### ISSUE TITLE
Exclude node_modules from Babel loader

### ISSUE THREAD

**Issue by Bottersnike** [preactjs/preact-cli#1013]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug

**What is the current behaviour?**
When building using `preact watch`, bable appears to be run on every package in `node_modules`. This is problematic with large packages, such as `react-icons` or `zxcvbn`, causing the build to essentially freeze.

**If the current behaviour is a bug, please provide the steps to reproduce.**
- Create a new project
- Install a large package (e.g. `zxcvbn` or `react-icons`)
- Run `preact watch`

**What is the expected behaviour?**
Packages in `node_modules` will be skipped by babel so building doesn't take hours.

**Please mention other relevant information.**
`preact info` failed, but the output of `npm list` is at https://hastebin.com/raw/anifubexot. (without `zxcvbn` or `react-icons`, as they were uninstalled locally so builds could complete)

**Comment by rschristian** [comment]
This has always been intentional, as shipping raw `node_modules` is somewhat error prone. It might be slower for poorly set up packages, but gives the user a lot more control and ensures you're not shipping content that doesn't adhere to the browserlist config to your users.
