### ISSUE TITLE
App doesn't render properly with preact build --no-prerender 

### ISSUE THREAD

**Issue by bilafish** [preactjs/preact-cli#1017]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug

**What is the current behaviour?**
Added the --no-prerender flag to build script but realised deployed app does not render properly.
See example here: [https://nfc-reader-ku2p1w642.now.sh/](https://nfc-reader-ku2p1w642.now.sh/)

**If the current behaviour is a bug, please provide the steps to reproduce.**
- Create a preact project using default template
- Change build script to "preact build --no-prerender" in package.json
- Deploy

**What is the expected behaviour?**
App should render normally as per demo preact app.

**Comment by prateekbh** [comment]
what version of `@preact/async-loader` are you on?

**Comment by bilafish** [comment]
@prateekbh Seems to be v 3.0.0-rc.9 as taken from node_modules/@preact/async-loader folder of my project.
```
{
  "name": "@preact/async-loader",
  "version": "3.0.0-rc.9",
  "description": "Preact's async component loader for Webpack",
  "files": [
    "*.js"
  ],
  "engines": {
    "node": ">=6"
  },
  "dependencies": {
    "kleur": "^3.0.3",
    "loader-utils": "^1.1.0"
  },
  "peerDependencies": {
    "preact": "^8.1.0"
  },
  "gitHead": "ef9af643837a7a94f9d2d683c36a549c8b710ec2"
}
```

**Comment by Steffo99** [comment]
I think I'm experiencing this bug too with 3.0.0-rc.9 🤔

How can I help in reproducing it?

**Comment by bilafish** [comment]
Based on observation, this seems to only affect the class CSS styles in the Header component for some reason. When I inspected the header element in browser, all the DOM elements in header do not have any classes, hence the styles are missing.
The CSS styles for the route components like home/about seems to work as expected.

**Comment by Steffo99** [comment]
Can you please check [my repo](https://github.com/Steffo99/steffo.eu) (live
at [steffo.eu](https://steffo.eu))?

I think the same thing is happening to my Box component...

**Comment by prateekbh** [comment]
Will do

**Comment by prateekbh** [comment]
we have the [fix](https://github.com/preactjs/preact-cli/pull/1011) in, will be releasing a version that should fix this.
by EOW

**Comment by prateekbh** [comment]
should be fixed with rc.10.

Happy to re-open if it still persist

**Comment by Steffo99** [comment]
Yay! It works! Thanks :D
