### ISSUE TITLE
cant use preact as command (preact are not in my path)

### ISSUE THREAD

**Issue by Julian-B90** [preactjs/preact-cli#1025]
**Do you want to request a _feature_ or report a _bug_?**
A Bug.

**What is the current behaviour?**
After install `npm i -g preact` i can´t type preact in the shell. 

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. Install preact-cli `npm install -g preact-cli`
2. type preact in the shell
3. preact cant be found

**What is the expected behaviour?**
After install preact-cli i want to use preact as a command

OS: macOS 10.15.3
Terminal: iTerm2 3.3.9
Shell: fish 3.0.2
Installed Path: /usr/local/Cellar/node/13.8.0/bin/preact
Node: v12.16.1
npm: 6.13.4
preact-cli: 2.2.1

**Comment by mikolaj6r** [comment]
Do other global installed packages work when invoked from shell ?
