### ISSUE TITLE
Enable optional-chaining & nullish-coalescing in preset-env

### ISSUE THREAD

**Issue by reznord** [preactjs/preact-cli#1033]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the expected behaviour?**
Support babel stage 3 features in preact-cli

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Right now, we can use optional-chaining with preact-cl@rc since we don't support them in our babel config.

**Please mention other relevant information.**
By setting `shippedProposals` to true, we can use the following [proposals](https://github.com/babel/babel/blob/master/packages/babel-preset-env/data/shipped-proposals.js#L9-L15) in CLI

**Comment by reznord** [comment]
In current babel versions, `shippedProposals` defaults to true. But since we use `preset-modules` for generating `esm build`, we need to wait until next version of `preset-env` is released (after [this PR](https://github.com/babel/babel/pull/11083) merges in babel).

**Comment by aethelz** [comment]
PR in question seems to be merged quite some time ago.

**Comment by reznord** [comment]
This is fixed in 3.0.0-rc.14 with babel updates.
