### ISSUE TITLE
Building Repositories with multiple Preact apps

### ISSUE THREAD

**Issue by e-compton** [preactjs/preact-cli#1044]
**Do you want to request a _feature_ or report a _bug_?**
Feature
**What is the current behaviour?**
Can only run `preact watch` on a single preact app.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
I'm developing an app that will be embedded as a third party app in a client's website. This app consists of multiple components:
- Two iframes, each containing preact components.
- A script to create these iframes on page load (needs to be bundled with webpack).

I'd like all these components to exist in the same repository, and to be able to start a single hot-reloading server for development.

**Potential Solution 1**
Export the Preact webpack config into node.js. So that it can be imported into my own custom webpack config. For example:
```js
// webpack.config.js
const Preact = require('preact-cli');

module.exports = [
  new Preact({
    src: './src/iframe1',
    dest: './build/iframe1'
  }),
  new Preact({
    src: './src/iframe2',
    dest: './build/iframe2'
  }),
  {
      entry: './src/plugin/index.js',
      ...
  }
];
```

**Potential Solution 2**
Overload the cli so that it can accept multiple src/dest values:
```
preact build --src src/iframe1 --dest build/iframe1 --src src/iframe2 --dest build/iframe2
```
But then I would still need a separate server for the additional script and also these arguments could be difficult to resolve in the cli.

**Potential Solution 3**
Provide some documentation on how to create my own Webpack config for building Preact X apps. So that I can build my own custom solution. But this would inevitably lose some of the complex optimisations that the preact-cli performs.

**Potential Solution 4**
Add a new parameter on `preact watch` / `preact build` that live reloads my code to a directory that can then be watched by another server. For example:
```
preact build  --watch --src iframe1 --dest build/iframe1 &
preact build  --watch --src iframe2 --dest build/iframe2 &
http-serve ./build
```

**Please mention other relevant information.**

Please paste the results of `preact info` here.

  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Safari: 13.0.5
  npmPackages:
    preact: ^10.3.2 => 10.3.2 
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.9 
    preact-render-to-string: ^5.1.4 => 5.1.4 
    preact-router: ^3.2.1 => 3.2.1

**Comment by e-compton** [comment]
For anyone who comes across this issue in the future. I ended up writing my own webpack config:
```js
const path = require('path');
const webpack = require('webpack');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CompressionPlugin = require('compression-webpack-plugin');
 
const entry = {
  main: './src/main/index.js',
  launcher: './src/launcher/index.js',
  plugin: './src/plugin/index.js'
};

module.exports = {
  entry,

  output: {
    path: path.join(__dirname, '..', 'build'),
    publicPath: '/',
    filename: '[name]/bundle.[contentHash].js'
  },

  resolve: {
    alias: {
      react: 'preact/compat',
      'react-dom': 'preact/compat'
    }
  },

  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      },
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader']
      }
    ]
  },

  plugins: [
    new CleanWebpackPlugin(),
    new webpack.ProvidePlugin({
      h: ['preact', 'h'],
    }),
    ...Object.keys(entry).map(
      name =>
        new HtmlWebpackPlugin({
          title: `Client ${name}`,
          filename: `${name}/index.html`,
          inlineSource: '.(js|css)$',
          template: `src/${name}/template.ejs`,
          chunks: [name],
          meta: {
            viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no'
          }
        })
    ),
    new CompressionPlugin({
      filename: '[path].br[query]',
      algorithm: 'brotliCompress',
      test: /\.js$|\.css$/,
      compressionOptions: { level: 11 },
      threshold: 10240,
      minRatio: 0.8,
      deleteOriginalAssets: false,
    }),
    new MiniCssExtractPlugin({
      filename: '[name]/style.[hash].css'
    })
  ]
};

```

**Comment by wansiedler** [comment]
Perfect! Thank you!
