### ISSUE TITLE
preact-cli 3 typescript config does no support fragments

### ISSUE THREAD

**Issue by b-gyula** [preactjs/preact-cli#1057]
**Do you want to request a _feature_ or report a _bug_?**
I guess is more _feature request_

**What is the current behavior?**
When the `<> ... </>` short form of fragments used with typescript, tsc gives the error:

`TS17016: JSX fragment is not supported when using --jsxFactory`

Using the generated config from the `typescript` template created `preact create typescript [app name]` command

_tsconfig.json:_
```json
{
    "compilerOptions": {
        "target": "ES5",
        "module": "ESNext",
        "allowJs": true,
        "jsx": "react",
        "jsxFactory": "h",
        "strict": true,
        "moduleResolution": "node",
        "esModuleInterop": true
    },
    "include": ["src/**/*.tsx", "src/**/*.ts"]
}
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
Support the `<> ... </>` short form of fragments

**If this is a feature request, what is motivation or use case for changing the behaviour?**

Preact X supports fragments, _preact-cli_ shall also

**Please mention other relevant information.**
```
Environment Info:
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 10.16.1 - C:\nodejs\node.EXE
    Yarn: 1.22.0 - C:\nodejs\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    preact: ^10.3.1 => 10.3.4
    preact-cli: ^3.0.0-rc.10 => 3.0.0-rc.10
    preact-render-to-string: ^5.1.4 => 5.1.4
    preact-router: ^3.2.1 => 3.2.1
	typescript: 3.8.3
```

**Comment by prateekbh** [comment]
cc: @ForsakenHarmony @reznord
