### ISSUE TITLE
Chunk css is inserted before bundle on production, inconsistent with dev environment

### ISSUE THREAD

**Issue by Inviz** [preactjs/preact-cli#1106]
### Steps to reproduce

1. Use some css in the bundle
2. Create a lazy loading chunk with some css in it
3. Navigate to the page that loads the chunk

### Expected Behavior

In production environment, I expect both csses to be in the same order as in dev environment - chunk after bundle.

### Actual Behavior
1. In development `<style>` element of the chunk will be injected after the bundle css
2. In production `<link>` element of the chunk will be inserted before the bundle css (chunk in head, bundle before `</body>`)

<img width="524" alt="Screen Shot 2020-04-02 at 14 37 51" src="https://user-images.githubusercontent.com/2708/78220187-9ee67600-74f3-11ea-9b5c-24072706a7f4.png">

### Conversation in Slack with prateekbh
> ohh i guess i know whats happening
> bundle is placed by. us at the end of the body
> where as chunks are inserted by webpack
> at runtime in headtag

**Comment by Inviz** [comment]
Thanks!

The reason stylesheet order matter is that it's a tie-breaker in case multiple selectors with the same specificity affect the same properties of the same element. Right now i'm seeing different visual results between production and development.

**Comment by developit** [comment]
Ah this makes sense. We need to adjust where we are injecting the prerendered chunks. Maybe we could just set `inject:'body'` here?
https://github.com/preactjs/preact-cli/blob/605c965de7da96e974ded1aa511b747b06e1c5a3/packages/cli/lib/lib/webpack/render-html-plugin.js#L71

**Comment by Inviz** [comment]
@developit I tried 
```
  helpers.getPluginsByName(config, 'HtmlWebpackPlugin')[0].plugin.options.inject = 'body';
```

but this didn't seem to do anything

**Comment by prateekbh** [comment]
I posted an update here: 
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/212

May be for now we can just make them consistent? would that help?

**Comment by Inviz** [comment]
Yeah that would certainly help for me. If possible, that chunks should be inserted after the bundle.

**Comment by Inviz** [comment]
I personally don't mind either all of them will be in head, or all of them be in body. thank you

**Comment by developit** [comment]
This is actually caused by Critters: it inlines your critical CSS into a style tag in `<head>`, then moved the `<link>` tag to the end of the document so it loads without blocking JS. 

Critters has a `preload:"swap"` option that does this in-place - that might work better for you?

**Comment by prateekbh** [comment]
@developit do you think our currrent choice of `preload` strategyy is good or should we switch to `swap` since more people might encounter this?

**Comment by developit** [comment]
I avoided swap as the default here because it requires JavaScript, but I think 100% of CLI apps would fail without JS enabled anyway..

**Comment by prateekbh** [comment]
makes sense, also this will make everything a lot more intuitive  i agree
