### ISSUE TITLE
Can only run build on MacOS and not Windows [typescript]

### ISSUE THREAD

**Issue by daniel-sudz** [preactjs/preact-cli#1115]
**Do you want to request a _feature_ or report a _bug_?**
Report a Bug
**What is the current behaviour?**
Cannot run build on windows
**If the current behaviour is a bug, please provide the steps to reproduce.**
preact-cli create typescript mysite
preact watch
```
Error: Error at C:\Users\danie\Desktop\mysite\mysite\preact.config.js:
TypeError: transformer is not a function
```
npm start
```
> per-env
```
Nothing happens

**What is the expected behaviour?**
npm run start should start the dev environment and preact watch should as well
**Please mention other relevant information.**
This works on macOS for me but not windows for some reason
Please paste the results of `preact info` here.
```
Unknown argument: info
```

**Comment by daniel-sudz** [comment]
Same issue reported here #1062

**Comment by ForsakenHarmony** [comment]
Should be fixed now
