### ISSUE TITLE
Double render 

### ISSUE THREAD

**Issue by devalexandre** [preactjs/preact-cli#1130]
When use preact_root

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><% preact.title %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link rel="apple-touch-icon" href="./assets/icons/apple-touch-icon.png">
		<% preact.headEnd %>
	</head>
	<body>
<div id="preact_root"></div>
	<% preact.bodyEnd %>
	</body>
</html>

```

**Comment by developit** [comment]
This is happening because you have 2 elements with the ID preact_root. When Preact boots up, it gets a reference to the first one, which is the empty duplicate you created here. 

You can address this by removing the bodyEnd block.

**Comment by devalexandre** [comment]
but if you remove the bodyEnd, it will not fail to load the .js that are generated dynamically?

**Comment by prateekbh** [comment]
why do we want in the markup `<div id="preact_root"></div>`

**Comment by devalexandre** [comment]
for do SSR with preact

[template ssr](https://github.com/devalexandre/preact-ssr)

**Comment by devalexandre** [comment]
for do SSR have get root tag for render components, have somebody to remove double render?

**Comment by devalexandre** [comment]
here, get a preact_root, but uf I use this id double render
https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/entry.js#L39
