### ISSUE TITLE
How to disable Pre-rendering in cli?

### ISSUE THREAD

**Issue by higimo** [preactjs/preact-cli#1132]
I don't need pre-rendering, how do I turn it off?

**Comment by RyanChristian4427** [comment]
Right from the ReadMe:

> * drop out of prerendering by passing --no-prerender flag to preact build

**Comment by developit** [comment]
Yep, just `preact build --no-prerender` to turn it off.

**Comment by higimo** [comment]
@RyanChristian4427 @developit `preact build --no-prerender` breaks the rendering of my application, in particular the attributes of the tags are not inserted.

**Comment by RyanChristian4427** [comment]
I'm no expert or authority on Preact, so while I haven't heard of this happening before, I can take a look at this for you if you have a repo or sandbox that reproduces this issues.

**Comment by developit** [comment]
@higimo which version of preact-cli are you using? Paste the output of `./node_modules/.bin/preact info`.

There was a bug in one of the recent alpha releases of preact-cli 3 that would have caused this, but it has been fixed in the latest release.

**Comment by higimo** [comment]
@developit I use preact-cli 2.2.1

**Comment by developit** [comment]
@higimo please paste the output of the above command - most folks are actually not running preact-cli 2 in their projects, they just use preact-cli 2 to scaffold new projects. The globally installed version of preact-cli isn't what your project uses, it uses the one defined in your package.json.

Alternatively, if you could paste the output of `npm ls | grep preact` that would suffice.

**Comment by higimo** [comment]
@developit 
```
λ npm ls | grep preact
+-- enzyme-adapter-preact-pure@2.2.0
| `-- preact-render-to-string@4.1.0
+-- jest-preset-preact@1.0.0
+-- UNMET PEER DEPENDENCY preact@10.3.2
+-- preact-cli@3.0.0-rc.9
| +-- @preact/async-loader@3.0.0-rc.9
| +-- UNMET PEER DEPENDENCY preact@^8.1.0
+-- preact-compat@3.19.0
| +-- UNMET PEER DEPENDENCY preact@^8.2.7
| +-- preact-context@1.1.4
| +-- preact-render-to-string@3.8.2
| +-- preact-transition-group@1.1.1
+-- preact-render-spy@1.3.0
| `-- preact-render-to-string@3.8.2
+-- preact-render-to-string@5.1.4
+-- preact-router@3.2.1npm
```

**Comment by developit** [comment]
@higimo run this:

```sh
npm i preact@latest preact-router@latest preact-render-to-string@latest
npm rm preact-compat
```

**Comment by higimo** [comment]
@developit it works, thanks!
