### ISSUE TITLE
To turn off the service worker

### ISSUE THREAD

**Issue by higimo** [preactjs/preact-cli#1133]
I don't need a service worker, how do I turn it off? I use preact-cli 2.2.1

**Comment by RyanChristian4427** [comment]
Right from the ReadMe:

> You can disable default: true flags by prefixing them with --no-<option>; for example, --no-sw, --no-esm, and --no-inline-css.

> --sw               Generate and attach a Service Worker  (default true)

**Comment by developit** [comment]
@RyanChristian4427 thanks!

**Comment by higimo** [comment]
`"build": "preact build --no-sw --no-ssr --no-esm --no-inline-css",`

Good job!
