### ISSUE TITLE
Duplicated styles when using CSS pre-processors

### ISSUE THREAD

**Issue by sebastianks** [preactjs/preact-cli#1139]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Duplicate styles when using SCSS.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Create a project, add SCSS (sass-loader etc.) and make a single file with styling of an element. This will now appear twice when you inspect it with your Devtool.

**What is the expected behaviour?**
That the styling only appears once.

**Please mention other relevant information.**
This seems to be happening on [https://preactjs.com/](https://preactjs.com/) too. If you inspect one of the primary buttons they'll have duplicated styles too.

This does not happen when using `styled-components`.

```
Environment Info:
  System:
    OS: Linux 5.6 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 13.12.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Firefox: 75.0
  npmPackages:
    preact-cli: 3.0.0-rc.6 => 3.0.0-rc.10
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.10
```

**Comment by prateekbh** [comment]
is one set of those styles coming from a style tag and another from a css file?
// @marvinhagemeister

**Comment by sebastianks** [comment]
@prateekbh yes, that seems correct.

**Comment by steindaniel** [comment]
@prateekbh Any update on this issue?

**Comment by prateekbh** [comment]
hi! this is by design on preact-cli. we inject critical styles in the <style> tag in head, so that your first paint is fast.

if this by any means is a problem use `--no-inline-css` flag with `preact build`. Lemme know if this helps

**Comment by UbiquitousBear** [comment]
@prateekbh How do you determine critical styles?

**Comment by prateekbh** [comment]
https://github.com/GoogleChromeLabs/critters

**Comment by sebastianks** [comment]
It seems like this an intended feature, and I will therefore close this issue.
