### ISSUE TITLE
@preact/async-loader demands preact@^8 as peerDependency

### ISSUE THREAD

**Issue by ezhikov** [preactjs/preact-cli#1167]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**

pnpm with flag `--strict-peer-dependencies` errors out with default template since @preact/async-loader demands preact@^8.1.0

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Create new preact-cli project without installing dependencies
1. Install typescript (this is also a peer dependency) with `pnpm i --strict-peer-dependencies typescript`. 
    1. If you don't have pnpm and don't want to install it, you can run `npx pnpm i --strict-peer-dependencies typescript`.

**What is the expected behaviour?**

Project works with default template.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

I'm working on monorepo controlled by rush and pnpm as package manager. While I can disable streect-peer-dependencies flag, it is either on for everything, or off for everything. In past I had problems with incorrect peerDependencies, so I'd prefer not to change this setting.

Please paste the results of `preact info` here.

Environment Info:
-  System:
    - OS: Linux 4.4 Arch Linux
    - CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
- Binaries:
    - Node: 12.16.1 - /home/linuxbrew/.linuxbrew/opt/node@12/bin/node
    - Yarn: 1.22.4 - /home/linuxbrew/.linuxbrew/bin/yarn
    - npm: 6.13.4 - /home/linuxbrew/.linuxbrew/opt/node@12/bin/npm

**Comment by developit** [comment]
Ah, yes. This is a bug.

**Comment by reznord** [comment]
This is fixed in the latest [3.0.0-rc.16](https://github.com/preactjs/preact-cli/tree/3.0.0-rc.16)
