### ISSUE TITLE
Prevent size plugin from running on SSR build

### ISSUE THREAD

**Issue by psabharwal123** [preactjs/preact-cli#1175]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
size plugin runs on both SSR build and actual build so as a result in the actual build the previous size of every chunk is 0 eg.
 27.chunk.*****.esm.js ⏤  5.01 kB (+5.01 kB)

**If the current behaviour is a bug, please provide the steps to reproduce.**
preact build on any project

**What is the expected behaviour?**
size plugin should run only during actual build

**If this is a feature request, what is motivation or use case for changing the behaviour?**
to be able to determine which build causes an increase in a particular chunk

**Please mention other relevant information.**

Please paste the results of `preact info` here.
Environment Info:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    preact: ^10.2.1 => 10.2.1 
    preact-cli: 3.0.0-rc.10 => 3.0.0-rc.10 
    preact-render-to-string: ^5.1.3 => 5.1.3 
    preact-router: ^3.1.0 => 3.1.0

**Comment by rschristian** [comment]
Should be fixed with #1407
