### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number

### ISSUE THREAD

**Issue by sumanthratna** [preactjs/preact-cli#1178]
# Bug

## Current behaviour
I am unable to create a project with only numeric characters in its name.

## Steps to reproduce
`preact create typescript 2021` returns `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number`.

## Expected behaviour
Preact creates a directory at `./2021` with my Preact project. 

## Other relevant information
- macOS 10.15.5 Beta 4
- npm v6.14.4
- preact-cli 2.2.1

`preact create typescript 2021 --force` doesn't fix the issue.

## `preact info`:
```
         ▄▄
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌ 
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌ 
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 2.2.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
For help with a specific command, enter:
  preact help [command]

Commands:
  create [template] [dest]  Create a new application.
  build [src] [dest]        Create a production build in build/
  watch [src]               Start a development live-reload server.
  serve [dir]               Start an HTTP2 static fileserver.
  list                      List all official templates

Options:
  -h, --help  Show help                                                [boolean]

Unknown argument: info
```

**Comment by RyanChristian4427** [comment]
The following should work for you.

```
npx preact-cli@3.0.0-rc.10 create typescript 2021
```
