### ISSUE TITLE
npm ERR! peer dep missing: ajv

### ISSUE THREAD

**Issue by marcoSven** [preactjs/preact-cli#1186]
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behaviour?**
Missing npm dependencies

**If the current behaviour is a bug, please provide the steps to reproduce.**
Mac Node v12.6.0 NPM 6.9.0
`npm install -g preact-cli
 npm list --global --depth=0
`
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

**Comment by rschristian** [comment]
Cannot reproduce, might've been corrected at some point upstream or here.
