### ISSUE TITLE
Async CSS loading is broken in Firefox 77

### ISSUE THREAD

**Issue by sampotts** [preactjs/preact-cli#1199]
**Do you want to request a _feature_ or report a _bug_?**

This is a bug. It seems to be resolved in Firefox nightly but at this moment it's broken on the v77 beta build of Firefox. It could be a beta issue, if someone could test on stable that'd be awesome. As a workaround I've just locked the version at `3.0.0-rc.9` in our projects. 

**What is the current behaviour?**

The stylesheet loaded via the new technique introduced in `3.0.0-rc.13` is broken on Firefox 77. 

Prior to `3.0.0-rc.13` stylesheets were loaded like this:

```html
<head>
  <link href="/bundle.css" rel="preload" as="style">
</head>
<body>
  ...
  <link rel="stylesheet" href="/bundle.css">
</body>
```

In `3.0.0-rc.13` they are now loaded with the following snippet:

```html
<link href="/bundle.css" rel="preload" as="style" onload="this.rel='stylesheet'" />
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

A test case is here:
https://jsfiddle.net/6gnwvfoe/

If the font stays as the default browser serif font, then you're experiencing the issue. Chrome and Safari seem fine. 

**What is the expected behaviour?**

The stylesheet loads as normal.

**Comment by RyanChristian4427** [comment]
Windows, stable Firefox 76.0.1 seems to be okay. The Inter var font is loaded and used.

**Comment by sampotts** [comment]
Looks like there's a Mozilla issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1626997

Some more info here:
https://twitter.com/Sam_Potts/status/1265446870790230016?s=20

**Comment by prateekbh** [comment]
cc @developit

**Comment by developit** [comment]
Ah! Yikes. Here's a workaround you can throw in your `preact.config.js`:

```js
// preact.config.js
export default function(config, env, helpers) {
    const critters = helpers.getPluginsByName(config, 'Critters')[0];
    if (critters) {
        // The default strategy in Preact CLI is "media",
        // but there are 6 different loading techniques:
        // https://github.com/GoogleChromeLabs/critters#preloadstrategy
        critters.plugin.options.preload = 'body';
    }
}
```

**Comment by sampotts** [comment]
Awesome, cheers!

**Comment by developit** [comment]
For my own curiosity - was this issue present in any Firefox mainline versions?

**Comment by sampotts** [comment]
I just checked 76.0.1 (stable) on another machine and it was the same as 77, i.e. broken.

**Comment by Inviz** [comment]
also 75, and mobile versions of firefox

**Comment by aethelz** [comment]
This behavior also breaks compatibility with old chromes as well (confirmed on Chrome 21.0.1180.60)
