### ISSUE TITLE
Source maps broken for .esm.js file, work fine for non esm js files

### ISSUE THREAD

**Issue by psabharwal123** [preactjs/preact-cli#1206]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
After updating from rc.4 to rc.10 source maps broken for all .esm.js files but work fine for non esm files
eg. of a source map for file bundle.43470.esm.js -
`{"version":3,"sources":[],"names":[],"mappings":"","file":"bundle.43470.esm.js","sourceRoot":""}`

**If the current behaviour is a bug, please provide the steps to reproduce.**
run preact build with esm flag

**What is the expected behaviour?**
source map generated should be correct

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
Environment Info:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    preact: ^10.2.1 => 10.2.1 
    preact-cli: 3.0.0-rc.10 => 3.0.0-rc.10 
    preact-render-to-string: ^5.1.3 => 5.1.3 
    preact-router: ^3.1.0 => 3.1.0

**Comment by psabharwal123** [comment]
@prateekbh @developit please let me know if you guys have any idea as to where i should look in the code / how to debug this.

**Comment by prateekbh** [comment]
can you verify that this works in `rc.4 `

**Comment by psabharwal123** [comment]
Hi
Yes I reverted to rc4 and it was working, interesting thing to note is that with rc4 the entry point contains 2 files bundle js and CSS, but rc10 it contains 3 files CSS, js, esm js (not sure if this helps)

**Comment by prateekbh** [comment]
oh right, this means that esm was not enabled back then

**Comment by prateekbh** [comment]
this is the root cause of this: https://github.com/prateekbh/babel-esm-plugin/issues/46

**Comment by psabharwal123** [comment]
in rc4 i did see .esm.js files generated for all routes and other js files tho, with correct sourcemaps

**Comment by prateekbh** [comment]
sorry what do you mean by 2 entry points then in https://github.com/preactjs/preact-cli/issues/1206#issuecomment-635640974?

**Comment by psabharwal123** [comment]
I was talking about what web pack considers as entry point files for purpose of performance budget, with RC.4 even with the esm flag, entry point would only have 2 files bundle.js and bundle.css

**Comment by psabharwal123** [comment]
thanks @prateekbh when will this be released?

**Comment by prateekbh** [comment]
we're working on a final RC for this month
