### ISSUE TITLE
Switch to a plugin system

### ISSUE THREAD

**Issue by SolarLiner** [preactjs/preact-cli#1210]
**Do you want to request a _feature_ or report a _bug_?** Feature request

**What is the current behaviour?** Preact CLI relies on templates to provide customized boilerplates to fit the needs of users. Need TypeScript? Use the provided TypeScript template. Want to start with Material UI ? We've got you covered. The templates system is a good, simple system which has served the project well.

**What is the expected behaviour?** A solution to the composability problem is plugins. It has been adopted by other projects (most notably, Vue and Angular) as a way to easily compose 

**If this is a feature request, what is motivation or use case for changing the behaviour?**  The main downside is that templates are not composable. If you want TypeScript *and* Material UI, you need to setup a template that features both, which brings the total to 3 different templates that need to be maintained. Plugins, on the other hand, separate the templating burden into logical packages and allow them to be easily composed. More plugins don't need to be created to support a combination of different features.

**Please mention other relevant information.** Plugins can go a lot further than just solving the templating problem - they allow customization of the CLI at its core. Prerendering for example could be extracted from the CLI into a plugin which removes weight from it in case it's not needed, which in turns mean we can swap prerendering for another solution (i.e. a custom SSR server or a proper static site generator, Nuxt-style server routing, etc.).

I have setup an experimental project re-implementing the CLI using a plugin-based approach, with example plugins adding TypeScript, SASS/SCSS/LESS support, and a compatibility plugin that restores templating and usage of `preact.config.js` (which I don't find is needed in this version of the CLI) [here](https://github.com/preactjs/preact-cli-experiment)

I tried fitting this into the issue template as best I could :upside_down_face:

**Comment by ForsakenHarmony** [comment]
How do plugins replace templates? 🤔

**Comment by SolarLiner** [comment]
This is done by having the CLI handle plugin installation (through and `add` command, for example `preact add typescript` would call the package manager to install the plugin, and invoke its `install` hook, which the plugin uses to make changes to the project. The CLI provides an API which writes data to files relative to the project root (no *actual* templating implemented, though this could easily be added).
[This function](https://github.com/preactjs/preact-cli-experiment/blob/b7cc3e66b483659e0d20480f9610b72a13cff583/packages/cli-plugin-typescript/src/index.ts#L13) is called in the case of the TypeScript plugin to make changes to the project (for now it only adds a `tsconfig.json` configuration).

In general, plugins are invoked through entrypoint functions in their exported file. The CLI itself calls `cli` for plugins to add CLI commands, `build` and `watch` for plugins which alter the build process (mainly to mutate the webpack config), and `install` to perform actions at installation (only when installed through `preact add <plugin>`, I don't think we can hook into package managers; which is why there's an alternate command `preact invoke <plugin>` which only calls the `install` export without installing the plugin first). Plugins can also call custom exported functions which allows plugins to extend each other.

The README on the experiment repo has documentation about various parts of the CLI (though I just realized I missed the `install` hook in the docs).

**Comment by rschristian** [comment]
While potentially compelling, this is unlikely to ever be built out / supported, so closing.
