### ISSUE TITLE
RC14 unable to load CSS without inline JavaScript

### ISSUE THREAD

**Issue by luhis** [preactjs/preact-cli#1211]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
The CSS loading mechanism requires inline JavaScript to be enabled

**If the current behaviour is a bug, please provide the steps to reproduce.**
Attempt to load a Preact app where inline JavaScript is disabled via CSP
Example site with issue here: https://codegolf.club

**What is the expected behaviour?**
App should load styles without allowing inline scripts as in RC10 and before

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
In RC14, the CSS links in the HTML have changed to include `onload="this.rel='stylesheet'`,  this causes issues with CSP, as it is inline JS, and it is rejected.  It should fallback to the other tag, but doesn't for some reason.

Please paste the results of `preact info` here.
Environment Info:
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    preact: 10.4.4 => 10.4.4
    preact-cli: 3.0.0-rc.14 => 3.0.0-rc.14
    preact-render-to-string: 5.1.8 => 5.1.8
    preact-router: 3.2.1 => 3.2.1

**Comment by prateekbh** [comment]
you can add the following in `preact.config.js`
```js
// preact.config.js
export default function(config, env, helpers) {
    const critters = helpers.getPluginsByName(config, 'Critters')[0];
    if (critters) {
        // The default strategy in Preact CLI is "media",
        // but there are 6 different loading techniques:
        // https://github.com/GoogleChromeLabs/critters#preloadstrategy
        critters.plugin.options.preload = 'default';
    }
}
```

**Comment by luhis** [comment]
@prateekbh excellent, that fixed my issue.
