### ISSUE TITLE
preact-cli doesnt create preact with the proper webpack version

### ISSUE THREAD

**Issue by brightredchilli** [preactjs/preact-cli#1217]
**Do you want to request a _feature_ or report a _bug_?**
a bug, i think?

**What is the current behaviour?**
i did a preact create with preact cli 2.2.1, and got a project with a package-lock with webpack set to 4x. From https://github.com/preactjs/preact-cli/issues/774#issuecomment-483148989, it seems like webpack should be set to 3x.

I'm runnning into the 'TypeError: transformer is not a function' issue with a barebones preact.config.js.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Do preact create, then verify the version of webpack

**What is the expected behaviour?**

I expect to get a version of webpack compatible with this cli.

**Please mention other relevant information.**

preact-cli 2.2.1

**Comment by RyanChristian4427** [comment]
Are you sure you're using Preact CLI v2.2.1? Most people are not using it in their projects, only using it to scaffold new ones. The globally installed version of preact-cli isn't what your project uses, it uses the one defined in your `package.json`.

Pasting the output of `./node_modules/.bin/preact info` would help.

**Comment by brightredchilli** [comment]
Ah! That makes sense, but also is confusing:
```
Environment Info:
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - ~/.zsh/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.zsh/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    preact: ^10.3.2 => 10.4.4
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.14
    preact-render-to-string: ^5.1.4 => 5.1.9
    preact-router: ^3.2.1 => 3.2.1
  npmGlobalPackages:
    preact-cli: 2.2.1

```
i see that im using the rc for preact-cli. I should probably open this in the templates repo then, correct? It seems that there should be a default-stable and default rc template, if that makes sense.

**Comment by RyanChristian4427** [comment]
> 
> i see that im using the rc for preact-cli. I should probably open this in the templates repo then, correct?

Sorry, poor wording on my part. Preact-CLI doesn't create the projects, but is used to scaffold them, but also does run them. It is a bit of a process to get your head around.

This is the valid place to comment on Webpack issues, but what comes out of `preact create` is not handled by the CLI itself, if that makes sense.

Sorry, I've probably still worded that horrendously. 

>
> It seems that there should be a default-stable and default rc template, if that makes sense.

While I can't comment on how the Preact team names things, "RC" does stand for "Release Candidate", which therefore should be quite stable. The idea is that it's a version that can be released, so long as significant bugs don't arise. 

All that being said, as you are using an RC release, it is correct for you to be using Webpack v4. If you want to v3, you can downgrade your app's Preact CLI version to v2.2.1.

**Comment by brightredchilli** [comment]
Ok, so this is a little bit roundabout, but I was running into this issue: https://github.com/preactjs/preact-cli/issues/774#issuecomment-483148989. I'm not doing font loading, I just have an empty preact.config.js:
```
export default {
  webpack(config) {
    return config
  }
}

```
And I got the error: 
```
TypeError: transformer is not a function
```

Might this be a bug for the preact project then?

**Comment by RyanChristian4427** [comment]
Using the default template, but adding your `preact.config.js`, I cannot reproduce this, which is odd.

But yes, this belongs here. Sorry, I thought you originally just wanted to switch CLI versions the template generated. I misunderstood.

**Comment by brightredchilli** [comment]
So i think piecing everything together... if I run `npx preact build`, it succeeds. preact is globally installed so its what is picked up when i run `preact build` on my machine. I feel like this is something more people would run into, seeing as to how the instructions to use this is to globally install preact-cli.

Not sure what the action item here is, but it seems to me that people should be told to either run `npx preact`, or not be installing another local preact-cli 🤷‍♀️(new to web dev so don't take me too seriously)

**Comment by RyanChristian4427** [comment]
Sorry, but just for clarity, are you running `preact build` from your terminal/command line, rather than running an NPM or Yarn command?

**Comment by brightredchilli** [comment]
yes, i am

**Comment by RyanChristian4427** [comment]
Well there's your problem. 

CLI apps run via executables in your `node_modules` folder. Basically, `npm run build`/`yarn build` know to look into the project's `node_modules` to find whatever `preact` is, and run it with the arguments you give. But when you run `preact` from your terminal, you're using your globally installed version instead.

That'll be your issue. Use NPM or Yarn. They should run your apps.
