### ISSUE TITLE
Inline critical path CSS during prerender

### ISSUE THREAD

**Issue by ethanroday** [preactjs/preact-cli#123]
Zero-config prerendering is great, but it would be awesome if critical path CSS could be inlined as well (or even just split out of the main `style.css`) during this process. The [Critical](https://github.com/addyosmani/critical) library is built to do just this, and there is even an associated [webpack plugin](https://github.com/nrwl/webpack-plugin-critical) (although I've had some issues getting it to work well).

I realize this could add bloat to `index.html`, but for a simple scenario like showing an app shell and a loading spinner while the main bundle gets downloaded, it would be a huge perceived performance benefit. (As an example, this is the strategy that https://www.flipkart.com/ implements. You can see it in action in Chrome by emulating a mobile device and disabling JS.)

PS: Loving this tool otherwise!

**Comment by developit** [comment]
Love the idea, and I think we could keep everyone happy by adding a flag like we do with `--prerender` itself, maybe even defaulting to having critical CSS inlining enabled (so it can be disabled via `--no-critical-css`).

**Comment by developit** [comment]
Ok just dropping a note here as I read up on deferring non-critical CSS today ([here's a good article on it](https://codepen.io/tigt/post/async-css-without-javascript#shove-it-in-the-body-3)).

There isn't an officially spec'd way to do it, but I think this would work quite well in our case:

```html
<html>
  <head>
    <style>/*critical CSS goes here*/</style>
  </head>
  <body>
    <link rel="stylesheet" href="/bundle.css">
  </body>
</html>
```

**Comment by kurtextrem** [comment]
Also interesting: https://gist.github.com/scottjehl/87176715419617ae6994
https://www.sitepoint.com/critical-rendering-path-css-fast-loading-website/

This task probably also opens up optimizations such as uncss/ucss

**Comment by kurtextrem** [comment]
https://github.com/kriasoft/isomorphic-style-loader/

**Comment by kurtextrem** [comment]
Another interesting project: https://github.com/gajus/usus "Renders page using Chrome Debugging Protocol (CDP)"

**Comment by thangngoc89** [comment]
@reznord I know this day would come. Check out https://github.com/gajus/usus 

Thanks @kurtextrem for the link

**Comment by reznord** [comment]
I'll take up this !! Self assigning !!

**Comment by reznord** [comment]
@thangngoc89 @developit How about this - https://github.com/kriasoft/isomorphic-style-loader ?

**Comment by thangngoc89** [comment]
It looks unnesserary complicated to me. Webpack gonna have first class css support soon so we can have css splitting put of the box. What's wrong with parsing generated HTML output for classes? We only need to inline those classes. Nothing else

**Comment by matthewlynch** [comment]
@developit / @reznord / @lukeed Could this be closed as there is a plugin now?

**Comment by developit** [comment]
Perhaps - I think we still might aim to include some rudimentary CSS inlining in the CLI out-of-the-box though.

**Comment by mfbx9da4** [comment]
> @thangngoc89 @developit How about this - https://github.com/kriasoft/isomorphic-style-loader ?

Isomorphic style loader uses [react context](https://reactjs.org/docs/context.html). Would like to avoid adding preact context to my app unless strictly necessary. 

The issue with the doing critical css prerender is that not all routes can be prerendered so SSR routes will suffer.

The compromise for SSR would be to do prerender on as many URLs as possible and when doing SSR pick a prerendered html file with as much of the critical CSS as possible.
