### ISSUE TITLE
automatically load css file

### ISSUE THREAD

**Issue by yangkennyk** [preactjs/preact-cli#1236]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behaviour?**
css file is not loaded automatically with preact widget template

**If the current behaviour is a bug, please provide the steps to reproduce.**
I'm using the https://github.com/preactjs-templates/widget with preact cli v3.0.0-rc.9

When I build the project, the css file is not loaded automatically if I just load the bundle.js . Emotion styles are all css components but I'm using tailwindcss as well and those a spit out as a css file.

**What is the expected behaviour?**
I believe the current behaviour is the intended behaviour 

**If this is a feature request, what is motivation or use case for changing the behaviour?**
so that preact widgets can be included with just a js snippet

**Please mention other relevant information.**

Please paste the results of `preact info` here.

Environment Info:
  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 72.0.2
    Safari: 13.1.1
  npmPackages:
    preact: ^10.4.4 => 10.4.4 
    preact-cli: ^3.0.0-rc.14 => 3.0.0-rc.14 
    preact-render-to-string: ^4.1.0 => 4.1.0 
    preact-router: ^3.2.1 => 3.2.1 
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.14

**Comment by RyanChristian4427** [comment]
Sorry for the late response, but, if I'm understanding your issue correctly, this is not really possible yet. See: https://github.com/developit/microbundle/issues/567#issuecomment-587001541 and https://github.com/developit/microbundle/issues/416#issuecomment-655988107.

**Comment by rschristian** [comment]
Closing as this is an issue with Microbundle and Microbundle has chosen to follow the spec, which means importing CSS into a JS module is a no-go. That assumes the user has a CSS loader configured, else, there will be errors and issues.
