### ISSUE TITLE
Named exports not working with async-loader

### ISSUE THREAD

**Issue by toniopelo** [preactjs/preact-cli#1237]
**Do you want to request a _feature_ or report a _bug_?**
This is a **Bug**

**What is the current behaviour?**
1/ Importing modules from `app.tsx` uses `async-loader` even if there is no `async!` prefix to it (why not)
2/ `async-loader` seems to not support named exports at all.

**If the current behaviour is a bug, please provide the steps to reproduce.**
```
src/
    - app.tsx
    routes/
        landing/
            - index.tsx
```

`app.tsx`
```
import { LandingPage } from 'routes/landing'
class App extends Components {

...

render() {
    return (
        ...
        <Router>
            ...
            <Route component={LandingPage}>
            ...
        </Router>
        ...
    )
}

export default App
```

`landing/index.tsx`
```
import { FunctionalComponent, h } from 'preact'
import LandingPageLegacy from 'legacy/src/core/js/forum/components/LandingPage'
import { LegacyComponent } from 'legacy/compat'

export const LandingPage: FunctionalComponent = () => {
  return (
    <div>
      <LegacyComponent component={LandingPageLegacy} />
    </div>
  )
}

export default LandingPage
```
-----
**1. Named export does not work**
```
⚠ WARN ./app.tsx 140:17-28
public_frontend_1  | "export 'LandingPage' was not found in 'routes/landing'
public_frontend_1  |  @ ./index.js
public_frontend_1  |  @ ../node_modules/preact-cli/lib/lib/entry.js
public_frontend_1  |  @ multi ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```
A `console.log(LandingPage)` at runtime yields `undefined`

**2. Switching back to default import `import LandingPage from 'routes/landing'` does work**
**3. Adding this**
```
import * as test from 'routes/landing'

...

class App extends Component ‘{
    ...
    render() {
        ...
        console.log(test)
        ...
    }
}
```
Logs:
![image](https://user-images.githubusercontent.com/9287511/84486781-268ff400-ac9e-11ea-8d1c-c84d7b73a93e.png)

At other places in my codebase this works fine because the `async-loader` is not doing the job.

**What is the expected behaviour?**
One of these
- Have the named exports working (prefered)
- Have it documented somewhere (didn't find any mention of this behavior)

**Comment by RyanChristian4427** [comment]
This was mentioned a while back in #757, though I'm not sure if anything's changed since that issue was opened. Moving your components out of `/routes` might be your best bet.

**Comment by toniopelo** [comment]
Thanks for the answer @RyanChristian4427 
I've opened a PR to update the readme with these info
