### ISSUE TITLE
switching to LESS: ValidationError: Invalid options object

### ISSUE THREAD

**Issue by br4nnigan** [preactjs/preact-cli#1247]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**

```
Build failed!

× ERROR C:/UsersC:/Users/xxx/AppData/Roaming/npm/node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--1-0!./src/components/header/style.less
Module build failed: ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'paths'. These properties are valid:
   object { lessOptions?, prependData?, appendData?, sourceMap?, implementation? }
    at validate (C:\Users\xxx\Documents\Workspace\my-project\node_modules\schema-utils\dist\validate.js:96:11)
    at Object.lessLoader (C:\Users\xxx\Documents\Workspace\my-project\node_modules\less-loader\dist\index.js:24:28)
    at Object.proxyLoader (C:\Users\xxx\AppData\Roaming\npm\node_modules\preact-cli\lib\lib\webpack\proxy-loader.js:23:16)
 @ ./src/components/header/style.less 4:14-360 18:2-22:4 19:20-366
 @ ./src/components/header/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ C:/Users/xxx/AppData/Roaming/npm/node_modules/preact-cli/lib/lib/entry.js
 @ multi C:/Users/xxx/AppData/Roaming/npm/node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
`$ npm install -g preact-cli`
`$ preact create default my-project`
`$ cd my-project && npm i --save-dev less less-loader`
`$ npm start dev` or `preact watch`

**What is the expected behaviour?**
the dev server hosting a running front end using styles from less files

**Please mention other relevant information.**

Please paste the results of `preact info` here.
```

         ▄▄
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 2.2.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
For help with a specific command, enter:
  preact help [command]

Commands:
  create [template] [dest]  Create a new application.
  build [src] [dest]        Create a production build in build/
  watch [src]               Start a development live-reload server.
  serve [dir]               Start an HTTP2 static fileserver.
  list                      List all official templates

Options:
  -h, --help  Show help                                                [boolean]

Unknown argument: info
```
"Unknown argument: info" ...  man I tried 2 preact boilerplates today already which weren't running, both (actually 3) jsx syntax implementations for SublimeText were buggy and now this too is failing in the very first steps and I can't even `preact info`. I'm thankful for all the work people put into open source but on a day like this I wonder if ANYTHING ever works. Sorry for the rant.

**Comment by RyanChristian4427** [comment]
Firstly, it doesn't seem that `info` was around for CLI version 2.2.1. I'd personally say to not even install the CLI, but to use NPX instead, but that's neither here nor there. The CLI version that comes bundled with your template, however, is the right version. You can add `info: preact info` to your `package.json` or simply run `node_modules/.bin/preact info` from your project root. Running `preact ...` from your terminal will use the globally installed version, which appears in your case to be v2.2.1.

What version of the Less Loader are you using? I know as of a few weeks ago you needed to use v5, as the CLI was not updated to be compatible with v6, but some work has been done on it since. I don't believe those fixes/updates for v6 have been released yet though, so someone can correct me if I'm wrong.

**Comment by br4nnigan** [comment]
`npx preact info` works fine.

It does work indeed with less-loader 5.0.0 instead of the current 6.x. Thank you!

Maybe the readme should reflect that?

`npm install --save-dev less less-loader@5.0.0`

**Comment by reznord** [comment]
@br4nnigan we have pushed a fix for this and will be available in the next rc release. Until then you can fallback to `less-loader@v5`
