### ISSUE TITLE
styles required with relative path leading to /src are not applied

### ISSUE THREAD

**Issue by br4nnigan** [preactjs/preact-cli#1250]
**Do you want to request a _feature_ or report a _bug_?**
bug, or configuration issue probably

**What is the current behaviour?**
see header? has no class
![grafik](https://user-images.githubusercontent.com/10244835/85020909-53964800-b171-11ea-8e5f-7e25202250ec.png)

**If the current behaviour is a bug, please provide the steps to reproduce.**
- preact create default my-project
- copy src/components/header/style.css to src/
- edit src/components/header/index.js to point to the new path `../../style.css`
- preact watch

**What is the expected behaviour?**
header styles being applied, header background being violet e.g.

**Please mention other relevant information.**

the compiler finds the file, you can verify this by renaming it, but the styles are not applied to the dom (actually the styles are inserted, but the class name not). 

Is this because of `../../`? No, I verified this by adding one more folder in depth and then going back 2 folders relative and it works. It only fails once the path leads to `src/`, or further up from there: `../../test/style.css`

Please paste the results of `preact info` here.
_System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 13.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0_

**Comment by RyanChristian4427** [comment]
CSS files imported from `/components` and `/routes` are the only ones treated as CSS modules. Importing from outside of those two means the CSS file isn't a module. You can test this by changing `<header class={style.header}>` to `<header class="header">`.

Depending on what you want to do, you can customize the Webpack config using your `preact.config.js` ([config to change can be found here](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/webpack/webpack-base-config.js#L229)) to work with any directories that you want. 

This is only turned on for `/components` and `/routes` so you can use the other directories to import styles globally, such as `index.js` importing `styles/index.css`. I think it's usually standard practice to keep your CSS file close to your component when using modules to cut down on the amount of searching you have to do, hence these defaults.

**Comment by br4nnigan** [comment]
Interesting. My intention was actually of organizing nature. 

Keeping the styles near the component is one option, and file structuring wise certainly the most clean, practical.
```
components
    header
        index.js
        style.css
```
The disadvantage is that in your editor you'll have lots of tabs open with files named index.js which is what I don't want!

Another option would be not to have a directory for every component, that would leave you with a components directory like this: 

```
components
    header.js
    header.css
    list.js
    list.css
```

So I think the solution I'd prefer would to keep the styles in a seperate directory, mirroring the component file names.

```
components
    header.js
    list.js
styles
    header.css
    list.css
```

I'll try out your suggested config change, thanks a lot for the fast reaction!

**Comment by RyanChristian4427** [comment]
And this is why styled components were born :)

Not that I'm suggesting you should use them, as I actually prefer plain ol' CSS imports, but this file-hell is why someone had the idea to simply combine the two. 

Glad I could be of use. Let me know if you need any help.

**Comment by br4nnigan** [comment]
Is it possible to use LESS with inline styles aswell?

**Comment by RyanChristian4427** [comment]
No, inline styling is just for writing CSS as JS. Obviously you can still import style sheets and use classes, but in a component, you only get standard CSS (in a JS naming convention).
