### ISSUE TITLE
Update typings-for-css-modules-loader dependencie to add formatter option

### ISSUE THREAD

**Issue by toniopelo** [preactjs/preact-cli#1252]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behaviour?**
We rely on a no-longer-maintained library for css typings that has no options for formatting created typing files

**What is the expected behaviour?**
Being able to format generated files with prettier for example.
A fork from the `typings-for-css-modules-loader` dead repo has been created with a `formatter` option out of the box.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
This avoids having constantly unrelevant unstaged files in your `git status` if you use prettier with `no-semi` for exemple.
Your typing files gets formatted when commited (with pre-commit hook) but gets regenerated soon after that with no diffs except for formatting. That's annoying.

**Please mention other relevant information.**
See this issue on [typings-for-css-modules-loader](https://github.com/Jimdo/typings-for-css-modules-loader/issues/94) for the fork author explanations.

**Comment by RyanChristian4427** [comment]
This sounds like an issue for the Typescript template. The CLI doesn't rely on that lib at all. 

[I've submitted a PR](https://github.com/preactjs-templates/typescript/pull/29) over there a few weeks back in regards to fixing another issue. See if whatever lib I used works for you (no clue, not a fan of modules myself).

**Comment by RyanChristian4427** [comment]
Sorry, only just had time to look into this a bit more. The solution I provided did not have a formatting option, so I swapped in the library you suggested instead. 

That should fit your needs, whenever someone has the chance to look at it/merge it in.

**Comment by toniopelo** [comment]
Thanks a lot, that's great. I'm gonna subscribe to the PR :)

**Comment by rschristian** [comment]
Solution implemented at https://github.com/preactjs-templates/typescript/pull/29
