### ISSUE TITLE
Cannot import async components: Undefined component passed to createElement()

### ISSUE THREAD

**Issue by hkh12** [preactjs/preact-cli#1293]
**Do you want to request a _feature_ or report a _bug_?**
It's a bug.

**What is the current behaviour?**
I'm trying to load a component from `src/components/async` directory, and get this error:
```
Uncaught Error: Undefined component passed to createElement()

You likely forgot to export your component or might have mixed up default and named imports<#text dangerouslySetInnerHTML="[object Object]" />

  in #text
  in AsyncComponent
  in App
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
```js
// src/components/async/Hello.js
export default function Hello() {
  return <h1>hello</h1>
}
```
```js
// src/index.js
import Hello from './components/async/Hello'
export default function App() {
  return <Hello />
}
```

**What is the expected behaviour?**
Load the component `Hello` as an async component.

**Please mention other relevant information.**

Please paste the results of `preact info` here.
```
Environment Info:
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (2) x64 AMD A9-9410 RADEON R5, 5 COMPUTE CORES 2C+3G
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.7.0 - ~/.npm-global/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
  npmPackages:
    preact: ^10.3.2 => 10.3.3 
    preact-cli: ^3.0.0-rc.16 => 3.0.0-rc.16 
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.16
```

**Comment by hkh12** [comment]
Update: `async!` prefix doesn't work too.

**Comment by RyanChristian4427** [comment]
I assume that, while this warning shows up in your console, the component does render? As that is what I can reproduce. 

One solution could be to use Lazy & Suspense. [While marked as experimental](https://preactjs.com/guide/v10/switching-to-preact#suspense), it does seem to suppress that warning.

```
import { Suspense, lazy } from 'preact/compat';
const Hello = lazy(() => import('./components/async/Hello'));

export default function App() {
    return (
        <Suspense fallback={<div>loading...</div>}>
            <Hello />
        </Suspense>
    )
}
```

**Comment by hkh12** [comment]
It actually prevents other things from rendering. Try adding something to `App` after `Hello`.

I've also noticed that downgrading to `3.0.0-rc.14` solves the problem.

**Comment by hkh12** [comment]
Found a better way to reproduce this:
```js
// src/index.js
import Hello from './components/async/Hello'
export default function App() {
  return <>
    <Hello />
    <div>This won't be rendered.</div>
  </>
}
```
But if you use an element instead of fragments the error will be gone.

**Comment by reznord** [comment]
@hkh12 can you just reproduce this in a repo and share if possible?

**Comment by hkh12** [comment]
@reznord https://github.com/hkh12/preact-cli-bug-1293

**Comment by reznord** [comment]
Awesome, thanks. Will look into it now.

**Comment by reznord** [comment]
@hkh12 this is resolved in the latest rc ([3.0.0-rc.17](https://github.com/preactjs/preact-cli/tree/3.0.0-rc.17)) today.

Feel free to re-open if you are still facing the issue 🙂

**Comment by hkh12** [comment]
Still facing the issue. I committed the updates to https://github.com/hkh12/preact-cli-bug-1293

**Comment by gokatz** [comment]
facing this issue in preact:10.4.7, preact-cli: 3.0.1. [downgrading preact](https://github.com/preactjs/preact-cli/issues/1293#issuecomment-655677355) CLI helped.

**Comment by FranciscoG** [comment]
also facing this issue:
- preact@10.5.7
- preact-router@3.2.1

trying to replicate it in a codesandbox but can't seem to
https://codesandbox.io/s/hopeful-aryabhata-1ynnj?file=/src/app.js

**Comment by cyclops26** [comment]
> also facing this issue:
> 
> * preact@10.5.7
> * preact-router@3.2.1
> * preact-cli@3.0.5
> 
> trying to replicate it in a codesandbox but can't seem to
> https://codesandbox.io/s/hopeful-aryabhata-1ynnj?file=/src/app.js

@FranciscoG did you find a resolution/or the issue? I'm running into this with the following packages, but like you in a sandbox it works. I've tried multiple node versions and started with a clean package-lock file and clean node_modules direction to no avail.

- preact@10.5.10
- preact-router@3.2.1
- preact-cli@3.0.5

**Comment by cyclops26** [comment]
I found that the resolution for me was to not use a second component declared within the same file and only to use imported components.... not sure why this was an issue though.

**Comment by hinst** [comment]
I am just getting started with Preact and I ran into this error when I tried to use my class component

🐞Uncaught Error: Invalid type passed to createElement(): [object Object]

```typescript
import { Component, ComponentChild, RenderableProps } from "preact";

interface ParameterTypesProps {
}

interface ParameterTypesState {
}

export class ParameterTypesPanel extends Component<ParameterTypesProps, ParameterTypesState> {
    constructor() {
        super({});
        this.state = {};
    }

    render(props?: RenderableProps<ParameterTypesProps, any>, state?: Readonly<ParameterTypesState>, context?: any): ComponentChild {
        return <div></div>;
    }
}
```

index.tsx:
```typescript
export function App() {
	return (
		<LocationProvider>
			<Header />
			<main>
				<Router>
					<Route path='/' component={Home} />
					<Route path='/ParameterTypes' component={new ParameterTypesPanel} />
					<Route default component={NotFound} />
				</Router>
			</main>
		</LocationProvider>
	);
}
```

Does someone by chance have an idea what is wrong here? And why is there no diagnostics information coming from Preact in the error message. Stack trace is not visible in browser console

**Comment by rschristian** [comment]
@hinst `preact-cli` is no longer maintained, see [the warning at the top of the ReadMe](https://github.com/preactjs/preact-cli?tab=readme-ov-file#preact-cli--).

Please switch to a supported tool, like a Vite via [`create-preact`](https://preactjs.com/guide/v10/getting-started#create-a-vite-powered-preact-app).

Edit: Never invoke/create components directly. Switch `new ParameterTypesPanel` to `ParameterTypesPanel`
