### ISSUE TITLE
Latest version, rc17, fails at building typescript project

### ISSUE THREAD

**Issue by rosenbjerg** [preactjs/preact-cli#1313]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug
**What is the current behaviour?**
yarn dev fails on latest version (rc17) of preact-cli, with the following error:
```
yarn run v1.21.1
$ preact watch
× ERROR ValidationError: ForkTsCheckerWebpackPlugin Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
I'm attempting to build a project that is based on the typescript template.

**What is the expected behaviour?**
I can build using yarn dev. It works fine after downgrading to rc16, so it must be a recent change.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
N/A

**Please mention other relevant information.**

Please paste the results of `preact info` here.
Version that does not work:
```
Environment Info:
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    preact: ^10.4.4 => 10.4.4
    preact-cli: 3.0.0-rc.17 => 3.0.0-rc.17
    preact-render-to-string: ^5.1.8 => 5.1.9
    preact-router: ^3.0.1 => 3.2.1

```

Version that works:
```
Environment Info:
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    preact: ^10.4.4 => 10.4.4
    preact-cli: 3.0.0-rc.16 => 3.0.0-rc.16
    preact-render-to-string: ^5.1.8 => 5.1.9
    preact-router: ^3.0.1 => 3.2.1

```

**Comment by smjnab** [comment]
Had the same issue. It seems it has to do with ForkTsCheckerWebpackPlugin that has been bumped from 4.x to 5.x in rc17 and in node_modules/preact-cli/lib/lib/webpack/webpack-base-config.js it is added with options

```
new ForkTsCheckerWebpackPlugin({
checkSyntacticErrors: true,
async: !isProd,
tsconfig: tsconfig,
silent: !isWatch,
})
```

and this is causing the error. I tested removing the options and moving my tsconfig.json to projectDir/src/ and that "solved" the issue. Not versed enough in webpack to know the actual issue or fix.
