### ISSUE TITLE
Console output provides incorrect instructions for starting development server

### ISSUE THREAD

**Issue by mattrossman** [preactjs/preact-cli#1319]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
The console says to run `npm run start`, but that script does not exist

**If the current behaviour is a bug, please provide the steps to reproduce.**
Create a default project with `preact create default my-project`

**What is the expected behaviour?**
The console should explain to run `npm run dev`

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
(that command doesn't exist, consider updating your issue template)

The full output from creating a starter project:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/22670878/87256640-77903500-c462-11ea-8e3f-a332609e0c81.png">

**Comment by RyanChristian4427** [comment]
This was noticed and fixed back in #1146, upgrade your CLI version to get the change. The same can be said for `preact info`. It is recommended to use CLI v3 though it is not (yet) the default install.
