### ISSUE TITLE
Running two builds in parallel?

### ISSUE THREAD

**Issue by jliebrand** [preactjs/preact-cli#1331]
Not sure if this is a bug or if this is simply not supported. I'm trying to run a few builds in parallel (building numerous projects in a mono repo). But I get

```
✖ ERROR Error: EEXIST: file already exists, mkdir '/tmp/preact-cli'
 
```

Is there a way to set which tmp folder is used? Or is running preact-cli in parallel simply not possible?

**Comment by developit** [comment]
oooh that's a strange one. I'm not actually sure where we're creating a temp directory.
