### ISSUE TITLE
Using Google Adsense in a Preact-CLI project

### ISSUE THREAD

**Issue by Yeahjoep** [preactjs/preact-cli#1339]
Hi guys! 

I have an issue and I've spent A LOT OF TIME trying to solve this. I am trying to add the Google Adsense code to my project. My status stays stuck at: "Your site needs work". The additional information explains that Google can't find the code. Eventhough I've added it (in multiple ways). 

What I've found out is that everytime this code:
`<script data-ad-client="ca-pub-#####" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`

gets transformed to this code:
`<script data-ad-client="ca-pub-#####" async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" data-checked-head="true"></script>`

This is how I'm trying to add the code:

**Option 1: In my app.js file**
```
componentDidMount() {
        //SetAdsense
        let script = document.createElement('script');
        script.setAttribute('data-ad-client','ca-pub-########' );
        script.setAttribute('async');
        script.src = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";           
        document.getElementsByTagName('head')[0].appendChild(script);
}
```

**Option 2: Using Helmet**

```
<Helmet>
                <script data-ad-client="ca-pub-#####" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
</Helmet>
```

Any idea how I can make Google see the provided Adsense code in my Head?

**Comment by ForsakenHarmony** [comment]
https://github.com/preactjs-templates/netlify/blob/master/template/src/template.html
If you update to preact-cli v3 it should generate the template in your project dir you can insert stuff into

**Comment by Yeahjoep** [comment]
Thanks! Is it also possible to implement the template.html is Preact-CLI 2.2.1?

**Comment by developit** [comment]
(we discussed elsewhere but I'll echo here for others)

In 2.2.1, the `--template` argument was relative to the `src` directory. Here's how to use it:

`package.json`:

```jsonc
{
  "scripts": {
    "dev": "preact watch --template template.html",
    "build": "preact build --template template.html"
  }
}
```

`src/template.html`:

```ejs
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><%= htmlWebpackPlugin.options.title %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath %>manifest.json">
		<% if (htmlWebpackPlugin.options.manifest.theme_color) { %>
			<meta name="theme-color" content="<%= htmlWebpackPlugin.options.manifest.theme_color %>">
		<% } %>
		<% for (var chunk of webpack.chunks) { %>
		 <% if (chunk.names.length === 1 && chunk.names[0] === 'polyfills') continue; %>
			<% for (var file of chunk.files) { %>
				<% if (htmlWebpackPlugin.options.preload && file.match(/\.(js|css)$/)) { %>
					<link rel="preload" href="<%= htmlWebpackPlugin.files.publicPath + file %>" as="<%= file.match(/\.css$/)?'style':'script' %>">
				<% } else if (file.match(/manifest\.json$/)) { %>
					<link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath + file %>">
				<% } %>
			<% } %>
		<% } %>
	</head>
	<body>
		<%= htmlWebpackPlugin.options.ssr({
			url: '/'
		}) %>
		<script defer src="<%= htmlWebpackPlugin.files.chunks['bundle'].entry %>"></script>
		<script>window.fetch||document.write('<script src="<%= htmlWebpackPlugin.files.chunks["polyfills"].entry %>"><\/script>')</script>
	</body>
</html>
```

**Comment by Yeahjoep** [comment]
> 
> 
> (we discussed elsewhere but I'll echo here for others)
> 
> In 2.2.1, the `--template` argument was relative to the `src` directory. Here's how to use it:
> 
> `package.json`:
> 
> ```js
> {
>   "scripts": {
>     "dev": "preact watch --template template.html",
>     "build": "preact build --template template.html"
>   }
> }
> ```
> 
> `src/template.html`:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> 	<head>
> 		<meta charset="utf-8">
> 		<title><%= htmlWebpackPlugin.options.title %></title>
> 		<meta name="viewport" content="width=device-width,initial-scale=1">
> 		<meta name="mobile-web-app-capable" content="yes">
> 		<meta name="apple-mobile-web-app-capable" content="yes">
> 		<link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath %>manifest.json">
> 		<% if (htmlWebpackPlugin.options.manifest.theme_color) { %>
> 			<meta name="theme-color" content="<%= htmlWebpackPlugin.options.manifest.theme_color %>">
> 		<% } %>
> 		<% for (var chunk of webpack.chunks) { %>
> 		 <% if (chunk.names.length === 1 && chunk.names[0] === 'polyfills') continue; %>
> 			<% for (var file of chunk.files) { %>
> 				<% if (htmlWebpackPlugin.options.preload && file.match(/\.(js|css)$/)) { %>
> 					<link rel="preload" href="<%= htmlWebpackPlugin.files.publicPath + file %>" as="<%= file.match(/\.css$/)?'style':'script' %>">
> 				<% } else if (file.match(/manifest\.json$/)) { %>
> 					<link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath + file %>">
> 				<% } %>
> 			<% } %>
> 		<% } %>
> 	</head>
> 	<body>
> 		<%= htmlWebpackPlugin.options.ssr({
> 			url: '/'
> 		}) %>
> 		<script defer src="<%= htmlWebpackPlugin.files.chunks['bundle'].entry %>"></script>
> 		<script>window.fetch||document.write('<script src="<%= htmlWebpackPlugin.files.chunks["polyfills"].entry %>"><\/script>')</script>
> 	</body>
> </html>
> ```

True and we've ended the thread with an advice to update to Preact-CLI v3

**Comment by Yeahjoep** [comment]
So I'm still busy with this issue. I'm sorry for getting back at an issue which has already been closed but I've figured out something which I'd like to discuss.

So I've just found out that the reason for not getting Adsense implemented is not related to the way I've implemented the Adsense code snippet. 2 reasons for this assumption:

 1. Adsense has unapproved my website with the message: No content provided (which is strange because I've tested the crawlresults in the Google Webmaster tools and it crawls my website like a charm).
 2. This solution has the same changes in the snippet and the Ads are still working. 
https://react-adsense.xmplaylist.com/

So my issues should be related to Preact CLI. I cant figure out why exatly yet, because I prerender al my pages (using the json file) and running the preact build should automatically use that json to prerender als these pages right?

@developit @prateekbh

**Comment by ForsakenHarmony** [comment]
@Yeahjoep have you checked the output directory for the generated html files?

**Comment by Yeahjoep** [comment]
> 
> 
> @Yeahjoep have you checked the output directory for the generated html files?

Hey tyes I did! I've fixed an issue this evening related to this. I had to call the function that sets the dynamic content from the ComponentWillRender() function. Now fingers crossed to see if Google like it now. The output contains the dynamic content now and the Google snippet. Fingers crossed :wink:
