### ISSUE TITLE
Why does --preload default to false?

### ISSUE THREAD

**Issue by dbbk** [preactjs/preact-cli#1367]
Hi there,

Just curious why the default behaviour is not to add the `preload` tags, are there any downsides to doing this?  It's not clear to me from the docs why this is off by default, or under what circumstances it would make sense to opt into it.

**Comment by prateekbh** [comment]
The default behavior is to take advantage of h2 push. and the push manifest generated.
Several plugins can read this manifest and generate headers accordingly
