### ISSUE TITLE
[Feature] Provide a template to create libraries

### ISSUE THREAD

**Issue by thesobercoder** [preactjs/preact-cli#1373]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**If this is a feature request, what is motivation or use case for changing the behaviour?**

The idea behind this feature is to have a consistent way for library authors to scaffold a new library based on preact. Even though it is totally possible for two different library authors to adopt completely different approach and still produce their respective libraries, but having something consistent would help new library authors to focus on the functionality instead of trying to figure out how to setup everything, basically provide the same value that the `default` template provides for application authors.

**Comment by RyanChristian4427** [comment]
While it's a little rough and probably needs a few PRs, that's essentially what the [Widget template](https://github.com/preactjs-templates/widget) is for. The `dist` command will bundle it into something that can be used as a library in other Preact apps.

**Comment by prateekbh** [comment]
its broken with 3.0 will need some work to enable it again

**Comment by RyanChristian4427** [comment]
I can look into giving it a bit of help later, to get it up-to-date.

**Comment by RyanChristian4427** [comment]
@thesobercoder I have created [a PR that gets the template back up-to-date](https://github.com/preactjs-templates/widget/pull/14). Check it out if you have a few minutes. Let me know if you notice any issues with it.

Hopefully this was the sort of thing you were looking for.
