### ISSUE TITLE
Error with typecheckings in typescript template

### ISSUE THREAD

**Issue by pukarsharma112** [preactjs/preact-cli#1376]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behaviour?**
_Error with types checking in typescript template_

**If the current behaviour is a bug, please provide the steps to reproduce.**
`const name:string = 1;` should show error but it is compiling properly.

**What is the expected behaviour?**
_Should show typescript error._

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

Environment Info:
  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.E
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.125
  npmPackages:
    preact: ^10.3.1 => 10.4.7
    preact-cli: ^3.0.0 => 3.0.1
    preact-render-to-string: ^5.1.4 => 5.1.10
    preact-router: ^3.2.1 => 3.2.1

**Comment by RyanChristian4427** [comment]
When you say "it is compiling properly." do you mean that `preact watch` won't throw any errors?

This is intentional. The full type checking only runs when you use `preact build`. It's not as quick, so it's restricted for production building.

**Comment by pukarsharma112** [comment]
I understand but does this means all the typecheckings in development mode are managed by ide or code editor.

**Comment by RyanChristian4427** [comment]
Your console should have an error popup, but yes. TS will not break your entire application in dev if there are type issues. It will try to continue through the type checking issues as best as it can.

**Comment by pukarsharma112** [comment]
Thank you for helping. BTW I'm really loving both preact and preact-cli
