### ISSUE TITLE
__webpack_public_pack__ setting is not effective

### ISSUE THREAD

**Issue by Edorka** [preactjs/preact-cli#1379]
Maybe a bug:

I'm working on a transform too to turn a `build` result into a wordpress theme to easily produce SPAs with Preact (https://github.com/Edorka/preact-cli-wp-theme). 

Everything works great till code-split gets in our way: The tool set `window.resourceBaseUrl` with a value from PHP, then in `src/index.js` I have added this to the very first line:

```
if (typeof window !== "undefined") { 
    window.__webpack_public_path__ = window.resourceBasePath;
    console.log('webpack set to ', window.__webpack_public_path__);
}
```
after runing `yarn build` and running my script the new code still try to load from the old path `http://snp.local/route-category.chunk.d5d82.esm.js 404 (Not Found)` while the correct one is `http://snp.local/wp-content/themes/snp/route-category.chunk.d5d82.esm.js` . However, I'm still getting the console.log: `webpack set to  /wp-content/themes/snp`
**Do you want to request a _feature_ or report a _bug_?**

If this can't be fixed is there any comman-line option just to disable code splitting? this would be very helpful to add to the instructions

**If the current behaviour is a bug, please provide the steps to reproduce.**

Please paste the results of `preact info` here.
```
$ ./node_modules/.bin/preact info

Environment Info:
  System:
    OS: Linux 5.4 elementary OS 5.1.6 Hera
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 12.18.3 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
  npmPackages:
    preact: ^10.3.2 => 10.4.7 
    preact-cli: ^3.0.0 => 3.0.1 
    preact-render-to-string: ^5.1.4 => 5.1.10 
    preact-router: ^3.2.1 => 3.2.1 
```

**Comment by RyanChristian4427** [comment]
To customize the Webpack configuration you'll need to use the `preact.config.js`. Creating a plugin might be the way you want to do this. [Plugin Wiki](https://github.com/preactjs/preact-cli/wiki/Plugins). It has a few examples with it. 

You can set the public path with something like the following:

```
export default (config, env, helpers) => {
  config.output.publicPath = '/wp-content/themes/snp/';
  return config;
};
```

I don't believe your problem is code splitting, rather that, by default, `preact build` prerenders your initial route (`/`) into `index.html`. Code splitting or no your scripts won't be found, but prerendering the route gets around this somewhat.

If you want to disable code splitting you can move your files out of `/routes`. Other popular options would be `/pages` and `/views`.

**Comment by Edorka** [comment]
Problem is that config can't be updated on runtime and the route can only be provisioned from the PHP.

Certainly your solution, however it requires asking/guessing, the theme's name it will shorten sensitively the code required for this feature.

**Comment by RyanChristian4427** [comment]
Could your tool say set an environment variable that a plugin will then use to set Webpack public path?

It's certainly a bit more to ask your users to do, adding a plugin to their dependencies and then adding it to their `preact.config.js` but I don't believe this CLI offers any other real way to play with the Webpack config.

**Comment by Edorka** [comment]
No worries, the solution you provided works even with code splitting. I will update my plugin to do a build but setting that config and doing some minor tasks.
Thanks for the suggestion and the help :+1:
