### ISSUE TITLE
how build to mpa

### ISSUE THREAD

**Issue by dhzou** [preactjs/preact-cli#1391]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behaviour?**

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

**Comment by RyanChristian4427** [comment]
Can you please fill out the sections in this template?

What sort of behavior are you looking to achieve? Preact-CLI will prerender routes, if that's the behavior you're looking for. You can find information on prerendering [here](https://github.com/preactjs/preact-cli#pre-rendering) and [here](https://github.com/preactjs/preact-cli#prerender-multiple-routes)
