### ISSUE TITLE
CLI takes "sideEffects" field of package into account while building application

### ISSUE THREAD

**Issue by rschristian** [preactjs/preact-cli#1411]
**Do you want to request a _feature_ or report a _bug_?**

This is a bug

**What is the current behaviour?**

Currently the CSS loader does not override the `"sideEffects"` field of a package. This is an issue as CSS imports in the form of `import './style.css';` have side effects by their very nature. They should not be affected as that style of import should either causes a side effect or just doesn't work.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Set the `"sideEffects"` field to `false` in a package file, import non-moduled CSS (`import './style.css';`), then run a production build. The CLI will ignore that import entirely.

**What is the expected behaviour?**

The CSS should be included.  

**Please mention other relevant information.**

```
Environment Info:
  System:
    OS: Linux 5.7 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.9.0 - /tmp/yarn--1599859321698-0.6191202931910675/node
    Yarn: 1.22.5 - /tmp/yarn--1599859321698-0.6191202931910675/yarn
    npm: 6.14.8 - ~/.npm-global/bin/npm
  Browsers:
    Firefox: 80.0.1
  npmPackages:
    preact: ^10.4.7 => 10.4.7 
    preact-cli: ^3.0.1 => 3.0.1 
    preact-render-to-string: ^5.1.9 => 5.1.
```

**Comment by RyanChristian4427** [comment]
Finally dawned on me, `"sideEffects": false` in the pkg.json caused this. 

Having that field (with that value) will stop any CSS from being processed apparently. That would make sense for building a library, but I do think that's odd behavior for an application bundler setup, but maybe I'm not thinking of a scenario where that's useful.
