### ISSUE TITLE
Cannot Read 'filter' of undefined in `preact-cli-plugin-flow`

### ISSUE THREAD

**Issue by ajay28kumar** [preactjs/preact-cli#1422]
Yes
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behaviour?**
on running the `npm run dev` locally I'm getting following error in `preact-cli-plugin-flow`:-
```
✖ ERROR Error: TypeError: Cannot read property 'filter' of undefined
```
**If the current behaviour is a bug, please provide the steps to reproduce.**
I'm trying to upgrade my preactJS and preact-cli in my existing code base:-
My previous version of:-
```
preact: "10.0.5",
preact-cli: "2.2.1",
```

After Running npm run dev I'm getting an error saying: `Cannot read property 'filter' of undefined`

**What is the expected behaviour?**
It should be working perfecly
**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
Error Response:-
![Screenshot 2020-09-14 at 12 25 40 PM](https://user-images.githubusercontent.com/16662534/93054019-51fff180-f686-11ea-94f9-70bf768ef51d.png)

My preact.config.js:-

![Screenshot 2020-09-14 at 12 33 00 PM](https://user-images.githubusercontent.com/16662534/93054081-6e9c2980-f686-11ea-9e2f-0c4adbf97fff.png)

Error coming from `preact-cli-plugin-flow/src/index.js`

![Screenshot 2020-09-14 at 12 34 21 PM](https://user-images.githubusercontent.com/16662534/93054194-9f7c5e80-f686-11ea-80e0-7eea9c4d3f60.png)

Please paste the results of `preact info` here.
![Screenshot 2020-09-14 at 10 59 25 AM](https://user-images.githubusercontent.com/16662534/93053980-46142f80-f686-11ea-9046-6148c03077a5.png)

**Comment by RyanChristian4427** [comment]
So there's better ways of doing that, but firstly, [`config.module.loaders` doesn't exist anymore](https://github.com/preactjs/preact-cli/blob/172e9ecb8f2db33f19e137d24e6eaea0baa8a405/packages/cli/lib/lib/webpack/webpack-base-config.js#L157), which is your problem.

But before you change `loaders` -> `rules`, check out the [config recipes](https://github.com/preactjs/preact-cli/wiki/Config-Recipes) to see if we don't have something that works better for you, like ` helpers.getLoadersByName(config, 'babel-loader')[0];`. There's a few helpers in there to try to make it easier for you to target the certain areas you want to change. 

On an unrelated note, you should be able to remove those aliases in your config. [Preact CLI ships with React aliases already](https://github.com/preactjs/preact-cli/blob/172e9ecb8f2db33f19e137d24e6eaea0baa8a405/packages/cli/lib/lib/webpack/webpack-base-config.js#L133). I don't think your setup will hurt, but it is unnecessary.
