### ISSUE TITLE
typescript template broken by default: Types of property 'parent' are incompatible

### ISSUE THREAD

**Issue by peterbe** [preactjs/preact-cli#1425]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
```
▶ npx preact-cli create typescript demo-chunkloaderror --yarn
▶ cd demo-chunkloaderror
▶ yarn run build
yarn run v1.22.4
$ preact build
 Build  [=================== ] 93% (1.5s) after chunk asset optimization
 ssr-bundle.ac348.css ⏤  0 B (-602 B)
        ssr-bundle.js ⏤  4.21 kB
 ssr-bundle.f9224.css ⏤  601 B (+601 B)

✖ ERROR ./node_modules/@types/node/ts3.1/globals.d.ts
ERROR in ./node_modules/@types/node/ts3.1/globals.d.ts(573,15):
TS2430: Interface 'NodeJS.Module' incorrectly extends interface '__WebpackModuleApi.Module'.
  Types of property 'parent' are incompatible.
    Type 'Module | null | undefined' is not assignable to type 'NodeModule | null'.
      Type 'undefined' is not assignable to type 'NodeModule | null'.
error Command failed with exit code 1.

```

**If the current behaviour is a bug, please provide the steps to reproduce.**

I hope the steps above are clear enough

**What is the expected behaviour?**

That it builds the `./build/` folder. 

**Please mention other relevant information.**

```
▶ npx preact-cli info

Environment Info:
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /opt/boxen/homebrew/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 13.1.2
  npmPackages:
    preact: ^10.3.1 => 10.4.8
    preact-cli: ^3.0.0 => 3.0.1
    preact-render-to-string: ^5.1.4 => 5.1.10
    preact-router: ^3.2.1 => 3.2.1

```

**Comment by kidqueb** [comment]
I believe this is an issue with `@types/node` documented [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47516)

Try running `yarn upgrade @types/node&14.6.4` to see if it cleans that up.

**Comment by RyanChristian4427** [comment]
If that somehow doesn't fix it try removing your lock file & `node_modules` and then reinstall. I believe I had to do that the other day for a quick demo and it worked just fine.

**Comment by peterbe** [comment]
> `yarn upgrade @types/node&14.6.4`

It does. But since it's not a direct dependency, I forced the upgrade with `yarn add --dev @types/node@14.6.4` and if you do that it upgrades and solves the problem. 

Now, what do we need to do to prevent this? The output of `yarn why @types/node` is pretty intense after all :)

**Comment by rschristian** [comment]
Closing this out, should be long since fixed upstream.
