### ISSUE TITLE
flow type support in preact-cli

### ISSUE THREAD

**Issue by ajay28kumar** [preactjs/preact-cli#1433]
**Do you want to request a _feature_ or report a _bug_?**
feature
**What is the current behaviour?**

the previous version of preact-cli had the support of `.flow` but in updated preact-cli version removed the support.In current version `config.module.loaders` doesn't exist anymore and `preact-cli-plugin-flow` is not updated anymore.

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**
It's always good to know about the type of data that's passing as `props` and `state` and it's always great for a new person to understand the project in case of type.

**Please mention other relevant information.**

Please paste the results of `preact info` here.

```
Environment Info:
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 13.0.4
  npmPackages:
    preact: ^10.4.8 => 10.4.8 
    preact-cli: ^3.0.0 => 3.0.1 
    preact-router: ^3.2.1 => 3.2.1 
  npmGlobalPackages:
    preact-cli: 3.0.1
```

**Comment by rschristian** [comment]
I suggested a solution back in #1422.

The CLI updating didn't remove support for Flow, it just broke an old and unmaintained plugin.

You can update the config from the plugin and move it into your own `preact.config.js` or you could fork the plugin, make the necessary updates, and then use that.

**Comment by ajay28kumar** [comment]
Hey @rschristian ,
Thanks for updating but can you provide me any code snippet because I've tried working with [webpack-base-config](https://github.com/preactjs/preact-cli/blob/172e9ecb8f2db33f19e137d24e6eaea0baa8a405/packages/cli/lib/lib/webpack/webpack-base-config.js#L157) and it's still throwing error. My code snippet of `preact.config.js` is:

```
import envVars from 'preact-cli-plugin-env-vars';
const WorkboxPlugin = require('workbox-webpack-plugin');
const preactCliFlow = require('preact-cli-plugin-flow');
const webpackBaseConfig = require('preact-cli/lib/lib/webpack/webpack-base-config')

export default (config, env, helpers) => {
    process.env.PREACT_APP_ENV_NAME = process.env.PREACT_APP_ENV_NAME ? process.env.PREACT_APP_ENV_NAME : 'dev';
    envVars(config, env, helpers);
    config.output.publicPath = process.env.PREACT_APP_BASE_PATH;
    console.log('Environment : ' + process.env.PREACT_APP_ENV_NAME);
    console.log('Public path : ' + process.env.PREACT_APP_BASE_PATH);


    config.plugins.push(
        new WorkboxPlugin.InjectManifest({
            swSrc: './service-worker.js',
            swDest: './service-worker.js',
            include: [/\.png$/, /\.ico$/],
        })
    );
    config.resolve.alias = Object.assign({}, config.resolve.alias, {
        react: 'preact/compat',
        'react-dom': 'preact/compat'
    });
    const webpackEnv = webpackBaseConfig(env);
    config.module.loaders = webpackEnv.module.rules

    return preactCliFlow(config);
};
```

It's throwing error 

![Screenshot 2020-09-22 at 3 20 15 PM](https://user-images.githubusercontent.com/16662534/93867755-206ed200-fce7-11ea-98be-bfee6830f738.png)

**Comment by rschristian** [comment]
There's no reason to import the config. `preact.config.js` is an escape hatch to override that config. You shouldn't be actually trying to use it yourself.

**Comment by rschristian** [comment]
Something like the following should replace the config

```
const babelLoader = helpers.getLoadersByName(config, 'babel-loader')[0];
babelLoader.options.plugins.push(flowStripTypes);
```

You'll still need to handle the flow stuff yourself, like the babel plugin, the flow binary, etc.

**Comment by rschristian** [comment]
Closing as should be answered. Let me know if you have any further questions.
