### ISSUE TITLE
 Add --no-sourcemaps build option

### ISSUE THREAD

**Issue by RonnyLV** [preactjs/preact-cli#1476]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behaviour?**
Production build generates sourcemaps

**What is the expected behaviour?**
Providing `--no-sourcemaps` option would result in build without sourcemaps

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Minimalistic production build bundle

**Comment by rschristian** [comment]
Not quite a CLI flag but you can disable sourcemaps through your `preact.config.js`

https://github.com/preactjs/preact-cli/issues/549#issuecomment-380335605

I believe this should still work.

**Comment by RonnyLV** [comment]
Thanks, it worked out

**Comment by rschristian** [comment]
Can this be closed then?
