### ISSUE TITLE
`sw-debug.js` is included in build output when building with option `--no-sw`

### ISSUE THREAD

**Issue by RonnyLV** [preactjs/preact-cli#1477]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
`sw-debug.js` is included in build output when building with option `--no-sw`

**If the current behaviour is a bug, please provide the steps to reproduce.**
![image](https://user-images.githubusercontent.com/3844817/100713755-733ac900-33bd-11eb-9a1e-d1349b11eb5b.png)

**What is the expected behaviour?**
No `sw-debug.js` in build output with `--no-sw` enabled

```
Environment Info:
  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    preact: ^10.3.1 => 10.5.7 
    preact-cli: 3.0.3 => 3.0.3 
    preact-render-to-string: ^5.1.4 => 5.1.12 
  npmGlobalPackages:
    preact-cli: 3.0.3
```

**Comment by rschristian** [comment]
The SW will be copied to the output directory but won't be registered.

We can probably exclude it but there would be no change in functionality.
