### ISSUE TITLE
Preact-cli takes at least 3 seconds to respond

### ISSUE THREAD

**Issue by DenizBasgoren** [preactjs/preact-cli#1488]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
`preact -h` takes 3-5 seconds to respond. Others (watch, build) take just about the same time.

**If the current behaviour is a bug, please provide the steps to reproduce.**
I think it's easy to reproduce. I'm using node via nvm, and have installed preact-cli globally (`npm i -g preact-cli`). Behavior is same regardless of whether cli is installed globally or not. issues with nvm are irrelevant.

**What is the expected behaviour?**
Should respond immediately, about as fast as `node -v`.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
```
System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    npm: 6.14.9 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Browsers:
    Firefox: 83.0
  npmGlobalPackages:
    preact-cli: 3.0.4

```

**Comment by rschristian** [comment]
As mentioned in your previous issue (#1483), `nvm` very well could be your issue. It has had historical difficulty not just with slowing down node related applications but slowing entire terminal environments. It's certainly worth taking a look at.

Secondly, `node -v` is executing a binary. There's a huge difference between a binary and a script that needs to pass through an interpreter which then links to even more scripts. Node is C/++ and sprinklings of JS, Preact-CLI is just JS. There's a reason why the former are kings when you need performance.

Thirdly, you're running an 8 year old dual core mobile processor. 3 second start up times seems about what I'd expect given the circumstances.

I'd try switching away from `nvm`, see if you can get any sort of speed up there. Unless this is a regression from another version that you've experienced I don't believe this is a bug. I've just manually tested the past 4 versions to check and I'm consistently seeing sub 2 seconds on my personal device. I can certainly test older if you think this tool used to be faster.

**Comment by DenizBasgoren** [comment]
Tested running
`preact watch` and
`~/.nvm/versions/node/v14.7.0/lib/node_modules/preact-cli/lib/index.js watch`
both print the first message in 3 seconds after running the command. So it's not an issue with nvm. Will test `create-react-app` and alikes to see if their performance is comparable.

**Comment by DenizBasgoren** [comment]
I did some profiling and it turns out this project spends the 3 seconds `require`ing webpack related files. They are required no matter what the cli arguments are. For example if I just type `./index.js` without parameters, it takes 3 seconds to print `ERROR No command specified.` While not a bug, this could be improved by first parsing the cli and then `require`ing packages as needed. This would make people get the `--help` messages faster.

Besides that, `create-react-app` runs a bit slower, so I think these are the limits of my hardware. There also seems to be an issue with nvm, but that's offtopic here, so I'll close this issue.

**Comment by rschristian** [comment]
> While not a bug, this could be improved by first parsing the cli and then `require`ing packages as needed. This would make people get the `--help` messages faster.

This is just how Node works, you're welcome to take a look at the source. Most of the dependencies wouldn't be `required()` at all if you walked from entry point to help command. That's all top-level in the lib. Webpack stuff comes lower. Dynamically importing every dependency might work but would be a mess, more than likely.
