### ISSUE TITLE
--no-prerender is considered invalid argument in 3.0.4

### ISSUE THREAD

**Issue by smjnab** [preactjs/preact-cli#1489]
**Do you want to request a _feature_ or report a _bug_?**
Bug, appeared with 3.0.4 release and the addition of validating arguments.

**What is the current behaviour?**
When running "preact build --no-prerender" it fails with "ERROR Invalid argument prerender passed to build."

**If the current behaviour is a bug, please provide the steps to reproduce.**
Run preact build --no-prerender

**Please mention other relevant information.**

Please paste the results of `preact info` here.
Environment Info:
  System:
    OS: Linux 5.9 KDE neon 5.19
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 12.20.0 - /usr/bin/node
    npm: 6.14.9 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 83.0
  npmPackages:
    preact: ^10.5.7 => 10.5.7 
    preact-cli: ^3.0.4 => 3.0.4 
    preact-render-to-string: ^5.1.12 => 5.1.12 
  npmGlobalPackages:
    preact-cli: 3.0.4

**Comment by craftedsystems** [comment]
Pre-render tells `Alternatively use 'preact build --no-prerender' to disable prerendering.` as possible solution.
And fails when using it with `Invalid argument prerender passed to build.`.

**Comment by craftedsystems** [comment]
Temporary solution: use preact-cli@3.0.3 :-)

**Comment by rschristian** [comment]
Sorry about that, PR has been written to fix this
