### ISSUE TITLE
Build creates 200.html with `--no-prerender` option

### ISSUE THREAD

**Issue by marzepani** [preactjs/preact-cli#1495]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
`preact build --no-prerender` creates a `200.html` file.

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
The file should not be created, as in v3.0.3.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
```
Environment Info:
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 15.3.0 - ~/.n/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.14 - ~/.n/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Edge: 87.0.664.57
    Firefox: 83.0
    Safari: 14.0.1
  npmPackages:
    preact: ^10.5.7 => 10.5.7
    preact-cli: ^3.0.5 => 3.0.5
```

**Comment by prateekbh** [comment]
That is just a fallback file used for service worker. and has nothing to do with pre-rendering. However with no pre-rendering we can fallback to `index.html` as well.

Is this file being created a problem of any sort @marzepani

**Comment by marzepani** [comment]
Thx @prateekbh. I prefer to get just the files I need, and currently, there are some other unused files.

build options:
`preact build --no-sw --no-json --no-inline-css --no-prerender`

questionable files:
* 200.html (like mentioned)
* preact_prerender_data.json (unused, in my case)
* push-manifest.json (unused, in my case)

It is not a big deal to ignore some files, but I might wonder later. :-)

**Comment by rschristian** [comment]
I can look at getting those removed, though the push manifest I believe you'll have to prune yourself (maybe add as an after build action, i.e., `preact build ... && rm build/push-manifest.json`). There's no way of knowing at build time whether or not you/your web server could make use of it.

@prateekbh Just so I'm clear, as I didn't totally understand from your PR's explanation (totally out of the loop on SW stuff), this is something that doesn't need to exist when `--no-sw` is used, correct?
