### ISSUE TITLE
Question: NODE_ENV is still "development" during build

### ISSUE THREAD

**Issue by dextermb** [preactjs/preact-cli#1497]
**Do you want to request a _feature_ or report a _bug_?**

Question/Potential bug

**What is the current behaviour?**

When running `preact build` the `process.env.NODE_ENV` variable is `development.

**What is the expected behaviour?**

From what I understand `preact build` builds for production, so with plugins and other things checking `process.env.NODE_ENV` for `production` it should be set accordingly.

**Please mention other relevant information.**

I'm trying to give `preact` a go after looking for lighter options than React. I'm attempting to set up a `tailwindcss` configuration with a purge config:

```js
module.exports = {
  purge: [
    './src/**/**.jsx'
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {}
  },
  variants: {
    extend: {}
  },
  plugins: []
}
```

But it did not seem like purge was being called when viewing the bundle sizes, so I tried checking the `NODE_ENV`:

```js
console.log(process.env.NODE_ENV)

module.exports = {
  purge: {
    enabled: process.env.NODE_ENV !== 'development',
    content: [
      './src/**/**.jsx'
    ]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {}
  },
  variants: {
    extend: {}
  },
  plugins: []
}
```

And during `preact build` I was getting `development` logged out rather than `production` which meant purge was not triggered.

---

How can I use `NODE_ENV` to check for production builds?

**Comment by rschristian** [comment]
You can set it yourself if you need it:

```
"build": "NODE_ENV=production preact build"
```

If you're using a `preact.config.js` you can use `env.production` to check the current environment. [Example from the wiki](https://github.com/preactjs/preact-cli/wiki/Config-Recipes#conditional-changes-based-on-env)

**Comment by dextermb** [comment]
@rschristian Thanks for pointing me towards the wiki. I'd of expected it to be default behaviour, to set the `NODE_ENV`, if `preact` has it's own internal env state.

I've resolved my issue by adding the following to my `preact.config.js`:

```js
module.exports = (config, env, helpers) => {
  if (env.production) {
    process.env.NODE_ENV = 'production'
  }

  // ...
}
```

This seems to work as expected, during `yarn run build` `NODE_ENV` comes back as `production`.
