### ISSUE TITLE
React to Preact codemod

### ISSUE THREAD

**Issue by sumanthratna** [preactjs/preact-cli#1521]
# Feature Request

I see that the Preact team has written useful codemods for Preact before: https://github.com/preactjs/migrate-preact-x

I think there should be an official codemod for converting from React to Preact. The codemod should support this:
- JSX/Create React App setups
- TypeScript

e.g., if I wanted to convert a TSX codebase to Preact, I would run `preact codemod from-tsx`

# Motivation

reduce the react -> preact conversion friction, which has been preventing me from making the switch (converting seems like a task that can generally be automated)

# Other Relevant Information
n/a

**Comment by rschristian** [comment]
In most basic situations, this is as simple as setting up an alias in your bundler of choice. We have some documentation for that here: https://preactjs.com/guide/v10/getting-started#integrating-into-an-existing-pipeline

As you're posting this in the Preact-CLI repof, are you asking for a CRA -> Preact-CLI conversion? Because that'd be impossible to maintain I think. Too much going on there, and it'd be a moving target.

**Comment by sumanthratna** [comment]
thanks for the reply @rschristian! 

> In most basic situations, this is as simple as setting up an alias in your bundler of choice. We have some documentation for that here: https://preactjs.com/guide/v10/getting-started#integrating-into-an-existing-pipeline

I saw that, but it didn't address my needs, since I'm coming from CRA

> As you're posting this in the Preact-CLI repof, are you asking for a CRA -> Preact-CLI conversion? Because that'd be impossible to maintain I think. Too much going on there, and it'd be a moving target.

Yup, this feature request is mostly inspired by CRA -> Preact-CLI. Can you explain why it would be hard to maintain? As far as I can tell (with no knowledge of Preact-CLI's internals), the process would look something like this:
1. user ejects from CRA, leaving them with a Webpack setup
2. user runs codemod, which updates imports and Webpack config

I'm guessing you're referring to the Webpack config has hard to keep up with—is that correct?

**Comment by rschristian** [comment]
CRA is an extremely opinionated Webpack configuration. This means it is quite highly customized.

To customize Preact-CLI, a user creates a `preact.config.js` file and uses that to programmatically change the configuration that's ran. To do a CRA -> Preact-CLI means we need to generate code that would fix every difference between CRA's config and Preact-CLIs. Not to mention with Preact-CLI's prerendering, things get even more complicated in terms of what plugins need to be ran when to ensure that your application is built correctly.

The task is to copy [this](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js) correctly into [this](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/webpack/webpack-base-config.js), [this](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/webpack/webpack-client-config.js), and [this](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/webpack/webpack-server-config.js).

I think to refer to this as updating a Webpack config is really underselling the task here. Dozens of plugins with incompatibilities and a different build process in general. 

You're better off copying your `src/` directory into a new Preact-CLI app.

**Comment by sumanthratna** [comment]
I see; thanks for the explanation. I agree that this seems unmaintainable so I'll close this issue

**Comment by rschristian** [comment]
I'd certainly enjoy a tool that allowed for a quick switch, but I think the idea of a merged or migrated config is just too much to really hope for. 

Something that just quickly changed up the imports and swapped out the packages like you mentioned would be great, though it would have to come with the huge caveat of "this has a decent chance of not working right out of the box".
