### ISSUE TITLE
How can I polyfill things on top of preact-cli, like Object.entries for Ie11?

### ISSUE THREAD

**Issue by wahidshafique** [preactjs/preact-cli#1524]
**Do you want to request a _feature_ or report a _bug_?**
Bug?

**What is the current behaviour?**
Running my website on IE11, I get the following error

```
 Object doesn't support property or method 'entries'
```

**What is the expected behaviour?**
I thought preact had support for this (unless I misconfigured something). How can I extend the traspilation step?

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Having an simple escape hatch to support older browsers (or other platforms) would be nice.

```
Environment Info:
  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  Binaries:
    Node: 12.16.1 - /var/folders/rh/4gfj4k6x6t7c422x0q2rk_200000gn/T/yarn--1612194347531-0.7164875915010767/node
    Yarn: 1.22.4 - /var/folders/rh/4gfj4k6x6t7c422x0q2rk_200000gn/T/yarn--1612194347531-0.7164875915010767/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 77.0.1
    Safari: 14.0.1
  npmPackages:
    preact: 10.5.12 => 10.5.11 
    preact-cli: ^3.0.5 => 3.0.5 
    preact-router: ^3.2.1 => 3.2.1
```

**Comment by rschristian** [comment]
You'll need to bring your own polyfill as far as I'm aware. Then just use it in a script tag in your template.

**Comment by wahidshafique** [comment]
@rschristian Ah yes, I decided to just include it in the template, something like this 

```
 <body>
    <script type="text/javascript">
      if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent))
        document.write(
          '<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.8.3/polyfill.min.js"><\/script>'
        );
    </script>
    <% preact.bodyEnd %>
  </body>
```

**Comment by rschristian** [comment]
Glad you got this working. Certainly let me know if you're having any further issues.
