### ISSUE TITLE
A way to remove missing dependencies warning?

### ISSUE THREAD

**Issue by heymartinadams** [preactjs/preact-cli#1525]
### Reproduction

1. Install **Preact** and **React** like so:

#### package.json
```json
	"preact": "^10.5.9",
	"preact-render-to-string": "^5.1.12",
	"react": "npm:@preact/compat",
	"react-dom": "npm:@preact/compat",
```

2. Install other npm modules that use `react` as their dependency
3. Run

### Expected Behavior

Doing `yarn` (e.g. `yarn install [package]`) should not provide us with a list of warnings about missing React dependencies.

### Actual Behavior

Instead, because we have a fairly large codebase, we’re getting **91 lines** of warning messages.
![image](https://user-images.githubusercontent.com/11673745/106822750-7f007100-6634-11eb-90f0-2d03361943b3.png)

I tried something like this (inside package.json), but that didn’t work either.
```json
	"peerDependencies": {
		"react": "^17.0.0"
	},
```

Looked to yarn documentation, but couldn’t find a solution. Anything you might know that could be helpful?

**Comment by heymartinadams** [comment]
No, this is for our preact-based web app... what you’re suggesting is that we simply use this in our package.json?

```json
	"preact": "^10.5.9",
	"preact-render-to-string": "^5.1.12",
	"react": "npm:@preact/compat",
	"react-dom": "npm:@preact/compat",
```

instead of this?

```json
	"preact": "^10.5.9",
	"preact-render-to-string": "^5.1.12",
	"react": "^17.0.1",
	"react-dom": "^17.0.1",
```

**Comment by JoviDeCroock** [comment]
It depends on what you're trying to do I guess, if this is for SSR, you'll need the latter if it's purely CSR the former will suffice with a webpack alias. You can probably silence the warning with a `--quiet` flag. Essentially it's just the package seeing a different name property in the pkg.json and warning you.

**Comment by heymartinadams** [comment]
Thank you, @JoviDeCroock. One more question, sorry to bother: how would I create a webpack alias for this? We’re using NextJS and have integrated this example (using `next-plugin-preact`): https://github.com/developit/nextjs-preact-demo

**Comment by JoviDeCroock** [comment]
Next.JS relies on SSR which means you need the latter, `next-plugin-preact` does the webpack alias for you. The problem is that the webpack-alias will make it so that the client-side bundle uses Preact, this however sadly doesn't make it so that the Node bundle uses Preact, for the Node bundle we use these manual pkg.json aliases.

**Comment by rschristian** [comment]
The Preact slack is another alternative if that is any easier: https://chat.preactjs.com/
