### ISSUE TITLE
open page with flash

### ISSUE THREAD

**Issue by panfeng-fe** [preactjs/preact-cli#1528]

**Comment by rschristian** [comment]
Can you provide a minimal reproduction or source code by any chance? Debugging your production environment will be more difficult.

**Comment by rschristian** [comment]
There's a decent chance you're asynchronously loading your router. Make sure your router isn't within `routes/` or being async loaded in any other way.

**Comment by panfeng-fe** [comment]
![image](https://user-images.githubusercontent.com/74502037/106982599-5b0d6e80-679f-11eb-9c4a-25523980a1b4.png)

// this is start up scripts

![image](https://user-images.githubusercontent.com/74502037/106982567-4df07f80-679f-11eb-9bf2-97a7704070a0.png)
// this is Router

![image](https://user-images.githubusercontent.com/74502037/106982669-7b3d2d80-679f-11eb-8d32-43106d0dbf5a.png)
// this is pages

**Comment by panfeng-fe** [comment]
project use preact-cli,Nothing else changed

**Comment by panfeng-fe** [comment]
source code Inconvenient to display， I try to write a demo for debugging

**Comment by panfeng-fe** [comment]
repo: git@github.com:panfeng-fe/flash_demo.git
After you build, start the local http-server, you will find this
![Uploading image.png…]()

**Comment by panfeng-fe** [comment]
![image](https://user-images.githubusercontent.com/74502037/106986801-184f9480-67a7-11eb-9836-08e98d6d2f63.png)

**Comment by rschristian** [comment]
I can't reproduce.

Your provided lock files that were for a private repo though, so I had to remove them and install from NPM. I'm guessing your issue is in one of those.

**Comment by panfeng-fe** [comment]
'git@github.com:panfeng-fe/flash_demo.git'

**Comment by rschristian** [comment]
I was able to clone the repo just fine. I just can't reproduce the actual issue.

**Comment by panfeng-fe** [comment]
![image](https://user-images.githubusercontent.com/74502037/106994156-32916e80-67b7-11eb-83e8-b6dc0f8fb832.png)
myproject  
![image](https://user-images.githubusercontent.com/74502037/106994226-55238780-67b7-11eb-91c7-36c0b5c8fea7.png)
preact-www(preact Official website）
so, I think What caused it render twice，

**Comment by panfeng-fe** [comment]
![image](https://user-images.githubusercontent.com/74502037/106994464-c9f6c180-67b7-11eb-8f4a-b95b99130342.png)
this package can delete

**Comment by panfeng-fe** [comment]
I have deleted the private package    ‘git@github.com:panfeng-fe/flash_demo.git’

**Comment by panfeng-fe** [comment]
The trigger is the static file after the build， not dev， dev is ok

**Comment by rschristian** [comment]
All your lock files still point to a private repository. `"http://registry.npm.baidu-int.com/@babel%2fcode-frame/-/code-frame-7.10.4.tgz#168da1a36e90da68ae8d49c0f1b48c7c6249213a"` is not a public URL. 

I can't seem to get this to flash on Firefox, and this is way too much for me to try to debug. Need a minimal reproducible example.

**Comment by panfeng-fe** [comment]
I have packed ， Please check the build folder    ‘git@github.com:panfeng-fe/flash_demo.git’
