### ISSUE TITLE
TypeScript version is old ^3.4.5

### ISSUE THREAD

**Issue by osdiab** [preactjs/preact-cli#1529]
**Do you want to request a _feature_ or report a _bug_?**
Feature? But feels like a bug to me

**What is the current behaviour?**
can't use the latest version of typescript, which is suggested in the preact docs themselves, because `preact-cli` specifies an old typescript version of `^3.4.5`

**If the current behaviour is a bug, please provide the steps to reproduce.**

- `yarn add preact-cli typescript`
- Put `"jsxImportSource": "preact"` as the preact docs tell you to for TypeScript support with modern typescript
- try to compile with `tsc`, you get an error: `Unknown compiler option 'jsxFragmentFactory'.`
- can't follow the docs on Preact!

**What is the expected behaviour?**

It works and uses the newer version of typescript

**If this is a feature request, what is motivation or use case for changing the behaviour?**

I want to use modern features

**Please mention other relevant information.**

```
Environment Info:
  System:
    OS: macOS 11.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 14.3.0 - /var/folders/ct/hs211d3n09nb3d6nkmv7j7g80000gn/T/yarn--1612505637634-0.13322901752400163/node
    Yarn: 1.22.5 - /var/folders/ct/hs211d3n09nb3d6nkmv7j7g80000gn/T/yarn--1612505637634-0.13322901752400163/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.146
    Firefox: 80.0.1
    Safari: 14.0.3
```

**Comment by rschristian** [comment]
If you're using `preact-cli` you shouldn't be compiling with `tsc`. 

Here's a demo app: https://github.com/rschristian/preact-cli-ts-demo

Runs TS 4.1.3 and uses `"jsx": "react-jsx"` + `"jsxImportSource": "preact"`. It builds correctly.
```

**Comment by rschristian** [comment]
I'm not even sure how you come across that. Are you trying to run the TS dep that gets installed with Preact-CLI rather than installing TS as a dependency of your project?

**Comment by osdiab** [comment]
Ah yeah, I wanted to see what the errors in my project were so I ran `tsc` directly. Guess it's a surprise to me that the actual typescript command doesn't work if you install `preact-cli`.

**Comment by rschristian** [comment]
It definitely should work. Are you sure you actually installed TS as a dependency? If you did, there's some weird resolution going on. 

How are you actually running `tsc`? `yarn tsc`/`npm run tsc`? Both should prioritize your dependency (4.x.x) over the one that exists because the CLI holds it as a dependency. 

Either way it's not really a CLI issue.

**Comment by osdiab** [comment]
my project uses yarn workspaces, so it's like this:

```
package.json
  - packages
    - packageA
      - package.json // this one has typescript@4.1.3 installed
    - packageB
      - package.json // this one has typescript@4.1.3 and preact-cli installed
```

i have no globally installed typescript. Run `yarn tsc` in `packageB` and then it tries to use the version installed by `preact-cli`, and then fails.

**Comment by rschristian** [comment]
Are you hoisting your dependencies up? That's probably the problem. 

Have a repo by any chance I can take a look at?

**Comment by osdiab** [comment]
ah i think i understand it now. here's a simple repro: https://github.com/osdiab/preact-tsc-yarn-workspace-issue

so if you `cd` into either of the packages and run `yarn tsc --version` it shows `3.9.7`; but if you actually make a script in `package.json` that calls `tsc --version` it uses the correct `4.1.3`. Guess this is a quirk with how `yarn` resolves which dependency to use if you call it directly from the command line instead of via a script.

**Comment by osdiab** [comment]
we can close this, but yeah that was confusing.

**Comment by rschristian** [comment]
Yeah, yarna and NPM will both look in `./node_modules/.bin` for executables. In a workspace you need to use that top level TSC, and there's a few ways to do that, mostly using the `yarn workspace ...` commands. The other option is disabling hoisting.

 Glad you have that working.

**Comment by osdiab** [comment]
fyi I upgraded my repo to Yarn 2 (still using `node_modules`) and this started happening again, so I just gave up and ran yarn set resolution `typescript@^3.4.5 4.1.3` to just hard override the old version of TypeScript that `preact-cli` uses, and everything seems to still work.

**Comment by cdog** [comment]
Current `typescript` version is giving trouble with constructors:
```
"version": "4.2.4",
```

Sample code to reproduce:
```ts
new URL(new URL('https://preactjs.com/'));
```

Resulting in:
```
TS2345: Argument of type 'URL' is not assignable to parameter of type 'string'.
```

For some reason typings are not correct. Can be reproduced live in TypeScript Playground: https://www.typescriptlang.org/play

v4.5.4

<img width="1440" alt="Screenshot 2022-02-14 at 16 56 26" src="https://user-images.githubusercontent.com/690647/153899620-005448d9-f021-4831-951d-5078ee69b76d.png">

v4.2.3

<img width="1440" alt="Screenshot 2022-02-14 at 16 56 15" src="https://user-images.githubusercontent.com/690647/153899652-08832a28-2ebf-472d-a6af-6dbe748c27e6.png">

**Comment by rschristian** [comment]
If this can be reproduced in the Typescript playground it's a TS language issue. Not anything we can do about it.

**Comment by cdog** [comment]
> If this can be reproduced in the Typescript playground it's a TS language issue. Not anything we can do about it.

Hi Ryan, thanks for fast reply. Both `preact` and `preact-cli` come with outdated dependencies. Suggestion is to bump to more recent.

preact@10.6.5
```
@types/mocha                 5.2.7     5.2.7    9.1.0  node_modules/@types/mocha              preact
@types/node               14.18.11  14.18.11  17.0.17  node_modules/@types/node               preact
esbuild                    0.12.29   0.12.29  0.14.21  node_modules/esbuild                   preact
eslint                      5.15.1    5.15.1    8.9.0  node_modules/eslint                    preact
eslint-config-prettier      6.15.0    6.15.0    8.3.0  node_modules/eslint-config-prettier    preact
eslint-plugin-react         7.12.4    7.12.4   7.28.0  node_modules/eslint-plugin-react       preact
husky                        4.3.8     4.3.8    7.0.4  node_modules/husky                     preact
lint-staged                 10.5.4    10.5.4   12.3.4  node_modules/lint-staged               preact
microbundle                 0.11.0    0.11.0   0.14.2  node_modules/microbundle               preact
mocha                        8.4.0     8.4.0    9.2.0  node_modules/mocha                     preact
npm-merge-driver-install     1.1.1     1.1.1    3.0.0  node_modules/npm-merge-driver-install  preact
prettier                    1.19.1    1.19.1    2.5.1  node_modules/prettier                  preact
sinon                        9.2.4     9.2.4   13.0.1  node_modules/sinon                     preact
typescript                   4.4.2     4.4.2    4.5.5  node_modules/typescript                preact
```

preact-cli@3.3.5
```
@types/webpack                  4.41.32  4.41.32      5.28.0  node_modules/@types/webpack                  preact-cli
compression-webpack-plugin        6.1.1    6.1.1       9.2.0  node_modules/compression-webpack-plugin      preact-cli
copy-webpack-plugin               6.4.1    6.4.1      10.2.4  node_modules/copy-webpack-plugin             preact-cli
critters-webpack-plugin           2.5.0    2.5.0       3.0.2  node_modules/critters-webpack-plugin         preact-cli
css-loader                        5.2.7    5.2.7       6.6.0  node_modules/css-loader                      preact-cli
fork-ts-checker-webpack-plugin    4.1.6    4.1.6       7.2.1  node_modules/fork-ts-checker-webpack-plugin  preact-cli
get-port                          5.1.1    5.1.1       6.0.0  node_modules/get-port                        preact-cli
html-webpack-plugin               3.2.0    3.2.0       5.5.0  node_modules/html-webpack-plugin             preact-cli
less-loader                       7.3.0    7.3.0      10.2.0  node_modules/less-loader                     preact-cli
loader-utils                      2.0.2    2.0.2       3.2.0  node_modules/loader-utils                    preact-cli
mini-css-extract-plugin           1.6.2    1.6.2       2.5.3  node_modules/mini-css-extract-plugin         preact-cli
minimatch                         3.1.1    3.1.1       4.1.1  node_modules/minimatch                       preact-cli
ora                               5.4.1    5.4.1       6.0.1  node_modules/ora                             preact-cli
p-retry                           4.6.1    4.6.1       5.0.0  node_modules/p-retry                         preact-cli
postcss-loader                    4.3.0    4.3.0       6.2.1  node_modules/postcss-loader                  preact-cli
preact-router                     3.2.1    3.2.1       4.0.1  node_modules/preact-router                   preact-cli
puppeteer                         9.1.1    9.1.1      13.3.2  node_modules/puppeteer                       preact-cli
react-refresh                    0.10.0   0.10.0      0.11.0  node_modules/react-refresh                   preact-cli
sass-loader                      10.2.1   10.2.1      12.5.0  node_modules/sass-loader                     preact-cli
sirv                             1.0.19   1.0.19       2.0.2  node_modules/sirv                            preact-cli
stack-trace                      0.0.10   0.0.10  1.0.0-pre1  node_modules/stack-trace                     preact-cli
style-loader                      2.0.0    2.0.0       3.3.1  node_modules/style-loader                    preact-cli
stylus                           0.54.8   0.54.8      0.56.0  node_modules/stylus                          preact-cli
stylus-loader                     4.3.3    4.3.3       6.2.0  node_modules/stylus-loader                   preact-cli
terser-webpack-plugin             4.2.3    4.2.3       5.3.1  node_modules/terser-webpack-plugin           preact-cli
typescript                        4.2.4    4.2.4       4.5.5  node_modules/typescript                      preact-cli
webpack                          4.46.0   4.46.0      5.68.0  node_modules/webpack                         preact-cli
```

Mainly **typescript@4.2.4** and **sass-loader@10.2.1** in `preact-cli`. Is this a possibility?

**Comment by rschristian** [comment]
Preact itself has no dependencies. Those are all devDeps.

Nost if those dependencies cannot be touched in Preact-CLI, no. We're on Webpack 4 still, though a PR is open for 5.

Upgrading TS in CLI would do nothing. You should be providing your own install of TS.

**Comment by cdog** [comment]
Managed to pin typescript version as you suggested. Next issue with bumping sass-loader from 10 to 12:
```
npm WARN Could not resolve dependency:
npm WARN peerOptional node-sass@"^4.0.0 || ^5.0.0 || ^6.0.0" from sass-loader@10.2.1
npm WARN node_modules/sass-loader
npm WARN   peerOptional sass-loader@"^10.2.0" from preact-cli@3.3.5
npm WARN   node_modules/preact-cli
npm WARN   1 more (the root project)
```

Looking forward for webpack@5 changes. Thanks!

**Comment by rschristian** [comment]
In general, you shouldn't be using a dependency of a dependency directly. If you need to access/run/whatever it, it should be listed as a dependency in your project.

TS 4.2.4 fits our needs in the CLI just fine. If you have different needs, rather than overriding that as listed above (this is very hacky and could break things), you should have a separate install.

Edited the above, some can be touched but they're minor version bumps, so it really doesn't matter if they're slightly outdated. It's not going to cause anyone problems.

**Comment by cdog** [comment]
Hey Ryan, all clear. I have it listed in my package. Using a multi-package
repository with Lerna, whew one pf the packages is a Preact app. Already
had specific versions in root, however seems not picked correctly. After
adding in specific project from entire setup is started working.
