### ISSUE TITLE
Flicker on render of prerendered pages

### ISSUE THREAD

**Issue by nikse** [preactjs/preact-cli#1535]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
~When I build my app w/ prerendered url's the css that is being inlined on the page and the css that is loaded in the bundle.css file are the same, i believe causing a flickering to happen when the bundle.css file loads.~
I think hydration is causing a flicker

The other possibility is that the app is flickering on hydration for somer reason

**If the current behaviour is a bug, please provide the steps to reproduce.**
To be honest, i'm not sure how this is happening. It sort of just creeped up after my app got a little more complicated. I am trying to load tailwind globally, which seems to be working fine and I am being forced to do a weird loading split (maybe this is the issue) to get the aws cognito library loaded

preact.config.js - https://gist.github.com/nikse/76e1bf6f964219dbb69832657df6b9fc
postcss.config.js - https://gist.github.com/nikse/b2f85e9a9a980bf136aff891b86c5f63

**What is the expected behaviour?**
~The inlined css should be on the page and should not load in the bundle.css file. I believe there shouldn't even be a bundle.css file?~
The flicker shouldn't happen

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
Environment Info:
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 88.0.4324.146
    Firefox: 83.0
    Safari: 14.0.1
  npmPackages:
    preact: ^10.3.2 => 10.5.7 
    preact-cli: ^3.0.0 => 3.0.3 
    preact-compat: ^3.19.0 => 3.19.0 
    preact-render-to-string: ^5.1.4 => 5.1.12 
    preact-router: ^3.2.1 => 3.2.1 
  npmGlobalPackages:
    preact-cli: 3.0.3

**Comment by nikse** [comment]
Here's a screen recording showing the issue, can't figure out whey it's doing this for the life of me

https://user-images.githubusercontent.com/1050982/107300621-e27d0b00-6a47-11eb-822d-0f94ad0ba181.mov

**Comment by rschristian** [comment]
The `bundle.css` is needed if you have multiple pages. If initially load `/foo` and have client side navigation, when you switch to `/`, the `index.html` page isn't pulled down. Those styles, if they only exist inlined in that html doc, will be inaccessible. Hence the bundle. 

Extra CSS shouldn't cause a flash. Probably a hydration issue.

**Comment by nikse** [comment]
Ya, I'm still digging into it and that was just a hunch. There is actually a css issue right now, but that's because the inline css and bundle css are *not* matching, so I'm actually missing some styles I'd expect to be inlined on the page. Thanks for the quick response on that one. Any ideas of what could be causing a hydration issue? Something that can maybe be fixed with keys?

**Comment by rschristian** [comment]
[Critters](https://github.com/googleChromeLabs/critters) handles the CSS inlining. Should inline all rules in the HTML file though, so not sure what you're looking for vs what you're getting.

That's a number of problems that can cause a flash, not necessarily just hydration issues. I think the most common is to make sure you're not asynchronously loading your router, but beyond that I'd just be guessing without a reproduction with some code.

**Comment by nikse** [comment]
Alright, I actually got the inline css issue figured out. I ended up only running my purgecss on a client build which took care of that issue.

Re: the flicker, what code would you need to check out? I included my preact.config.js above, lmk what you'd like to look at and I can get it to you

**Comment by rschristian** [comment]
Something like a codesandbox would be ideal.

**Comment by nikse** [comment]
Sure thing, will update you soon. In the meantime I'm wondering if this line in my config might be causing issues? Essentially I had to split the app files into and app.js and an app_ssr.js file. The app.js is pretty much just a shell that loads the aws cognito library because I couldn't get prerendering to run with that library being imported.

```
// split entry so that we can load aws cognito
    if (env.isProd && env.isServer) {
      config.entry['ssr-bundle'] = config.entry['ssr-bundle'] + '_ssr'
    }
```

Here's those two app files:
app.js https://gist.github.com/nikse/275a369e51178209f22e1db80fea9f9e
app_ssr.js https://gist.github.com/nikse/ed8098bc0408f015907fd4ea07488dae

**Comment by rschristian** [comment]
Is there a reason why a window check wouldn't work?

```
if (typeof window !== "undefined") { ... }
```

**Comment by nikse** [comment]
@rschristian yeah, it's because the build fails when I import the cognito library and I can't wrap an import in an if statement, so that was the only solution I could come up with that allowed me to use the library.

Here's the aws import `import Amplify, { Auth } from 'aws-amplify'`

and here's the build fail when importing that in an app file that is running during the build
```
 Build  [=================== ] 93% (156.4s) after chunk asset optimizationUnable to read sourcemap: /Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/ssr-bundle.js.map

ReferenceError: self is not defined
method: +TSP
[object Object]
This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.

See https://github.com/developit/preact-cli#pre-rendering for further information.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reit@0.0.0 build: `preact build --preload`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reit@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kameronniksefat/.npm/_logs/2021-02-09T02_08_50_839Z-debug.log```

**Comment by rschristian** [comment]
You can use the dynamic `import()` to import in an if statement, or anywhere for that matter.

```
if (typeof window !== undefined) {
  async function amplify() {
	const { default: Amplify, Auth } = await import('aws-amplify');
	Amplify.configure(...)
  }

  amplify();
}
```

**Comment by nikse** [comment]
@rschristian still get the error 
```
[BABEL] Note: The code generator has deoptimised the styling of /Users/kameronniksefat/www/kam/realtymogul/investflow-reit/node_modules/@aws-sdk/client-pinpoint/dist/es/protocols/Aws_restJson1.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/kameronniksefat/www/kam/realtymogul/investflow-reit/node_modules/@aws-sdk/client-s3/dist/es/protocols/Aws_restXml.js as it exceeds the max of 500KB.
 Build  [=================== ] 93% (145.0s) after chunk asset optimization✖ ERROR ReferenceError: self is not defined
    at Object.+TSP (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/1.chunk.95733.js:1:5029)
    at n (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/ssr-bundle.js:1:194)
    at Object.Y6hj (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/1.chunk.95733.js:81:4)
    at n (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/ssr-bundle.js:1:194)
    at Object.2y9g (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/1.chunk.95733.js:8:4151)
    at n (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/ssr-bundle.js:1:194)
    at Module.ot3a (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/1.chunk.95733.js:96:142488)
    at n (/Users/kameronniksefat/www/kam/realtymogul/investflow-reit/build/ssr-build/ssr-bundle.js:1:194)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reit@0.0.0 build: `preact build --preload`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reit@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kameronniksefat/.npm/_logs/2021-02-09T03_38_55_621Z-debug.log
```

**Comment by nikse** [comment]
Here's a small codesandbox with key files https://codesandbox.io/s/sleepy-darwin-z66fh. i can upload a built folder there, just kind of hard to get it all in there when i can't import the repo

**Comment by nikse** [comment]
@rschristian I appreciate the help so far and staying along with me. I've tracked it down to an inline css issue, essentially some css that should be inlined isn't getting in there. I thought disabling the purgecss server side solved that issue, but looks like that didn't do it. So looks like the code splitting I'm doing is fine, I'm gonna keep investigating and can update here if I figure anything out. Thanks again for taking a look!

**Comment by nikse** [comment]
I'm using tailwind for this project and the html w/ the classes that should be inlined is showing up in the prerendered html, so not sure how the classes aren't making it in there (possibly being stripped out?). Here's a gist to the rendered html https://gist.github.com/nikse/93b0529645ed8d3cced7c6273cc2635c. One of the classes I'm seeing in the html that I'm not seeing in the inlined css is `sm:block`, which should render as `sm\:block` in the inlined css

**Comment by rschristian** [comment]
CSS imports in `components/` and `routes/` are treated as CSS modules by default. The following in your `preact.config.js` would disable that, if you want to try it. 

```
const css = helpers.getLoadersByName(config, 'css-loader')[0];
css.loader.options.modules = false;
```

**Comment by nikse** [comment]
Alright, now I'm thinking it's because the css that's being loaded in via the style is lazy loading w/ `media="only x" onload="this.media='all'`, any way to disable that? I'm still seeing a small flicker in the main content even when I remove that, but I could just render a loader server side and call it a day

```<link href="/bundle.6c8e1.css" rel="stylesheet" media="only x" onload="this.media='all'"><noscript><link rel="stylesheet" href="/bundle.6c8e1.css"></noscript>```

Re: the css modules, I do want those enabled as I have a few random style sheets that I need modules for

**Comment by nikse** [comment]
Alright, so played around with critters last night and resolved the css loading to a different method and still no luck. Still seeing a flash of content + a flash of content being styled improperly, which is what lead me to believe it was some css issue.

Here is a link to a code sand box w/ a build and the relevant config files. Not sure if you can garner anything from that, I can upload more manually to this codesandbox if you think you can help me https://codesandbox.io/s/inspiring-swirles-p30dg

thanks

**Comment by nikse** [comment]
Alright, after chasing my tail around all night I just removed the inline styles and it works now. Thanks again for helping here, gonna close this guy out
