### ISSUE TITLE
Lib's worker.js not found on preact watch

### ISSUE THREAD

**Issue by likidu** [preactjs/preact-cli#1540]
I scaffolded a typescript template and added the asm.js version of TDLib - [tdweb](https://github.com/tdlib/td/blob/master/example/web/README.md) into [my project](https://github.com/likidu/kaigram/tree/preact). 

When I do `preact watch`, it reports that the `c3af216b32ab782ac3eb.worker.js` (a.k.a `worker.js`) which is loaded by [`tdweb.js`](https://github.com/likidu/kaigram/blob/preact/tdweb/dist/tdweb.js#L231) is not found.

From the console, it seems that the `worker.js` is not loaded by **webpack-dev-server**:
![image](https://user-images.githubusercontent.com/575981/109502819-7173c500-7ad4-11eb-9435-113a73a668dc.png)

This might be not entirely related with `preact-cli` rather than how to load ServiceWorker properly. But just want to get some more information or hints here. Thanks.

## Reproduction

* `npm run dev`
* Open `http://localhost:8080` and browser dev tool with console
* From the Network tab, the `sw-debug.js` could not not fetch this `worker.js` due to it doesn't exists in the webpack-dev-server source tree.

## Expected behavior

The `worker.js` should load properly with the webpack-dev-server.

## Actual behavior

`404 not found` in console.

**Please mention other relevant information.**

Please paste the results of `preact info` here.

```sh
Environment Info:
  System:
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.10.0 - /opt/homebrew/bin/node
    npm: 7.5.3 - /opt/homebrew/bin/npm
  Browsers:
    Edge: 85.0.564.51
    Firefox: 52.9.0
    Safari: 14.0.3
  npmPackages:
    preact: ^10.5.12 => 10.5.12
    preact-cli: ^3.0.5 => 3.0.5
    preact-render-to-string: ^5.1.12 => 5.1.12
    preact-router: ^3.2.1 => 3.2.1
```

**Comment by rschristian** [comment]
The library's built output expects to find resources at that URL, but they're not included. 

Not sure what the best solution is, will need to do some research myself (never needed this before), but moving those 3 files (`c3...`, `1.c3...`, `81...`) into `src/` will have them served as you'd need so they won't 404

**Comment by likidu** [comment]
It looks like I can override the DevServer `contentBase` by including the **tdweb** folder in it. I added these lines into my `preact.config.js`:

```js
if (!env.production) {
            Object.assign(config.devServer, {
                contentBase: [
                    join(__dirname, '/src'),
                    join(__dirname, '/tdweb/dist'),
                ],
            })
        }
```
