### ISSUE TITLE
Why do I still get sw-debug.js requests when I use --no-sw

### ISSUE THREAD

**Issue by maltoze** [preactjs/preact-cli#1543]
**What is the current behaviour?**
Still get sw-debug.js requests.

**Steps to Reproduce**
```
  "scripts": {
    "build": "preact build --no-esm --no-sw --no-prerender --no-inline-css",
    "serve": "sirv build --port 8080 --cors --single",
    "dev": "preact watch --sw false",
    "lint": "eslint 'src/**/*.{js,jsx,ts,tsx}'",
    "test": "jest ./tests"
  }
```
1. `npm run build`
2. After `npm run serve`,  following request will appear
`[11:33:54] 404 ─ 0.41ms ─ /sw-debug.js`

**What is the expected behaviour?**

**Please mention any other relevant information**
```
Environment Info:
  System:
    OS: Linux 4.19 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Binaries:
    Node: 14.5.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.9 - /usr/bin/npm
  npmPackages:
    preact: ^10.3.1 => 10.5.12 
    preact-cli: ^3.0.5 => 3.0.5 
    preact-render-to-string: ^5.1.4 => 5.1.12 
    preact-router: ^3.2.1 => 3.2.1 
```

**Comment by rschristian** [comment]
That would be because you have not unregistered the debug service worker. 

In your browser's dev tools, go to `Application` and unregister the SW. After doing so, the request will go away.

**Comment by maltoze** [comment]
Thanks.

**Comment by rschristian** [comment]
In case you weren't aware, `--no-x` is just another way of doing `--x false`. Works the same for dev & building.

Just noticed you use both `--no-sw` & `--sw false`.
