### ISSUE TITLE
`--clean` is considered invalid argument in 3.0.5

### ISSUE THREAD

**Issue by mashabow** [preactjs/preact-cli#1544]
**What is the current behaviour?**

In 3.0.5, I got the following error with `$ preact build --clean`:

```
✖ ERROR Invalid argument clean passed to build. Please refer to 'preact build --help' for full list of options.
```

**Steps to Reproduce**

1. Run `$ preact build --clean`

**What is the expected behaviour?**

Successfully build as in 3.0.3.

**Please mention any other relevant information**

It seems the same validation issue as https://github.com/preactjs/preact-cli/issues/1489.

**Comment by rschristian** [comment]
That would be a correct error. 

While we use it internally, that isn't a documented flag anywhere?

**Comment by mashabow** [comment]
> While we use it internally, that isn't a documented flag anywhere?

Oh, I found that I read [a very old version of README.md](https://github.com/preactjs/preact-cli/blob/v3.0.0-rc.2/README.md#preact-build). Sorry.

**Comment by rschristian** [comment]
Ah, np. We do clean by default, for what it's worth, so you're probably already getting the behaviour you'd expect.
