### ISSUE TITLE
How can I use the css module in widget template?

### ISSUE THREAD

**Issue by spb200** [preactjs/preact-cli#1546]
**What is the current behavior?**
I can't seem to find any documentation for enabling CSS modules in preact. the document in this case is confusing. I would really appreciate your help.

**Comment by rschristian** [comment]
Which widget template? Slight difference in them. I'd also recommend my forks for both of them, bit more up-to-date.

**Comment by spb200** [comment]
I use this template from the document https://github.com/preactjs-templates/widget.

**Comment by rschristian** [comment]
I'd suggest this: https://github.com/rschristian/widget, but in either case, Microbundle's instructions cover how to use modules. 

To import a CSS file as a module, either file name must either be in the form `x.module.css` or you add the `--css-modules true` flag to Microbundle.

**Comment by spb200** [comment]
Thanks a lot, this [link](https://github.com/developit/microbundle#css-and-css-modules) that you mentioned helped me a lot and solved my problem

**Comment by rschristian** [comment]
Glad to hear it. I'll close this out then if the issue was solved, but certainly feel free to reply if you have any more issues that I can help with/need more info on.
