### ISSUE TITLE
How can I embed the widget in other websites ? 

### ISSUE THREAD

**Issue by spb200** [preactjs/preact-cli#1548]
**What is the current behavior? ** 

Based on the document of the widget template, I couldn't figure out how I should build the widget so I could use it on any website, not only preact web apps. Could you please provide me with a command build or the other required configs?

**Comment by spb200** [comment]
When I try to build the widget with this command: `"preact build --prerender --clean --sw"` and embed it in my Wordpress website, the path of service worker scope changes to domain of host website.
![Screen Shot 2021-03-30 at 9 20 52 AM](https://user-images.githubusercontent.com/41111577/112947740-6d2ade00-914c-11eb-9f6b-a55201cc2347.png)
These red lines should be the address of deployed widget but it is the host website's domain.

and this is what I add to the body of host website:
```
<div data-widget-form="widget" data-prop-slug="j4N9hoZyXlcue8e" data-prop-type="side-widget" dir="ltr"> 
        <script type="text/props"> 
            { "position": "right" }
	</script> 
</div> 
 <script async src="https://6062c6d0231dac0008704ee5--flamboyant-ramanujan-827a17.netlify.app/bundle.js"></script>	

```

**Comment by rschristian** [comment]
Firstly I'd recommend [my fork](https://github.com/rschristian/widget) as it's a bit more up-to-date.

However, in the existing template, you want the `dist` command. `preact-cli` is for applications, not libraries. The `build` command there I don't see much use for, personally. Not sure why it was added.
