### ISSUE TITLE
Unable to add latest webpack v5

### ISSUE THREAD

**Issue by ThunderArmy** [preactjs/preact-cli#1552]
When I try to add webpack v5 to my current project the dev enviroment wont build and outputs
`Error: Cannot find module 'webpack/lib/MultiEntryPlugin'`

1) Add
`    "webpack": "^5.35.1",`
to `package.json`

2) Run `npm run dev`

package.json:
https://gist.github.com/ThunderArmy/21163cdb902646cc711b053462859f04

Additional info:
I tried adding  `--no-prerender` but it doesn't seem to help. 

full log stack:
https://gist.github.com/ThunderArmy/5a3c8b0d6fb5d14f7e18650ec8f7b46b

**Comment by rschristian** [comment]
Why are you adding Webpack manually? Preact-CLI handles all of that for you.

**Comment by ThunderArmy** [comment]
I'm trying to add https://github.com/react-toolbox/react-toolbox to my project, which needs postcss and it's loader.
Since i'm new to preact and I couldn't figure out webpack was already in preact-cli by reading the wiki, i tried adding it.

**Comment by rschristian** [comment]
[Here's the section of the docs where we specify how to configure the Webpack config](https://github.com/preactjs/preact-cli#webpack). You can strip out a lot of those dependencies, they're just replicating what Preact-CLI does right out of the box. 

We already process your styles with PostCSS, see [here](https://github.com/preactjs/preact-cli/blob/4b8164172ec4e7e9a725909b58bc54eb1f82ed8a/packages/cli/lib/lib/webpack/webpack-base-config.js#L261) and [here](https://github.com/preactjs/preact-cli/blob/4b8164172ec4e7e9a725909b58bc54eb1f82ed8a/packages/cli/lib/lib/webpack/webpack-base-config.js#L285). You can customize the behavior with that first link if you need to.

**Comment by ThunderArmy** [comment]
After removing unneccesary webpack-related items from package.json and running npm run dev it now tells me it cannot find module webpack

The new package.json looks the following: https://gist.github.com/ThunderArmy/d6754ad53c7406e73482dede059d297c

**Comment by rschristian** [comment]
From where is it reporting that? Can you provide a reproduction? What you have there looks okay to me.

**Comment by ThunderArmy** [comment]
Simply running `npm run dev`

Error log looks like the following:
`N:\Projects\Preact\teacharr>npm run dev

> teacharr@0.0.0 dev N:\Projects\Preact\teacharr
> preact watch

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack'
Require stack:
- N:\Projects\Preact\teacharr\node_modules\webpack-dev-server\lib\Server.js
- N:\Projects\Preact\teacharr\node_modules\preact-cli\lib\lib\webpack\run-webpack.js
- N:\Projects\Preact\teacharr\node_modules\preact-cli\lib\commands\build.js
- N:\Projects\Preact\teacharr\node_modules\preact-cli\lib\commands\index.js
- N:\Projects\Preact\teacharr\node_modules\preact-cli\lib\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (N:\Projects\Preact\teacharr\node_modules\webpack-dev-server\lib\Server.js:23:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'N:\\Projects\\Preact\\teacharr\\node_modules\\webpack-dev-server\\lib\\Server.js',
    'N:\\Projects\\Preact\\teacharr\\node_modules\\preact-cli\\lib\\lib\\webpack\\run-webpack.js',
    'N:\\Projects\\Preact\\teacharr\\node_modules\\preact-cli\\lib\\commands\\build.js',
    'N:\\Projects\\Preact\\teacharr\\node_modules\\preact-cli\\lib\\commands\\index.js',
    'N:\\Projects\\Preact\\teacharr\\node_modules\\preact-cli\\lib\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! teacharr@0.0.0 dev: `preact watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the teacharr@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by rschristian** [comment]
Clear your `node_modules` and reinstall. Webpack is definitely a dependency: https://github.com/preactjs/preact-cli/blob/4b8164172ec4e7e9a725909b58bc54eb1f82ed8a/packages/cli/package.json#L145

**Comment by ThunderArmy** [comment]
Already deleted the folder and ran `npm i`
Is there anything i'm missing?

**Comment by ThunderArmy** [comment]
Turns out after removing preact-cli globally it still didnt work.

Had to run `npm install -g --force preact-cli` again, now it's working

**Comment by rschristian** [comment]
We don't recommend installing it globally at all See [Usage](https://github.com/preactjs/preact-cli#usage). Generally you'll just end up with an out-of-date project initializer that way. 

Glad it's working for you now. Can you use your component lib as you'd expect?

**Comment by ThunderArmy** [comment]
Seems like the best practises guide is outdated then, because it says

`As the name implies, Preact CLI is a command-line tool that can be run in the terminal on your machine. Install it globally by running:

npm install -g preact-cli` [https://preactjs.com/guide/v10/getting-started#best-practices-powered-by-preact-cli]

The additional lib is working, but there are no animations when i click their buttons. Guess i'll have to do more research :)

**Comment by ThunderArmy** [comment]
I originally got the material lib from https://github.com/developit/preact-compat-example because that's what they used in the example. But it seems like many things changed since then, especially with using webpack beause it's installed by default in preact-cli.

I still can't get their example code to work. Could it be that there was so much changed it simply won't support react-toolbox anymore?

**Comment by rschristian** [comment]
Thanks for pointing that out! I fixed it [on one page](https://preactjs.com/cli/getting-started). but evidently missed that usage. Will get that corrected! Appreciate it.

That link doesn't actually use Preact-CLI, look at its dependencies. It instead chooses to roll its own tooling. But yes, in 5 years a lot of things change. react-toolbox seems to be dead an unmaintained entirely. Last commit was nearly 2 years ago, with minimal work done for a few years before. It looks like [material-ui](https://github.com/mui-org/material-ui) is the popular option if you want to use Material Design with (p)react these days, though I'm not a user of Material so maybe worth some more research there.

**Comment by ThunderArmy** [comment]
Sure! Glad i could also help somewhere!

Yup i found that out myself after struggling with it for so long.
And thanks for the hint on react-toolbox and material-ui! I will have a look at it.

I will close this issue for now :)
