### ISSUE TITLE
Problem when using build prerender

### ISSUE THREAD

**Issue by metehus** [preactjs/preact-cli#1558]
- [x] Check if updating to the latest Preact version resolves the issue: **Yes, using preact 10.5.13**

## Describe the bug
Preact isn't able to prerender a project on build, with a file that does not exist.
When i run "preact build", it shows the following error:

```
Unable to read file: /mnt/d/Projects/Musicorum/prestion/testing/src/src/Promise.ts

ReferenceError: self is not defined
method: nGod
at: /mnt/d/Projects/Musicorum/prestion/testing/src/src/Promise.ts:4:5

Source code:


This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.
```
The thing is that this file (`Promise.ts`) doesn't exist, either this last `src` folder. Here is my file tree:
![image](https://user-images.githubusercontent.com/22124518/117905307-5ded9300-b2a9-11eb-9d7c-1a1aa99171d7.png)

## To Reproduce

Because this is a build problem, i can't link to a csb/codepen app, but the full code is open source at [this commit](https://github.com/musicorum-app/Prestion/tree/1232a70030821887984ea75547315ed6656f604e).

## Expected behavior
It should build with no problems. I used the `--no-prerender` option and it works fine, but it would be better to use the prerender option.

**Comment by rschristian** [comment]
You're looking in the wrong folder. You map a path to `../src`. Not sure where the `Promise.ts` is coming from, but your issue is in the other directory there. 

Not sure how well `file:` is supported at the moment. Will try to take a look into this more tomorrow.

**Comment by rschristian** [comment]
It seems you're heavily using the window object so I'm not sure there's even any use in enabling prerendering here (at least not at the moment, with the content that's in the repo). You're likely better off disabling as browser graphics / animation isn't usually cut out for prerendering / ssr.

**Comment by metehus** [comment]
> It seems you're heavily using the window object so I'm not sure there's even any use in enabling prerendering here (at least not at the moment, with the content that's in the repo). You're likely better off disabling as browser graphics / animation isn't usually cut out for prerendering / ssr.

You are right, there's no much use of SSR here, and it works fine without it so I'm gonna keep with that, thanks!
