### ISSUE TITLE
Show typescript errors in the browser

### ISSUE THREAD

**Issue by lishine** [preactjs/preact-cli#1559]
**What is the current behaviour?**
typescript error shows in the console, but it does not show in the browser, instead browser stop reloading

**What is the motivation or use case for changing this behaviour?**
To know that there are errors from looking at the browser

**Please mention any other relevant information.**
preact-cli 3.04

```
Environment Info:
System:
OS: Linux 5.11 Pop!_OS 20.04 LTS
CPU: (12) x64 AMD Ryzen 5 1600X Six-Core Processor
Binaries:
Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
Yarn: 1.22.5 - /usr/bin/yarn
npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
Browsers:
Chrome: 90.0.4430.93
Firefox: 87.0
npmPackages:
preact: ^10.5.7 => 10.5.13
preact-cli: ^3.0.4 => 3.0.5
preact-render-to-string: ^5.1.12 => 5.1.19
npmGlobalPackages:
preact-cli: 3.0.3
```

**Comment by ForsakenHarmony** [comment]
Yes, an error overlay would be nice to have, feel free to open a PR for it

The best place to add it would probably be there
https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/webpack/webpack-client-config.js#L286

**Comment by ForsakenHarmony** [comment]
Oh, it seems like the overlay is explicitly disabled there, not entirely sure why

A way to enable it would be via the config
`preact.config.js`
```js
module.exports = function (config, env, helpers) {
	if (env.isProd) return;
	config.devServer.overlay = true;
};
```

**Comment by lishine** [comment]
Great!
Thank you!
