### ISSUE TITLE
version 3.1.0 does not seem to be published on npm

### ISSUE THREAD

**Issue by Gamesh** [preactjs/preact-cli#1566]
in Github releases i see version 3.1.0, but in npm there is v3.0.5 and then 3.2.0 but no 3.1.0

**Comment by rschristian** [comment]
Yes. Is this a problem...?

**Comment by ForsakenHarmony** [comment]
It was indeed not published because `changesets` was not set up properly

**Comment by Gamesh** [comment]
@rschristian for me yes, i can't use version 3.1 :)

**Comment by Gamesh** [comment]
@ForsakenHarmony it still don't see it on NPM
![image](https://user-images.githubusercontent.com/171747/120320608-0d3aea00-c2eb-11eb-823c-865a5e89732d.png)

**Comment by rschristian** [comment]
@Gamesh That's not a problem description. Why do you need v3.1.0?

**Comment by Gamesh** [comment]
because 3.2 was broken and un-usable, i see it's fixed now in 3.2.1. 
Would probably be good to still have it for people that don't like to skip minor versions if you're observing semver

**Comment by rschristian** [comment]
Well there's nothing to skip here as the version was never published 😉

I honestly see no value in going back to publish an outdated version. 3.2 is the next semver minor for all intents and purposes.

**Comment by NSExceptional** [comment]
@rschristian Is it really that much work to publish it? You make it sound so difficult

If you're not going to publish it, why not just delete the release too then?

**Comment by rschristian** [comment]
@NSExceptional 

A) I don't think I even have credentials, so I haven't made any comments towards difficulty/time as it wouldn't be me doing it. It's not about difficulty, but spending people's volunteer time efficiently. 

B) it's been eclipsed. Unless you can provide a concrete reason why someone should take 5 minutes to publish a version that's outdated, I don't see why anyone should spend any amount of time, no matter how little, doing it. It just doesn't make sense.

What is this value that I'm not seeing? As far as I've been made aware, there's no advantages to 3.1.0 over 3.2.x. I'm all ears though.

**Comment by NSExceptional** [comment]
I'm not sure I _can_ convince you, but I will say this: I would personally do it just because someone asked, if it really would take all of five minutes. 🤷🏻‍♂️

You've probably spend more than 5 minutes in this thread alone

**Comment by rschristian** [comment]
I'd certainly maintain that a version missing is not an issue in itself. Without a problem description, or why it's needed, I cannot know how to answer the question.

I'm certainly not "playing dumb" by answering the question that was asked, rather than trying to guess the context, and I don't appreciate that comment. For all I knew that was just a gentle prod that we made a mistake in publishing, which we already knew. 

If there's a problem with the latest release, the correct solution would be to fix that release, not release an older version.
