### ISSUE TITLE
Missing type="text" on inputs in prerendered HTML-files

### ISSUE THREAD

**Issue by roydigerhund** [preactjs/preact-cli#1583]
**Describe the bug**
On input fields in prerendered HTML-files, the type attribute is missing if it has the default value "text". Strangely this is not happening when testing directly with the "preact-render-to-string" package in this [CodeSandbox example](https://codesandbox.io/s/preact-render-to-string-test-with-inputs-bdis2?file=/src/index.js).

But it happens when I prerender the same content with `preact build`.

**To Reproduce**
1. Prerender a file with an input with `type="text"` in it.
2. Check the prerendered index.html file, the type attribute should be gone

**Expected behavior**
The `type="text"` attribute should not be stripped away, even though it is the default value. It might for example be used for CSS styling.

**Comment by roydigerhund** [comment]
@marvinhagemeister this is an example repo where you can test the wrong behaviour: https://github.com/roydigerhund/input-attribute

**Comment by developit** [comment]
I believe this might be caused by Critters, which is doing critical CSS inlining here. Can you try with `preact build --no-inline-css`?

**Comment by roydigerhund** [comment]
@developit If `--no-inline-css` completely disables Critters, then it has nothing to do with it. I already disabled inline CSS in the project where I stumbled upon this bug and I tested it in the example repository too, sadly it didn't resolve the issue.

**Comment by rschristian** [comment]
Sorry for the super late response!

This is intentional, redundant attributes are stripped by `html-webpack-plugin` (which uses `html-minifier-terser` to do this).

If you want to disable this,  you can use your config file to do so:

`preact.config.js`
```
export default (config, env, helpers) => {
    if (env.isProd) {
        const HtmlPlugin = helpers.getPluginsByName(config, 'HtmlWebpackPlugin')[0];
        if (HtmlPlugin) {
            const pluginOptions = HtmlPlugin.plugin.options;
            pluginOptions.minify.removeRedundantAttributes = false;
        }
    }
}
```
