### ISSUE TITLE
global scope polution and conflict with jquery

### ISSUE THREAD

**Issue by Gamesh** [preactjs/preact-cli#1584]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
preact seems to define a global function named dollar, like jquery does:

```js
function $(){}
```

```
$
function ()
length: 0
name: ""
<prototype>: function ()
```

when using preact with microbundle to create standalone libs, this conflicts with jquery on the page. 

**To Reproduce**
create a new project `npx preact-cli create default preact-scope-test`
1. goto preact-scope-test
2. run `npm run dev`
3. open browser and in console type `$`
4. it should print out `function()`

**Expected behavior**
it should print $ is undefined

**Comment by developit** [comment]
@JoviDeCroock the only thing I could find in our repos that has any chance of causing this was this:
https://github.com/preactjs/prefresh/blob/085eaf8446506220cec5f2fe2c7a6444bed51aee/packages/babel/src/index.mjs#L98

There really aren't any other references to `$` anywhere.

**Comment by JoviDeCroock** [comment]
Hmm, yeah and prefresh itself also namespaces very strictly to `__PREFRESH__`

**Comment by developit** [comment]
er - @Gamesh you mentioned you were checking in the browser console. The browser consoles (all of them) define a `$` function - if you go to `about:blank` and open the console, it'll be in there too. Does it show up as `window.$`?

**Comment by JoviDeCroock** [comment]
Oh that's akward 
![image](https://user-images.githubusercontent.com/17125876/125687988-fd23d81a-d6e7-430d-afaf-ab8a7570cc0f.png)

**Comment by Gamesh** [comment]
@developit nope, `window.$` seems undefined in the preact created project.
but after running my project through microbundle it seems be defined and set to boolean true, not sure if it's related to preact-cli or microbundle at this point
`window.$` -> true

my project sandbox: https://60ef42662578b700086b4dc6--elated-noyce-fbb486.netlify.app/

didn't know about global $ in browsers TIL

**Comment by developit** [comment]
@Gamesh interesting - that definitely sounds like an issue with the code being run through Microbundle, or Microbundle itself. 

Are you able to provide the code you're compiling with Microbundle?

**Comment by developit** [comment]
Ahh okay, I've looked and now I see what is going on. It seems like you're using Microbundle's CommonJS or ESM output targets, but loading the resulting bundle in a standard `<script>` tag. That's always going to introduce random unintentional globals and side effects, because it's not how those bundles are supposed to be used.

You should be using Microbundle's `iife` output format:

```
"scripts": {
  "build": "microbundle -f iife src/index.tsx"
}
```

**Comment by Gamesh** [comment]
Oh, that format was not very well documented, I've set target=web and thought that would be enough, apparently not. Thanks for this tip, might be a solution to all my problems 🙌

**Comment by Gamesh** [comment]
i'm closing this as iife seems to solve it, thanks all for the support
