### ISSUE TITLE
How to build with a stable package name?

### ISSUE THREAD

**Issue by wansiedler** [preactjs/preact-cli#1586]
**What is the current behaviour?**
Right now every
````
preact build
````
creates a random bundle hash in the dist folder.

**What is the motivation or use case for changing this behaviour?**
I would like to have a stable filename in order to use it in docker build.

**Describe the solution you'd like**
```
preact build --file bundle.js
```

**Comment by wansiedler** [comment]
e.g.
I am trying to change the bundle file, so it would be consistent over builds. It doesn't work. As if preact-cli doesnt see it.

        output: {
            chunkFilename: '[name].[id].js',
            filename: '[name].bundle.js'
        },
How can that be changed?

**Comment by rschristian** [comment]
Sorry, was away from computer, didn't want to provide any solution without testing. This should work on non-esm files (need to take a peek yet on correcting those):

```
export default { 
    webpack(config, env, helpers, options) {
        config.output.filename = '[name].js';
        config.output.chunkFilename = '[name].chunk.js';
    },
};
```

Taken from https://github.com/preactjs/preact-cli/issues/924#issuecomment-584772285

**Comment by wansiedler** [comment]
thank you for the answer. sorry, does not work for me =(

**Comment by rschristian** [comment]
What doesn't work? You can copy/paste that directly into your `preact.config.js`.

**Comment by rschristian** [comment]
Closing this out now, figure we have covered all the bases.
