### ISSUE TITLE
webpack 5 configuration tutorial

### ISSUE THREAD

**Issue by wansiedler** [preactjs/preact-cli#1587]
I would like to have full control of webpack 5 configuration under the hood of preact.

There are no tutorials how to interact with webpack 5 through preact.config.js

Could you please include it in the doc section? Thank you!

**Comment by rschristian** [comment]
Preact-CLI isn't using Webpack 5, so there's no way to configure that. As for our current version of Webpack: https://github.com/preactjs/preact-cli#webpack

**Comment by wansiedler** [comment]
What is the version of the webpack used by preact?

**Comment by rschristian** [comment]
https://github.com/preactjs/preact-cli/blob/022d9a8119ea9a4e09963ffbe5ee9adbc9fb0d92/packages/cli/package.json#L135

**Comment by wansiedler** [comment]
Thank you for the reply!
e.g.
I am trying to change the bundle file, so it would be consistent over builds. It doesn't work. As if preact-cli doesnt see it.
````
        output: {
            chunkFilename: '[name].[id].js',
            filename: '[name].bundle.js'
        },
````
How can that be changed?
