### ISSUE TITLE
Error cannot parse stylesheet

### ISSUE THREAD

**Issue by PGameplay** [preactjs/preact-cli#1592]
Importing web fonts crashes the build for me. Error cannot parse stylesheet missing '}'. I'm importing it like this.
In index.css
@import url('link to Google font');
I was struggling with this error for solid 2 days and removing the web font import fixed it for me. Using latest preact cli version.
Also to add it gives error for all stylesheets and doesn't highlight this but when I remove it it builds.

**Comment by rschristian** [comment]
@PGameplay Can you provide that link? Reminds me of #1430, which could be resolved by altering the Google font link format as noted [here](https://github.com/webpack/webpack/issues/10873#issuecomment-631724986)

**Comment by PGameplay** [comment]
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap');

**Comment by rschristian** [comment]
Yep, looks to be the same issue. See if you can edit your URL there to match the altered one in #1430. Should fix the problem.

**Comment by PGameplay** [comment]
Thank you

**Comment by tomas-wrobel** [comment]
That's logical. The parser looks for semicolons, but it also removes quotes from URL. So there are semicolons in middle of `url()` method.

Thank you, you saved my life!!
