### ISSUE TITLE
preact.config.js with webpack watchOptions

### ISSUE THREAD

**Issue by moszeed** [preactjs/preact-cli#1593]
Hello everyone,
first i will thank for your support and work on this awesome tool.
But i`m running into a Problem i cant get resolved alone.

I just want to extend the `preact.config.js` .
All i want is to add following:
```
watchOptions: {
    ignored: '/node_modules/',
    poll: 1000 // Check for changes every second
}
```

but i cant find a solution that is working...
my latest attempt looks like this:

```
// these props are both optional
export default {
    /**
     * Function that mutates the original webpack config.
     * Supports asynchronous changes when a promise is returned (or it's an async function).
     *
     * @param {object} config - original webpack config.
     * @param {object} env - options passed to the CLI.
     * @param {WebpackConfigHelpers} helpers - object with useful helpers for working with the webpack config.
     * @param {object} options - this is mainly relevant for plugins (will always be empty in the config), default to an empty object
     **/
    webpack(config, env, helpers, options) {
        config.devServer.watchOptions: {
            ignored: '/node_modules/',
            poll: 1000 // Check for changes every second
        }
    },
};
```

but i'm still getting a `SyntaxError: Invalid or unexpected token` error.
Thank you for your Help.

**Comment by rschristian** [comment]
What you want is:

```
config.devServer.watchOptions = {
    ignored: '/node_modules/',
    poll: 1000 // Check for changes every second
}
```

Your editor should make pretty clear that the semicolon you have there is invalid syntax.

We do also have a number of [config recipes](https://github.com/preactjs/preact-cli/wiki/Config-Recipes), including [one that's quite similar to your use](https://github.com/preactjs/preact-cli/wiki/Config-Recipes#setting-proxy-for-dev-server-using-config-directly) (syntactically, at least). Certainly feel free to ask though if something doesn't make sense.

**Comment by moszeed** [comment]
big thank you =)
