### ISSUE TITLE
Service Worker required when disabled in dev

### ISSUE THREAD

**Issue by tysonmatanich** [preactjs/preact-cli#1594]
**What is the current behaviour?**
When running `preact watch --sw false` it still tries to attach a service worker.  `preact watch` works fine which should default `sw` to false (https://github.com/preactjs/preact-cli#preact-watch).

**Steps to Reproduce**
1. Use a project without a `.\src\sw.js`
2. Run `preact watch --sw false`
3. See error

> Build failed!
> 
> × ERROR Entry module not found: Error: Can't resolve '.\src\sw.js' in '.\src'
> × ERROR InjectManifest: Entry module not found: Error: Can't resolve '.\src\sw.js' in '.\src'

**What is the expected behaviour?**
Build should succeed using same behavior as `preact watch` which defaults `sw` to `false`

**Please mention any other relevant information**
I'm assuming it was introduced in https://github.com/preactjs/preact-cli/commit/9f9277be2ed50476147bae5567640b36740b4d38

**Environment Info:**
>   System:
>     OS: Windows 10 10.0.19043
>   Binaries:
>     Node: 14.16.1 - C:\Program Files\nodejs\node.EXE       
>     npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
>   npmPackages:
>     preact: ^10.5.14 => 10.5.14
>     preact-cli: ^3.2.2 => 3.2.2
>     preact-render-to-string: ^5.1.19 => 5.1.19
>     preact-router: ^3.2.1 => 3.2.1

**Comment by developit** [comment]
any chance this works correctly via `preact watch --no-sw`?

**Comment by tysonmatanich** [comment]
Yes it does

✅ `preact watch`
✅ `preact watch --no-sw`
❌`preact watch --sw false`

**Comment by rschristian** [comment]
https://github.com/preactjs/preact-cli/blob/b3b6984a1d022ac3348784061bd8864f66f2d670/packages/cli/lib/lib/webpack/webpack-client-config.js#L41

Looks like we're not converting the "false" into a boolean in watch mode as we do in build, just passing the string value through.

Will try to get a fix together here.

**Comment by tysonmatanich** [comment]
It also seems the changes in https://github.com/preactjs/preact-cli/commit/9f9277be2ed50476147bae5567640b36740b4d38 broke the workaround in https://github.com/preactjs/preact-cli/issues/955#issuecomment-692921485 for using a ServiceWorker in watch mode.

**Comment by rschristian** [comment]
@tysonmatanich What doesn't seem to be working? That workaround, as far as I can tell, just matches what's already provided.

That exact config should be broken, as using it will result in duplicate plugins being pushed.

**Comment by tysonmatanich** [comment]
The workaround allows for the custom serviceworker to be used when running with `preact watch --sw`, hence the `if(env.isWatch)`

**Comment by rschristian** [comment]
Sorry, I don't understand. You can customize the config as-is:

```
export default {
    /**
     * Function that mutates the original webpack config.
     * Supports asynchronous changes when a promise is returned (or it's an async function).
     *
     * @param {object} config - original webpack config.
     * @param {object} env - options passed to the CLI.
     * @param {WebpackConfigHelpers} helpers - object with useful helpers for working with the webpack config.
     **/
    webpack(config, env, helpers) {
        if (env.isWatch) {
            const manifestPlugin = helpers.getPluginsByName(config, 'InjectManifest')[0];
            // You can make any modifications you'd like to the manifestPlugin here
        }    
    }
};
```
