### ISSUE TITLE
$PORT preferred over --port

### ISSUE THREAD

**Issue by peterbe** [preactjs/preact-cli#1596]
**What is the current behaviour?**

If I type:
```
▶ PORT=7777 preact watch -p 9999
```
it starts on port :7777. Not :9999

```
Compiled successfully!

You can view the application in browser.

Local:            http://0.0.0.0:7777
On Your Network:  http://192.168.1.192:7777
```

**Steps to Reproduce**
Hopefully clear from the description above. 

**What is the expected behaviour?**
I would expect the `-p` option to trump the environment variable. 
Typing `PORT=7777 preact watch -p 9999` is absurd but typing `preact watch -p 9999` is not and then you get negatively surprised that :9999 did not become the port. 

**Please mention any other relevant information**
My use case was that I was using [`foreman`](https://www.npmjs.com/package/foreman) to start a bunch of things, including `preact watch` and for some reason it sets `$PORT=5000` in there. I don't know why and nor is it very relevant.

Is it just me? I feel like the `-p` (or `--port`) is a lot more explicit and should be trumped over the environment variable.

**Comment by peterbe** [comment]
Here lies the problem: https://github.com/preactjs/preact-cli/blob/b3b6984a1d022ac3348784061bd8864f66f2d670/packages/cli/lib/lib/webpack/run-webpack.js#L15

The `env.port` is always a something. 
If you typed: `preact watch -p` then `env.port === true`. 
If you typed: `preact watch -p xxxx` then `env.port === 'xxxx'`.
If you typed: `preact watch` then `env.port === 8080` (because the default is set there in the `const options` in `watch.js`.

The problem is that it's impossible to know **if the user explicitly specificed** `-p` (or `--port`). 
I think we could extend `validateArgs()` in some fancy way so that we *could* achieve something like this:

```diff
-let userPort = parseInt(process.env.PORT || env.port, 10) || 8080;
+let userPort = env.port_set ? env.port_set : parseInt(process.env.PORT || env.port_default, 10);
env.port = await getPort({ port: userPort });
```

**Comment by peterbe** [comment]
Also, a bit so-so that `validateArgs()` doesn't bark on `--port notanumber`. We can extend `validateArgs()` to fix that (e.g. based on `typeof option.default`) or pull in so other CLI parsing third-party dependency.

**Comment by rschristian** [comment]
Agree, I think it makes sense. We could definitely also add some more validation to the arguments as-is, like you say.

It'd be a breaking change to prefer `--port` over `$PORT` though, so I don't think that can be altered soon.

**Comment by rschristian** [comment]
Alright, fair enough then. I suppose, as mentioned, `-p` is more explicit than `$PORT` so any issues should (hopefully) be quite obvious.
