### ISSUE TITLE
Getting 404 status in the browser 

### ISSUE THREAD

**Issue by webcodehindi** [preactjs/preact-cli#1605]
I m new for Preact CLI and Preact. 

I have created a new project using `preact create default app`
For development running I use `npm run serve`

It shows me

`Your application is ready~! �🚀

  - Local:      http://localhost:8080
  - Network:    Add `--host` to expose`

But in the browser i m getting 404  page can't find error

in terminal it show me 

`404 ─ 14.71ms ─ / `
`404 ─ 0.49ms ─ /profile `

**Comment by rschristian** [comment]
`serve` is a production-like server that serves the results of `build`. You need to run `npm run build` first.

**Comment by webcodehindi** [comment]
Actually i m from VueJs. So i directly run `npm run serve`

Anyway, Thanks 😀

**Comment by rschristian** [comment]
Well, regardless of where you're coming from, that's not what those templates ship with. You certainly can rebind those to whatever you want though. 

`preact dev` (whatever you have that assigned to) is the dev server, while `sirv` is for the prod-like. It will only serve built content, so if you haven't yet built, there's nothing for it to serve.
