### ISSUE TITLE
wrong version of dependency imported with duplicate dependencies using preact-cli

### ISSUE THREAD

**Issue by sjmarshy** [preactjs/preact-cli#1616]
My preact app uses `fp-ts@2`. The app has a dependency on `arya` which has a dependency on `fp-ts@1.19`

When I build or watch using `preact-cli` then my `arya` library gets built against `fp-ts@2`. This causes errors because the interfaces are different. 

It's possible that this is a webpack configuration issue, as I have found a similar issue here: https://github.com/webpack/webpack/issues/6538

It's not clear to me how to apply the solution provided in that issue in context of preact-cli, so any help/advice would be appreciated. 

Thanks.

**Comment by rschristian** [comment]
Can you provide a reproduction? [`arya` doesn't seem to have any dependencies](https://www.npmjs.com/package/arya) so I'd need some more info to try to test a solution against.

**Comment by sjmarshy** [comment]
Sorry, was just on holiday for a few days so didn't see this response! The `arya` I was referring to is a private package, so that's my fault. I've created a reproduction in a repo here: https://github.com/sjmarshy/preact-cli-repro

Thanks!

**Comment by rschristian** [comment]
No worries, thanks for providing that.

Seems to be an issue with how we resolve dependencies at the moment, nothing for you to solve in user config I believe. Will try to get a fix together.

**Comment by rschristian** [comment]
Okay so this is a tad hacky, but will unblock you for the time and won't create issues if/when we do get this fixed.

```js
// preact.config.js

export default (config, env, helpers) => {
    const modules = config.resolve.modules;
    if (modules[2] === 'node_modules') {
        modules.splice(2, 1);
        modules.unshift('node_modules')
    }
}
```

Changes the resolve priority (if it matches the current order) and alters it.
