### ISSUE TITLE
Support less-loader v8 and up

### ISSUE THREAD

**Issue by rejhgadellaabsl** [preactjs/preact-cli#1627]
**What is the current behaviour?**

According to the [README](https://github.com/preactjs/preact-cli#using-css-preprocessors), I can just run `npm install --save-dev less less-loader` and start using less files. However, running a build currently throws an error: `this.getOptions is not a function`. Downgrading to less-loader v7 solves the issue.

(An alternative to supporting newer less-loader packages would be to mention the limitation in the README)

**Steps to Reproduce**

1. Create a preact project using the cli
2. Follow the steps to use less: `npm install --save-dev less less-loader` and use less files instead of css
4. Run `npm run build`

**What is the expected behaviour?**

The build should succeed.

**Please mention any other relevant information**

```
Environment Info:
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.43)
  npmPackages:
    preact: ^10.3.2 => 10.6.2
    preact-cli: ^3.0.0 => 3.3.2
    preact-render-to-string: ^5.1.4 => 5.1.19
    preact-router: ^3.2.1 => 3.2.1
```

**Comment by rschristian** [comment]
Cannot support anything above v7.x, as they all require Webpack v5.

Nice catch though, do you want to make a PR updating the docs?

**Comment by rejhgadellaabsl** [comment]
Oh sure. Just need to find a break between things so may take a day or so 👍
