### ISSUE TITLE
Getting "Cannot convert non-arrow function to a function expression" upon build

### ISSUE THREAD

**Issue by devlukasz** [preactjs/preact-cli#1628]
- [X] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I have a helper class which is used within a preact component, and its failing on build due to the mentioned error in the name

**To Reproduce**
This is a class which I am importing to a component to use to help calculate certain stuff:

```
class DuplicateChecker {
  constructor() {
    this.iframe = this.createIframe();
  }

  hasDuplicates = async () => {
    const check = await this.isDuplicateFoundOnFirst();

    return check;
  }

isDuplicateFoundOnFirst = () => {
    // do some stuff here
  }

createIframe = () => {
 // do something here
}
}

export const duplicateChecker = new DuplicateChecker();
```

and this is the error i am receiving upon building the application as it runs on dev without any problems:

```
 Cannot convert non-arrow function to a function expression.
  14 |   }
  15 |
> 16 |   hasDuplicates = async () => {
     |                      ^
  17 |     const checkFirstPage = await this.isDuplicateFoundOnFirst();
  18 |
```

**Expected behavior**
The app builds and compiles any code using babel without any issues.

**Comment by rschristian** [comment]
Have you messed around with the babel config through your `.babelrc` or `preact.config.js`? I believe this should otherwise be working.

**Comment by developit** [comment]
Yes, I'm thinking this would have to be a result of a customized Babel config. Here's what Preact CLI's babel configuration should be doing with the above code sample:

[view on Babel REPL](https://babeljs.io/repl#?browsers=Edge%3E%3D16%2CSafari%3E%3D10.1%2CChrome%3E%3D61%2CFirefox%3E%3D60&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEAiCuAHEBLYYAuBTAwgCy2AGssAnaAbwChppgB7AOwg1PmA3tIAoBKSmrWgY8KCADoUAM1JgAtlmgBeYaInBSWTFgCSM-Vj4BuQQF8qgvJATI02mCsgBPRsGh9lAPgFC6TFnQExMrQYADuYCgYqmKSEDao6NgAYvTwjAAmAPKMySikLMYWvpoY8KSMgYREJrTmVGIJdilpmTl5BdEqHkre1L4A9APQGfTQEPQK42VSUtAEmmYWGlrYerJT3fy9PkMjYxMKIiiMAObzZFhU5vVYAB6IXNEMzNEZSIna-NVkIYxYYTgH2auCCJB4vCMQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%22noClassCalls%22%3Atrue%2C%22noNewArrows%22%3Atrue%2C%22noDocumentAll%22%3Atrue%2C%22mutableTemplateObject%22%3Atrue%2C%22iterableIsArray%22%3Atrue%2C%22ignoreToPrimitiveHint%22%3Atrue%2C%22ignoreFunctionLength%22%3Atrue%2C%22enumerableModuleMeta%22%3Atrue%2C%22constantSuper%22%3Atrue%2C%22constantReexports%22%3Atrue%2C%22privateFieldsAsProperties%22%3Atrue%2C%22objectRestNoSymbols%22%3Atrue%2C%22setClassMethods%22%3Atrue%2C%22setComputedProperties%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%2C%22setSpreadProperties%22%3Atrue%2C%22skipForOfIteratorClosing%22%3Atrue%2C%22superIsCallableConstructor%22%3Atrue%7D)

**Comment by rschristian** [comment]
So I ran into [this StackOverflow question](https://stackoverflow.com/questions/70271329/cannot-convert-non-arrow-function-to-a-function-expression-react-preact-build-f/70271685#70271685) which seems to match your question here, and I see you've provided your `.babelrc`.

I'm not entirely sure that the `.babelrc` pickup is working as intentioned at the moment, even a plain `{ "presets": ["preact-cli/babel"] }` runs into this issue. AFAIK that should be fine, will need to look into that more.

Regardless, you're adding a couple redundant plugins and you can add the ones you actually need through your preact config file:

preact.config.js
```js
export default (config, env, helpers) => {
    const { rule } = helpers.getLoadersByName(config, 'babel')[0];
    const babelConfig = rule.options;

    babelConfig.plugins.push(
        '@quickbaseoss/babel-plugin-styled-components-css-namespace',
        'babel-plugin-styled-components'
    );
}
```

**Comment by devlukasz** [comment]
So my **.babelrc** looks as following:

```
{
    "presets": [
        "preact-cli/babel"
    ],
    "plugins": [
        "@quickbaseoss/babel-plugin-styled-components-css-namespace",
        "babel-plugin-styled-components"
    ]
}
```

Would any of these change the outcome?? or as suggested should i just add them onto the preact.config.js?

**Comment by devlukasz** [comment]
This seems to be working! thank you so much!

**Comment by rschristian** [comment]
Upon further inspection, it doesn't look like there is any issue with the `.babelrc` handling. Our docs do say that it's use is only for overwriting part of the config, not modification.

As for why `{ "presets": ["preact-cli/babel"] }` is not functional, I have no clue, but we hand that off to `babel-loader` in, as far as I can tell, the correct state. I don't think there's anything actionable for us here.
