### ISSUE TITLE
Can't install webpack plugin (webpack version collision)

### ISSUE THREAD

**Issue by caxapexac** [preactjs/preact-cli#1629]
**What is the current behaviour?**
Seems like colliding of webpack versions

https://stackoverflow.com/a/68386322/9398364 didn't help

**Steps to Reproduce**
1. `npx preact-cli create simple project`
2. `cd project`
3. `npm run build` - just to check, everything works
4. `npm i -D html-webpack-plugin`
5. `npm run build`

> project@0.0.0 build
> preact build

× ERROR TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (project\node_modules\webpack\lib\NormalModule.js:207:10)
    at project\node_modules\mini-css-extract-plugin\dist\index.js:394:103
    at project\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:15:1)
    at project\node_modules\tapable\lib\Hook.js:154:20)
    at project\node_modules\preact-cli\node_modules\webpack\lib\Compiler.js:631:26)
    at project\node_modules\preact-cli\node_modules\webpack\lib\Compiler.js:667:29
    at project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at project\node_modules\tapable\lib\Hook.js:154:20)
    at project\node_modules\preact-cli\node_modules\webpack\lib\Compiler.js:662:28)
    at project\node_modules\preact-cli\node_modules\webpack\lib\Compiler.js:321:11
    at Compiler.readRecords (project\node_modules\preact-cli\node_modules\webpack\lib\Compiler.js:529:11)
    at project\node_modules\preact-cli\node_modules\webpack\lib\Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (project\node_modules\tapable\lib\Hook.js:154:20)
    at project\node_modules\preact-cli\node_modules\webpack\lib\Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)

Environment Info:
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.53)
  npmPackages:
    preact: ^10.1.0 => 10.6.4
    preact-cli: ^3.0.0 => 3.3.2
    preact-render-to-string: ^5.1.2 => 5.1.19

**Comment by rschristian** [comment]
Why are you adding `html-webpack-plugin`? v3 is already a dependency of ours.

**Comment by caxapexac** [comment]
Oh I see, thanks
I've just tried to make single html like in #923, any thought on how can this be done?

**Comment by rschristian** [comment]
You can use your [`preact.config.js`](https://github.com/preactjs/preact-cli#webpack) file to customize existing plugins, but honestly it sounds like you're using the wrong tool for the job. Preact-CLI is for making progressive web applications. While you could do a fair bit of work and stitch the output into what you're looking for, it'd be a bit of scripting and way heavier than you need.

Something like [`htm`](https://github.com/developit/htm) sounds more along the lines of what you're looking for. Super minimal, and you can easily run in through terser or whatever afterwards to minimize.
