### ISSUE TITLE
template.html broken on build and dev (broken differently)

### ISSUE THREAD

**Issue by caxapexac** [preactjs/preact-cli#1632]
**What is the current behaviour?**
template.html:
```html
        <body>
		<div>div to sacrifice</div>
		<div>some stuff</div>
		<div>
			<% preact.bodyEnd %>
		</div>
		<div>more stuff</div>
	</body>
```

## Dev
![image](https://user-images.githubusercontent.com/33996246/146511947-aeddcc18-76c7-49a1-9d78-f3741766cd83.png)
![image](https://user-images.githubusercontent.com/33996246/146512049-5fe61443-190e-4c9b-80ac-5e62892af674.png)
As you can see the first div disappeared

## Build
Here really strange things happens
build/index.html:
![image](https://user-images.githubusercontent.com/33996246/146512229-efc7b9a9-5ecd-42e1-97fc-421cae61c361.png)
**But serving:**
![image](https://user-images.githubusercontent.com/33996246/146512283-065b1711-df42-4e31-907e-cdc0c58b9d6f.png)
![image](https://user-images.githubusercontent.com/33996246/146512315-88208290-fe6e-4dd5-8ece-5dcf54eb52e6.png)

**What is the expected behaviour?**
Something like `<% preact.bodyRoot %>` to use as second argument in render() function

Or at least adding root element instead of replacing existing stuff

Where to store my non-preact dom tree right now?

**Comment by rschristian** [comment]
See: https://github.com/preactjs/preact-cli/issues/1259#issuecomment-653758149

**Comment by caxapexac** [comment]
Oh I see
