### ISSUE TITLE
Preact build has repeated bundles.

### ISSUE THREAD

**Issue by grazianobolla** [preactjs/preact-cli#1642]
**Describe the bug**
Preact build using npm run build has 2 bundles that are the same 

**To Reproduce**
create a default preact project with preact-cli and build with --analyze
![Screenshot from 2022-01-21 19-24-49](https://user-images.githubusercontent.com/35064738/150608661-deb3fe32-10e1-419e-bfde-7b3ab7bc610f.png)

**Comment by rschristian** [comment]
They're not the same, as one is ESM and the other is not. ESM is preferred, but not all browsers/versions can handle it, so we output two bundles. Only one is ever used, this isn't an actual duplication when it comes to use.

You can try this yourself, using the `serve` command (`sirv build --port 8080 --cors --single`) all the templates ship with. You'll see that you only request 1, which will in all likelihood be the ESM.

You can disable this if you'd like with the `--esm` flag, i.e., `preact build ... --no-esm`.
