### ISSUE TITLE
Support for devServer.client.webSocketURL

### ISSUE THREAD

**Issue by syncjuncture** [preactjs/preact-cli#1650]
```js
export default (config, env, helpers) => {
  if (!env.isProd) {
    config.devServer.client = {
      webSocketURL: "ws://localhost:PORT/ws",
    };
  }
};
```

Reference: [<https://webpack.js.org/configuration/dev-server/>](https://webpack.js.org/configuration/dev-server/#websocketurl)

**Comment by rschristian** [comment]
You're referencing the wrong version of the docs. That's v4, while the latest release of `preact-cli` is on v3.

That being said, we actually just landed support for v4 in #1646, though it has not yet been released.
