### ISSUE TITLE
GLOB-PARENT <5.1.2 REGULAR EXPRESSION DENIAL OF SERVICE

### ISSUE THREAD

**Issue by TbirdDuncan** [preactjs/preact-cli#1651]
From npm audit:
glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install preact-cli@2.2.1, which is a breaking change
node_modules/watchpack-chokidar2/node_modules/glob-parent
node_modules/webpack-dev-server/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/watchpack-chokidar2/node_modules/chokidar
  node_modules/webpack-dev-server/node_modules/chokidar
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/watchpack
        webpack  4.44.0 - 4.46.0
        Depends on vulnerable versions of watchpack
        node_modules/webpack
    webpack-dev-server  2.0.0-beta - 4.7.2
    Depends on vulnerable versions of chokidar
    Depends on vulnerable versions of selfsigned
    Depends on vulnerable versions of yargs
    node_modules/webpack-dev-server
      preact-cli  >=1.0.0
      Depends on vulnerable versions of critters-webpack-plugin
      Depends on vulnerable versions of webpack-dev-server
      node_modules/preact-cli

**Comment by rschristian** [comment]
`glob-parent` is used at build time only (look at your lock file to see what depends on it). If you write some really wonky file regexes _maybe_ you can cause an issue in your build pipeline, but that's the extent of the issue. It's not a real vulnerability.

https://overreacted.io/npm-audit-broken-by-design/
