### ISSUE TITLE
Uncaught TypeError: bind

### ISSUE THREAD

**Issue by TbirdDuncan** [preactjs/preact-cli#1652]
Created an app from preact-cli using standard template and then made an app. npm run dev causes the following

>Uncaught TypeError: Cannot read properties of undefined (reading 'bind')
   at eval (main.js?e0e7:11:1)
    at Object.../node_modules/preact-dom/main.js (bundle.js:1514:1)
    at __webpack_require__ (bundle.js:790:30)
    at fn (bundle.js:101:20)
    at eval (index.js?41f5:1:1)
    at Module../index.js (bundle.js:2597:1)
    at __webpack_require__ (bundle.js:790:30)
    at fn (bundle.js:101:20)
    at eval (entry.js?99dc:31:1)
    at Module.../node_modules/preact-cli/lib/lib/entry.js (bundle.js:1503:1)

**Comment by rschristian** [comment]
> and then made an app

What does this mean?

I see `preact-dom` in the error message which doesn't make much sense and certainly isn't from our template.

**Comment by TbirdDuncan** [comment]
Sorry, I copied some code over from a prexisting app. This is my 2nd attempt to make it work. First attempt was made through trying to update aliases using webpack as described in preact docs.

**Comment by rschristian** [comment]
The docs say you don't need to alias if you're using `preact-cli`. We handle that for you.

**Comment by TbirdDuncan** [comment]
For updating an existing react app with preact?

**Comment by TbirdDuncan** [comment]
This attempt was initialized using npx preact-cli standard <name>, and then I tried to translate some of the react code to preact 🤷‍♂️

**Comment by TbirdDuncan** [comment]
Heres a packakgejson dependency: 
>  "dependencies": {
    "axios": "^0.25.0",
    "preact": "^10.1.0",
    "preact-cli": "^3.3.3",
    "preact-dom": "^1.0.1",
    "preact-render-to-string": "^5.1.2",
    "react-redux": "^7.2.6",
    "redux-saga": "^1.1.3",
    "@reduxjs/toolkit": "^1.6.2",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10"
  }

**Comment by rschristian** [comment]
No document of ours ever says to use `preact-dom` intentionally. Can you link to whatever is saying this? It's a typo if it does exist.

I also don't think you're reading the docs correctly?

As you'll see, under [Integrating Into An Existing Pipeline](https://preactjs.com/guide/v10/getting-started#integrating-into-an-existing-pipeline), 

> **If you already have an existing tooling pipeline set up**

If you're migrating to `preact-cli` then you're not integrating into an existing pipeline. You're migrating.

**Comment by TbirdDuncan** [comment]
correct trying to migrate on this attempt rather than integrate. So maybe I'm missing some documentation on what the cli watch/build actually does with the src folder. If I have a index js file, do I just need to export?

**Comment by rschristian** [comment]
Yes, this tool handles all the configuration for you (though you can customize any piece if you wish).

[As the templates do, just re-export your main component from `src/index.js`](https://github.com/preactjs-templates/default/blob/master/template/src/index.js)

**Comment by TbirdDuncan** [comment]
Ok so I ended up fixing that issue, thank you. However it appears that react-redux causes issues, I found some old comments on the github for react-redux where they say they use a react-redux/compat shim but that folder is no longer in the repo. Provider from react redux is using react :(

**Comment by TbirdDuncan** [comment]
>Uncaught TypeError: Cannot read properties of undefined (reading 'getState')
    at eval (Provider.js?273f:20:1)
    at d (index.js?a178:213:1)
    at _.Provider [as constructor] (Provider.js?273f:19:1)
    at _.O [as render] (index.js?c988:514:1)
    at j (index.js?c988:171:1)
    at w (children.js?b0ec:137:1)
    at j (index.js?c988:171:1)
    at w (children.js?b0ec:137:1)
    at j (index.js?c988:171:1)
    at S (render.js?50ff:16:1)
eval @ Provider.js?273f:20
d @ index.js?a178:213
Provider @ Provider.js?273f:19
O @ index.js?c988:514
j @ index.js?c988:171
w @ children.js?b0ec:137
j @ index.js?c988:171
w @ children.js?b0ec:137
j @ index.js?c988:171
S @ render.js?50ff:16
init @ entry.js?99dc:60
eval @ entry.js?99dc:65
../node_modules/preact-cli/lib/lib/entry.js @ bundle.js:1503
__webpack_require__ @ bundle.js:790
fn @ bundle.js:101
0 @ bundle.js:2455
__webpack_require__ @ bundle.js:790
(anonymous) @ bundle.js:857
(anonymous) @ bundle.js:860

**Comment by rschristian** [comment]
Can you provide a reproduction? Really not giving me much to go on.

**Comment by TbirdDuncan** [comment]
At the moment no, I can possibly get a repo set up for people to check out later. If there's something specific however I can likely supply thatsupply that. 

```
import { Provider } from "react-redux";
const store = configureStore({});
console.log(store);
// const store = createStore()

function App() {
    return (
      <Provider>
        {/* <React.StrictMode> */}
          <div className="App">
            <header className="App-header">
              {/* <img src={logo} className="App-logo" alt="logo" /> */}
              <p>well would you look at that</p>
              <SliceAdder />
              <Counter />
              <Login />
              <Table />
            </header>
          </div>
        {/* </React.StrictMode> */}
      </Provider>
    );
}

export default App;

**Comment by rschristian** [comment]
`react-redux` should work right out of the box with `preact-cli`.

**Comment by TbirdDuncan** [comment]
thats what I thought as well :)

**Comment by TbirdDuncan** [comment]
I did not supply store woops

**Comment by rschristian** [comment]
I don't think you've added a store? That's most likely your issue.

**Comment by rschristian** [comment]
I'm going to close this out, but feel free to ping me if you ever run into an issue with anything. Happy to help if I can.
