### ISSUE TITLE
Using sass generates error: TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by ifexception** [preactjs/preact-cli#1668]
**What is the current behaviour?**
> TypeError: this.getOptions is not a function
Trying to use `sass` in the default project generated by preact-cli, but I keep getting this error.

**Steps to Reproduce**

1. Create default project
2. Then run: `npm install node-sass sass-loader bulma rxjs formik yup`
3. Rename all `style.css` files to `style.scss` in _routes/_ and _components/_
4. In _src/style/index.scss_ paste:
```@charset "utf-8";

$family-sans-serif: "Consolas", sans-serif;

$beige-lighter: #EFF0EB;

$primary: $purple;
$link: $pink;

$body-background-color: $beige-lighter;

@import "../../node_modules/bulma/sass/utilities/_all.sass";
@import "../../node_modules/bulma/sass/base/_all.sass";
@import "../../node_modules/bulma/sass/elements/button.sass";
@import "../../node_modules/bulma/sass/elements/container.sass";
@import "../../node_modules/bulma/sass/elements/title.sass";
@import "../../node_modules/bulma/sass/form/_all.sass";
@import "../../node_modules/bulma/sass/components/navbar.sass";
@import "../../node_modules/bulma/sass/layout/hero.sass";
@import "../../node_modules/bulma/sass/layout/section.sass";
```

5. Run `npm run dev`

Error:

```
ERROR in ./components/header/style.scss (../node_modules/css-loader/dist/cjs.js??ref--8-1!../node_modules/postcss-loader/dist/cjs.js??ref--8-2!../node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--6-0!./components/header/style.scss)
Module build failed (from ../node_modules/preact-cli/lib/lib/webpack/proxy-loader.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\Development\csharp-dev\Haros\src\Haros.WebApi\ClientApp\haros-app\node_modules\sass-loader\dist\index.js:27:24)
    at Object.proxyLoader (C:\Development\csharp-dev\Haros\src\Haros.WebApi\ClientApp\haros-app\node_modules\preact-cli\lib\lib\webpack\proxy-loader.js:28:32)
```

The error is repeated for each *.scss file in the _routes/_ and _components/_ directories

**What is the expected behaviour?**
According to what I read here: https://github.com/preactjs/preact-cli/issues/443 . This should work out of box. Did I miss anything? Can anyone please assist me? 

`src/index.js`:
```
import './style';
import App from './components/app';

export default App;
```

Please paste the results of `npx preact-cli info` here.
> npx: installed 1535 in 369.852s
Environment Info:
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (91.0.864.67)
  npmPackages:
    preact: ^10.3.2 => 10.6.6
    preact-cli: ^3.0.0 => 3.3.5
    preact-render-to-string: ^5.1.4 => 5.1.20
    preact-router: ^3.2.1 => 3.2.1

**Comment by rschristian** [comment]
You have added the latest version of `sass-loader`, which isn't compatible with Webpack 4. You'll need to use an older version as we show in the docs.

https://github.com/preactjs/preact-cli#sass

**Comment by ifexception** [comment]
Apologies, that was my bad. Googling this issue led me to this site: https://nicedoc.io/preactjs/preact-cli#user-content-sass which I've never encountered before and I figure it is out of date so I didn't specify a version when install `node-sass` and `sass-loader`. 
Thank you for your help!

**Comment by rschristian** [comment]
No worries, it's easy to miss.

I think that site just copies GitHub project READMEs, with the idea that it can style them and make them nicer to read. It's the exact same as ours.
