### ISSUE TITLE
Support building TypeScript with the --build flag

### ISSUE THREAD

**Issue by sjmarshy** [preactjs/preact-cli#1673]
**What is the current behaviour?**

When building an application with local libraries in typescript, such as in a yarn workspace, there is no way to ask the preact-cli application to also build the libraries it depends on. Currently, you have to set up secondary build watchers. This gets both tedious and a little expensive if you have multiple libraries that the application depends on. 

**What is the motivation or use case for changing this behaviour?**

To enable those using preact-cli with TypeScript and building with local TypeScript libraries to have a single incremental build process. 

**Describe the solution you'd like**

Expose some config to enable dev builds of TypeScript preact-cli projects to use the `tsc --build` flag. 

Environment Info:
  System:
    OS: macOS 12.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 14.19.0 - ~/.volta/tools/image/node/14.19.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 6.14.16 - ~/.volta/tools/image/node/14.19.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 98.0
    Safari: 15.2

**Comment by rschristian** [comment]
Closing as I don't think this would ever be something that'd we'd implement. Would be a huge expansion of the scope and difficult to do right, as mentioned above.
