### ISSUE TITLE
Trusted Types

### ISSUE THREAD

**Issue by tinganho** [preactjs/preact-cli#1676]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Not sure if you have support for CSP:s trusted types, but I get an error when I try to add trusted types. And there seems to be no docs on trusted types.
```
Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
```
**To Reproduce**

1. Go to https://codesandbox.io/s/loving-haibt-79bkcf

**Expected behavior**
What should have happened when following the steps above?

**Comment by rschristian** [comment]
Loading it up outside of code sandbox shows it's Webpack itself. Have you looked into the [Webpack config for enabling support](https://webpack.js.org/configuration/output/#outputtrustedtypes)?

Looks like this will need to be something you enable yourself through your `preact.config.js`.

**Comment by tinganho** [comment]
>Loading it up outside of code sandbox shows it's Webpack itself. Have you looked into the [Webpack config for enabling support](https://webpack.js.org/configuration/output/#outputtrustedtypes)?

Yes, I've done this. Though in my app, I got the error originating from a file called preact.mjs
![image](https://user-images.githubusercontent.com/1324476/158962288-4d6e9fce-25fe-4d55-b1b6-55cb55e935c9.png)

 I will do some more digging

**Comment by rschristian** [comment]
Can you provide a reproduction with whatever additional Webpack config you've done?

**Comment by tinganho** [comment]
Yes, I can try to create a reproducible.

**Comment by tinganho** [comment]
Nevermind, I missed to pass the correct trust policy in dangerousleSetInnerHtml. It's working as expected now.
