### ISSUE TITLE
Make hot reload show the error when build fails

### ISSUE THREAD

**Issue by alexander-entin** [preactjs/preact-cli#1678]
**What is the current behaviour?**
When dev server is unable to compile changed source files it show an error message in the console.
But the app in the browser continues running w/o the change made.

**What is the motivation or use case for changing this behaviour?**
It could take time to find out that the cause of the change not propagated is just a syntax error.

**Describe the solution you'd like**
Show the error in the browser too. Or a blank page. Or any indication that a build error has happened.

**Please mention any other relevant information.**
Could react-error-overlay be used?

Please paste the results of `npx preact-cli info` here.
Environment Info:
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.19.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.36)

**Comment by rschristian** [comment]
You can enable this yourself with your config:

```js
// preact.config.js
export default (config) => {
    config.devServer.overlay = true;
}
```

This was set long before I came into the project, maybe we can look at changing the defaults to this. Not sure how people feel.

**Comment by rschristian** [comment]
Closing as this is solved with the config above and is just preference.

**Comment by rschristian** [comment]
> displaying either a 500 error

Honestly I'm not sure how you'd go about displaying a 500 error when the build fails. Maybe you could hook into `webpack-dev-server`? No idea, never heard of such a thing being possible.

In case I was unclear, the issue you're having isn't with Preact-CLI, but with Webpack. As a Webpack-based tool, there's not a whole lot we can do in that situation.

> or an error overlay for build failures would indeed resolve a common counter-intuitive issue, rather than being a question of preference.

Enabling the error overlay is preference. Personally, I find them to be quite annoying. My terminal is perfectly capable of presenting errors to me at a glance. I don't need the bundler hijacking the browser content too.

As enabling this in a user config is just 3 lines of copy/paste (2 of which are standard boilerplate), I don't see a need for us to alter the config re:overlay at this time.

I'll consider it for the next major, but at this time, I think it'll be an unlikely change.
