### ISSUE TITLE
Style tags removed in production build

### ISSUE THREAD

**Issue by chinchang** [preactjs/preact-cli#1681]
**What is the current behaviour?**
If you have a custom index.html template and that has a `style` tag inside it, the index.html created in production build doesn't have the `script` tag anymore.

**Steps to Reproduce**

1. Create a custom `index.html`, copied from preact-cli's index.html itself
2. put in a `style` tag in the `head`
3. Build using `npm run build`
4. The built `index.html` doesn't have the `style` tag.

**What is the expected behaviour?**
`style` tag should have been there in the built `index.html`

**Please mention any other relevant information**

Environment Info:
  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Edge: 99.0.1150.52
    Firefox: 97.0.2
    Safari: 15.2
  npmPackages:
    preact: ^10.3.2 => 10.6.6
    preact-cli: ^3.0.0 => 3.3.5
    preact-render-to-string: ^5.1.4 => 5.1.20
    preact-router: ^3.2.1 => 3.2.1

**Comment by rschristian** [comment]
Please provide the actual HTML file you're using.

We don't ship with a `index.html`, but a `template.html`. If you've renamed this file, have you adjusted the path using the `--template` flag?

**Comment by chinchang** [comment]
Oh yes. I copied `template.html` into my own `index.html`. And added a `style` tag inside it.
I found the reason though - https://stackoverflow.com/questions/69959478/how-to-keep-the-style-tag-from-template-html-when-using-preact-build

Its the `critters` plugin at work. Which can be disabled through `--no-inline-css` flag :)

**Comment by rschristian** [comment]
Sounds like this is resolved then.
