### ISSUE TITLE
Unable to read file: /node_modules/form-data/lib/browser.js

### ISSUE THREAD

**Issue by philosofonusus** [preactjs/preact-cli#1682]
**What is the current behaviour?**
![Screenshot from 2022-04-08 20-36-12](https://user-images.githubusercontent.com/32138582/162493227-de72df6e-9bb7-4de8-b2d7-7fec3156e1c9.png)

**Steps to Reproduce**

1. npm run build 

**What is the expected behaviour?**
creation of production build

**Please mention any other relevant information**
  System:
    OS: Linux 5.8 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 AMD Ryzen 9 4900HS with Radeon Graphics
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    npm: 8.4.0 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 87.0
  npmPackages:
    preact: ^10.3.1 => 10.6.6 
    preact-cli: ^3.0.0 => 3.3.5 
    preact-render-to-string: ^5.1.4 => 5.1.20 
  npmGlobalPackages:
    preact-cli: 3.3.5

**Comment by rschristian** [comment]
https://github.com/preactjs/preact-cli#pre-rendering

**Comment by philosofonusus** [comment]
> https://github.com/preactjs/preact-cli#pre-rendering

1. The code is wrapped with if(typeof window !== "undefined") {
2. have tried preact build --no-prerender

**Comment by rschristian** [comment]
You've provided no bug description and no reproduction, just a screenshot of the resulting error message; I cannot do anything more than point you at the docs if you don't fill in our issue template and don't provide the necessary information.

Wrapping your entire app in a window check is essentially the same thing as `--no-prerender`. You only need to wrap whatever's causing the issue (whatever uses `form-data`).

Side note: While it shouldn't ever be an issue, you don't need to render your root component; whatever you `default export` from your `index.ts` file will be picked up & automatically rendered by `preact-cli` for you, see [TypeScript template entry](https://github.com/preactjs-templates/typescript/blob/5cdcd071da53299e71b118362f52d8f10e9fa8ee/template/src/index.ts#L4)

**Comment by rschristian** [comment]
I'm going to close this out as no reproduction has been provided to indicate it's a problem in `preact-cli`.
