### ISSUE TITLE
Issue using imported Objects outside the component

### ISSUE THREAD

**Issue by ayushkhanduri** [preactjs/preact-cli#1723]
**What is the current behaviour?**
Async import loading issue with Preact, I am not sure if it is a bug or not but i was told to create a ticket @rschristian 

**Steps to Reproduce**
This stackoverflow ticket explains the whole issue
https://stackoverflow.com/questions/73197376/async-import-loading-issue-with-preact

`npx preact-cli info` :

Environment Info:
  System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.4
  npmPackages:
    preact: ^10.6.2 => 10.10.0 
    preact-cli: ^3.3.2 => 3.4.1 
    preact-render-to-string: ^5.1.19 => 5.2.1 
    preact-router: ^3.2.1 => 3.2.1

**Comment by rschristian** [comment]
As I asked for on your post, I need a minimal reproduction.

The SO post shows very, very little.

**Comment by ayushkhanduri** [comment]
@rschristian I was trying to create a sandbox but turns out it was an issue with the code , the way modules were loading , causing the component to load first and the constants to load after causing that issue . Apologies for taking your time . I will close this.

**Comment by rschristian** [comment]
No worries, that's what an issue tracker is here for!

Certainly feel free to open issues/discussions if you do run into trouble, happy to help.
