### ISSUE TITLE
Remove ssr-build from build output

### ISSUE THREAD

**Issue by SvizelPritula** [preactjs/preact-cli#1739]
**What is the current behaviour?**
The `preact build` script currently creates a directory in `build/` called `ssr-build/` that isn't needed for deployment.

**What is the motivation or use case for changing this behaviour?**
This folder shouldn't be part of a deployment.

**Describe the solution you'd like**
The SSR build could be deleted after the build finishes, or built to a different directory.

**Please mention any other relevant information.**

Environment Info:
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
  npmPackages:
    preact: ^10.1.0 => 10.11.0 
    preact-cli: ^3.0.0 => 3.4.1 
    preact-render-to-string: ^5.1.2 => 5.2.4

**Comment by rschristian** [comment]
Isn't _necessarily_ needed.

It's the output from the server build, used for prerendering. Some users do use this for SSR, so we cannot just delete it, nor do I think it makes sense to output to another directory as it does need to be cleared before a rebuild.
