### ISSUE TITLE
preact-cli create error

### ISSUE THREAD

**Issue by taylinlarge** [preactjs/preact-cli#1740]
When running the command `npx preact-cli create default my-project` it returns `Unexpected token {` and nothing is created.

**Comment by rschristian** [comment]
Odd, I'm unable to reproduce and neither is our test suite.

Have you installed and older version of `preact-cli` globally perhaps?

**Comment by taylinlarge** [comment]
Just realized I was on the wrong version of Node.

**Comment by rschristian** [comment]
Still odd. What version were you using?

We're meant to be throwing errors if you're using too old of a version, unless our detection is failing.

**Comment by taylinlarge** [comment]
I was using node v8.17.0

**Comment by rschristian** [comment]
Ah, so old it might've failed to parse. That makes more sense. Can't do much about that unfortunately.

Glad you have it working now though!
