### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cwd'). - Jest widget-ts template

### ISSUE THREAD

**Issue by HelloItsDev** [preactjs/preact-cli#1746]
**What is the current behaviour?**
In index.test.tsx I've got a TS error : `'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)`
 
And when launching the test this error happen:

```
TypeError: Cannot read properties of undefined (reading 'cwd')

      at Object.getCacheKey (node_modules/babel-jest/build/index.js:299:33)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:256:23)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:290:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:429:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

**Steps to Reproduce**
Fresh install of the widget typescript template.

**What is the expected behaviour?**
Test run normally

**Please mention any other relevant information**
I've tried to import react, which resolve the TS error but not the error in babel jest 

```
System:
   OS: Windows 10 10.0.22000
   CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
 Binaries:
   Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
   Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
   npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
 Browsers:
   Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.47)
 npmPackages:
   preact: 10.5.7 => 10.5.7
   preact-cli: 3.0.5 => 3.0.5
   preact-render-to-string: ^5.1.11 => 5.2.5`
```

**Comment by rschristian** [comment]
> In index.test.tsx I've got a TS error : 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)

That's an issue with your editor. It's unaware that you're not using React, and therefore your JSX doesn't transform to `React.createElement(...)` calls. What editor are you using? I recall JetBrains' stuff having this issue, though the only choice is to ignore that (incorrect) warning.

> And when launching the test this error happen:

Upgrade Jest to `^27`.

**Comment by HelloItsDev** [comment]
Hi Christian, thanks for the quick response.
I'm using vscode. 
Upgrading to jest^27 did the tricks, tests are running fine now.
Thanks a bunch

**Comment by rschristian** [comment]
Ryan, actually, but glad that's working for you.

Closing this out, how to set up your editor to work with other JSX pragmas isn't really an issue for CLI.

Not a VSCode user myself, so can't really give advice there. Could maybe try the [Slack](https://chat.preactjs.com/)? Someone there might have a better idea.
