### ISSUE TITLE
compiling✖ ERROR Error: Babel-loader config not found!!!

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [preactjs/preact-cli#1751]
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
While trying to run npm run build I am getting the error below

 Build  [                    ] 0% (0.0s) compiling✖ ERROR Error: Babel-loader config not found!!!

**To Reproduce**
Install  "preact-i18nline": "^2.0.0" and follow the doc to add configs within preact.config.js as below

```js
export default (config, env, helpers) => {
	// Use Preact CLI's helpers object to get the babel-loader
	let babel = helpers.getLoadersByName(config, 'babel-loader')[0].rule;
	// Update the loader config to include preact-i18nline
	babel.loader = [
		{ // create an entry for the old loader
			loader: babel.loader,
			options: babel.options
		},
		{ // add the preact-i18nline webpack loader
			loader: 'preact-i18nline/webpack-loader'
		}
	];
	// remove the old loader options
	delete babel.options;
};
```

then run command `npm run build`

Versions

 "i18nline": "^2.0.1",
  "preact": "^10.3.2",
  "preact-i18nline": "^2.0.0",
   "preact-cli": "^3.0.0",

**Comment by rschristian** [comment]
That plugin, and by extension its docs, is many years out-of-date. That's no longer the Webpack interface. Try this instead:

```js
export default (config, env, helpers) => {
    let babel = helpers.getLoadersByName(config, 'babel-loader')[0].rule;
    // Update the loader config to include preact-i18nline
    babel.use = [
        { // create an entry for the old loader
            loader: babel.loader,
            options: babel.options
        },
        { // add the preact-i18nline webpack loader
            loader: 'preact-i18nline/webpack-loader'
        }
    ];
    // remove the old loader options
    delete babel.loader;
    delete babel.options;
}
```

Note: When `preact-cli` v3.4.2 is published, you'll need to alter this config to the following:

```js
export default (config, env, helpers) => {
    let babel = helpers.getLoadersByName(config, 'babel-loader')[0].rule;
    // add the preact-i18nline webpack loader
    babel.use.push({ loader: 'preact-i18nline/webpack-loader' });
}
```

**Comment by Bakhtiyar-Garashov** [comment]
Hey @rschristian  thank you for your answer. Adding this config fixes the previous issue. However this time I get error below:


` Build  [=================== ] 95% (7.1s) emittingUnable to read file: /Users/bakhtiyar/Desktop/huum-auth-spa/src/node_modules/ulog/browser.js

TypeError: Cannot read properties of null (reading 'substring')
method: S8e/

Stack:

{
    "fileName": "/Users/bakhtiyar/Desktop/huum-auth-spa/build/ssr-build/ssr-bundle.js",
    "lineNumber": 1,
    "functionName": "Object.S8e/",
    "typeName": "Object",
    "methodName": "S8e/",
    "columnNumber": 43079,
    "native": false
}
This could be caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: "if (typeof window !== "undefined") { ... }"

Alternatively use "preact build --no-prerender" to disable prerendering.

See https://github.com/preactjs/preact-cli#pre-rendering for further information.
`

Using `preact build --no-prerender` fixes the problem, however translation doesn't work at all after this. 

I insist on using this library because couldn't find any other option for i18n. If you have any other recommendation I would be glad to hear. Thanks

**Comment by rschristian** [comment]
Can you provide a reproduction?

The error is quite clear; one of your libraries are trying to use browser globals in Node, which isn't going to work. You'll need to wrap with window checks or drop out from prerendering.

Not prerendering won't break anything. You have done other problem if things aren't working.

**Comment by Bakhtiyar-Garashov** [comment]
Thanks for quick answer:

Reproduction steps:

1. In a project install ` "preact-i18nline": "^2.0.0",` via `"preact-cli": "^3.0.0",`
2. Setup preact.config.js with code below

export default (config, env, helpers) => {
    let babel = helpers.getLoadersByName(config, 'babel-loader')[0].rule;
    // Update the loader config to include preact-i18nline
    babel.use = [
        { // create an entry for the old loader
            loader: babel.loader,
            options: babel.options
        },
        { // add the preact-i18nline webpack loader
            loader: 'preact-i18nline/webpack-loader'
        }
    ];
    // remove the old loader options
    delete babel.loader;
    delete babel.options;
}

3. Run `"build": "preact build"`

Patching location in case of global window object undefined didn't help unfortunately.

**Comment by rschristian** [comment]
Sorry, but that on its own won't reproduce the issue. Was getting fine builds yesterday when I gave you that config. It likely has to do with your use of `preact-i18nline`?

Please make it something that I can just clone & run.

**Comment by Bakhtiyar-Garashov** [comment]
Thank you a lot for your time. I appreciate it. Removing node_modules folder, package-lock.json and reinstalling npm fixed my problem.

**Comment by rschristian** [comment]
That sounds a bit odd to me, but if it works ¯\\\_(ツ)\_/¯

It *should* error as far as I can tell, maybe double check that you are still using the library in question? Perhaps you commented out your usage or something?
