### ISSUE TITLE
Pages duplicate when accessing with /index.html

### ISSUE THREAD

**Issue by wenzf** [preactjs/preact-cli#1755]
Versions:

"preact-cli": "^3.4.1", (standard template)
"preact": "^10.11.3",
"preact-render-to-string": "^5.1.4",
"preact-router": "^4.1.0"

I'm not sure if this is a bug or wheter it's by design. It seems an issue for use cases.

I set up the routing like this:

```
<Header />
  <Router>
    <Home path="/" />
    <Component2 path="/component2" />
    <Component3 path="/component3 />
  </Router />
<Footer />
```

The issue: When pages are accessed with `index.html`, i.e. mysite.com/index.html, the site is duplicated as soon as one navigates to a new route. Inspecting the DOM shows that both elements are present. The previous page is attached after the new one.

This can be an issue since some Projects used /index.html as entry point and many backlinks point to /index.html.

I did a rather dirty workaround to hide the duplicate element from the viewer.  The issue can be solved that way, but it's far from a elegant solution.

I'm aware that the issue could also be solved by re-directing in the backend. But that's not elegent either.

How you guys deal with that issue?

**Comment by rschristian** [comment]
I'm not quite sure how to reproduce, but it's an issue with your file serving.

In general you're going to run into issues with client-side routing (like `preact-router`) if you continue to link to `/index.html`. Is there any reason you can't link to `/` instead?

**Comment by wenzf** [comment]
>  Is there any reason you can't link to `/` instead?

I link to `/` by default, that's not an issue. My case is a bit special: I did a website for a client. Before his website was accessed with `/index.html`. So there are lot of backlinks, pointing to the `/index.html`. When people click on those links, they have a bad experience. That's my problem.

I can reproduce this problem on my development environment (hosting production build) and I experienced it in production with 2 hosting services, including AWS. My deployment is pre-rendering all URLs and deploy the project as static site.

**Comment by rschristian** [comment]
> I can reproduce this problem on my development environment (hosting production build) and I experienced it in production with 2 hosting services, including AWS.

That doesn't exactly help me reproduce your issue though is what I was getting at.

Your best bet might be to redirect. As I said, that's not going to play nicely with SPA routing. `/index.html` will not trigger your Home component in the example you gave. You'll only get the header.

**Comment by wenzf** [comment]
> That doesn't exactly help me reproduce your issue though is what I was getting at.
Sorry, I explain in more detail: Set up the routing like described above. Host in production build. Access the 'home' or any other route with `mysite.com/index.html` instead of `mysite.com`. Navigate to any other page of the same website. Scroll down to see the duplicate.

I'm aware of the redirect as a solution. My guess was that this common problem and there might be established solutions in the front end to handle this.

Nevertheless, thanks for info!

**Comment by rschristian** [comment]
> Host in production build. 

And how are you hosting this? Using `sirv`, which ships with the templates, does not display this issue.

> I'm aware of the redirect as a solution. My guess was that this common problem and there might be established solutions in the front end to handle this.

Your issue specifically is with the mutative rendering/hydration of Preact-CLI, in which it will insert elements without interrupting the existing. In this case, inserting page2 _after_ the content of page1. But there's no way to get around that, besides not prerendering

**Comment by wenzf** [comment]
> And how are you hosting this? Using `sirv`, which ships with the templates, does not display this issue.

yes, `sirv`. First i build `yarn build` then I host `yarn serve` which runs `sirv`.  But same behavior can be seen in production, i.e. on AWS. So I would be surprised if `sirv` is the reason.
 
> Your issue specifically is with the mutative rendering/hydration of Preact-CLI, in which it will insert elements without interrupting the existing. In this case, inserting page2 _after_ the content of page1. But there's no way to get around that, besides not prerendering

I just tested. Same beahviour if no pre-rendering of URLs is done.

Ok, good to know. => re-directing in the backend seems to be the best solution / work around.

> Edit: Just to be clear, you haven't removed the wrapping `<div>`, have you? Your root component should something like this:
> 
> ```js
> const App = () => (
>   <div id="app">
>     <Header />
>     <Router>
>       <Home path="/" />
>       <Component2 path="/component2" />
>       <Component3 path="/component3" />
>     </Router />
>     <Footer />
>   </div>
> );
> ```

Yes, that's how my root component looks like. The `div` is used as wrapper.

Thanks again for quick info!

**Comment by rschristian** [comment]
> yes, sirv. First i build yarn build then I host yarn serve which runs sirv. But same behavior can be seen in production, i.e. on AWS. So I would be surprised if sirv is the reason.

A misconfigured production env could be the reason which is why I was asking. If you can reproduce with `sirv` then you have something else odd going on. Please provide a repo that I can clone.

> I just tested. Same beahviour if no pre-rendering of URLs is done.

I have no idea how that'd happen. Please do provide a repo, something's definitely not right there.

**Comment by wenzf** [comment]
I can't reproduce the behaviour as well when trying to build it with a new set up. Probably there is something corrupted in my project. I think this issue can be closed. Sorry for false alarm.

**Comment by rschristian** [comment]
No worries, and if you are able to reproduce I'd be happy to reopen and investigate.

Sorry that's happening for you though, not really sure what that could be. Browser cache? Old service worker perhaps?
