### ISSUE TITLE
Homepage content loaded on all non-prerendered pages

### ISSUE THREAD

**Issue by micahjon** [preactjs/preact-cli#1779]
**What is the current behaviour?**
Whenever a non-prerendered page is loaded in the browser, it is initially loaded with the homepage's content (as part of the HTML payload). Once JavaScript loads, this content is swapped out with the correct page content. Unfortunately, this often results in a flash of incorrect content. 

**Steps to Reproduce**

1. Create a new Preact CLI project, e.g. `npx preact-cli create default prerender-issue`
2. Run `npm run build && npm run serve`
3. Open any page beside the homepage, e.g. Profile. 
4. If you view the page's source, you will find text from the homepage, e.g. "Get Started Building PWAs with Preact-CLI"

_In this case, the only pre-rendered page is the homepage, so every other page inherits it's content. In the case of `--prerenderUrls`, only non-prerendered pages inherit it's content_

**What is the expected behaviour?**
Pages that are not pre-rendered should start off blank, not with content from an unrelated page. If they must start off with pre-rendered content, then there ought to be a way to control what pre-rendered content is used (instead of it having to be the homepage).

This is especially problematic when the homepage has a unique layout or a different colored background, making the flash of incorrect content really obvious.

**Please mention any other relevant information**
It appears that this issue (or a related one) was addressed in the Webpack config--but it appears this fix is no longer working, or only applies after the service worker is installed. 
https://github.com/preactjs/preact-cli/blob/bc1231781f90f9f10fcca2466b0d0f6599f149d1/packages/cli/src/lib/webpack/render-html-plugin.js#L139

Please paste the results of `npx preact-cli info` here.
```
Environment Info:
  System:
    OS: macOS 12.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.2
  npmPackages:
    preact: ^10.11.3 => 10.11.3 
    preact-cli: ^3.4.2 => 3.4.5 
    preact-render-to-string: ^5.2.6 => 5.2.6 
    preact-router: ^3.2.1 => 3.2.1 
```

Thanks a million for your help with this!

**Comment by rschristian** [comment]
Hmm, I'm not really sure what you expect CLI to do here? We just output static files, how you serve them is mostly out of scope.

> there ought to be a way to control what pre-rendered content is used (instead of it having to be the homepage).

This is entirely up to your file server's configuration. Most file servers fallback to `/index.html`, sounds like you instead want to configure `/200.html` as your fallback.

**Comment by micahjon** [comment]
@rschristian , thanks for the quick reply!

You're absolutely right--this is simply a case of me not knowing about the `200.html` file. 

Looks like I can get the behavior I'm looking for by using Vercel rewrites. In case anyone else is running into this, here's my `vercel.json` config to avoid a flash of green homepage content on dynamic podcast-specific pages (e.g. [adblockpodcast.com/podcast/1549059398](https://www.adblockpodcast.com/podcast/1549059398)).
```json
{
  "rewrites": [
    {
      "source": "/podcast/*",
      "destination": "200.html"
    }
  ]
}
```

It turns out all my pages share a header, so I was able to get a more complete page shell rendered (without content) on dynamic pages by manually creating a blank loading route (e.g. `routes/blank-ssr-page.tsx`), pre-rendering it, and then just changing `destination` in the Vercel rewrite to `"blank-ssr-page/index.html"`, e.g.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/9473554/215676960-fa24d892-341a-401b-9f80-1b0fa6379558.png">

**Comment by rschristian** [comment]
We can definitely do with some better docs here, will add it to the list.
