### ISSUE TITLE
Exported rest param syntax functions create invalid build JS

### ISSUE THREAD

**Issue by charlier** [preactjs/preact-cli#1791]
**What is the current behaviour?**
This is with **v4.0.0-next.2**, v3 works perfectly.
If you have an exported function that uses the [rest parameter syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) `({ var1, var2, ...rest })` the built JS pollutes the window and produces clashes/failure to load chunks.

**Steps to Reproduce**
Steps to reproduce the behaviour:

1. Import/Export a function using the rest parameter syntax.  [Gist](https://gist.github.com/charlier/5afd7d55af5c927a8103414baff209f1) for a very basic example
2. Run `preact-build`
3. Notice the named parts of that function params have been added to the window as an array. If you have multiple chunks you'll end up with some errors, where it's adding multiple constants with the same identifiers, e.g.:
```
Uncaught SyntaxError: Identifier 'i' has already been declared
Uncaught (in promise) ChunkLoadError: Loading chunk failed.
```

**What is the expected behaviour?**
Clashing consts to not be added to the window.

**Please mention any other relevant information**
Plopping something like this in `preact.config.js` fixes the issue, but as far as I can see it shouldn't be needed?
```
    const { rule } = helpers.getLoadersByName(config, 'babel-loader')[0]
    const babelConfig = rule.use[0].options
    babelConfig.plugins.push(require.resolve('@babel/plugin-proposal-object-rest-spread'))
```

Using the latest Node LTS (18.16)

**Comment by rschristian** [comment]
Strange, I removed `@babel/plugin-proposal-object-rest-spread` as it should be included in `@babel/preset-env`. Will need to look into it.

**Comment by charlier** [comment]
Ahh! Sorry, I thought I had nailed the minimum repo steps.
[Here's](https://github.com/charlier/preact-rest/tree/main) an example using the default template (there's a tiny [util](https://github.com/charlier/preact-rest/blob/main/src/utils/example.js) added to both routes. Move between them & it'll throw Identifier 'e' has already been declared & ChunkLoadError errors.


On a larger application - which is automagically split out into several chunks - it breaks instantly (and the two arrays just so happen to be where rest params were used.  No idea why its attaching functions to the window).  I'll see if I can rip enough out to get some proper reproduction steps & get back.
<img width="302" alt="Screenshot of Chrome Dev Tools, displaying a ChunkLoading error" src="https://github.com/preactjs/preact-cli/assets/144476/9cd350a8-2a50-4352-b7c2-bf8c08ade38a"><img width="302" alt="Screenshot of Chrome Dev Tools, displaying a duplicate identifier error" src="https://github.com/preactjs/preact-cli/assets/144476/d35e6172-14e3-43ac-9754-2d4cb53fbfd8">

**Comment by rschristian** [comment]
No worries, I might've just gotten lucky or something and avoided collisions.

The arrays I believe are an optimize spread transform, hoisted out of the IIFE that Webpack normally generates. Bit odd, might have to check in with Jason to see if that's correct. Not entirely sure myself.

I'm guessing this is just an issue with `optimize-plugin` not using a name cache or something, creating collisions across Terser runs. Hopefully using the Babel transform works for you for now.

**Comment by rschristian** [comment]
Ended up running into this myself, definitely a product of `optimize-plugin`. Ended up ripping it out, `4.0.0-next.6` should work.
