### ISSUE TITLE
Use esbuild instead of babel

### ISSUE THREAD

**Issue by wizzard0** [preactjs/preact-cli#1803]
**What is the current behaviour?**
Babel is an obvious and robust baseline, but also it's very, very slow compared to other modern bundlers.

Preact is very fast otherwise, so the sluggishness of preact-cli compared to vite, bun etc feels even more painful

**What is the motivation or use case for changing this behaviour?**
Improve iteration time on larger projects 10-100x

**Describe the solution you'd like**
Use esbuild-loader or raw esbuild instead of babel

> Please paste the results of `npx preact-cli info` here.
N/A

**Comment by rschristian** [comment]
I think this is quite unlikely; Webpack itself is a major performance issue. Swapping out Babel (which we couldn't actually do for a multitude of reasons) wouldn't see the type of improvement that you're after.

Nothing wrong with using Vite over `preact-cli`, heck, we even recommend that you do.

**Comment by wizzard0** [comment]
Thanks for the explanation. Makes sense, unfortunately %)
