### ISSUE TITLE
Fail to build due to `property missing ':'` when inline style

### ISSUE THREAD

**Issue by rluvaton** [preactjs/preact-cli#1804]
**What is the current behavior?**
Fail to build

**Steps to Reproduce**
Just run `npm run build` in this [codesandbox repro](https://codesandbox.io/p/sandbox/mutable-silence-tgjy7w)

**What is the expected behavior?**
successful build

**Please mention any other relevant information**
This is happening due to a bug in the [`css`](https://github.com/reworkcss/css) package that is a dependency of [`critters-webpack-plugin`](https://github.com/GoogleChromeLabs/critters) that is this package dependency

the `css` package seems unmaintained so opening the issue here as well 

Related bug URL:
- https://github.com/reworkcss/css/issues/171

Related issue:
- #1218

a workaround is using `--no-inline-css` as suggested here - https://github.com/preactjs/preact-cli/issues/1218#issuecomment-863698940

**info:**
```shell
$ npm preact-cli info

Environment Info:
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    preact: ^10.16.0 => 10.16.0 
    preact-cli: ^3.5.0 => 3.5.0 
```

**Comment by rschristian** [comment]
This seems like an upstream issue. I'm not sure what actions we could take here to easily rectify it?

**Comment by korichdaniel** [comment]
@rschristian upgrading [critters-webpack-plugin](https://github.com/GoogleChromeLabs/critters) solve the issue as they do not have [css](https://github.com/reworkcss/css) as dependancy anymore.

**Comment by rschristian** [comment]
There is no new version of `critters-webpack-plugin` that this repo can upgrade to. If you're referring to v3, that relies upon a newer version of `html-webpack-plugin` which cannot be touched outside of a major. 

Use `preact-cli@next` if you want to use it.

**Comment by rschristian** [comment]
Closing this out, there's nothing actionable.

`critters-webpack-plugin@^3.0.0` might fix your issue, but you'll need to be on `preact-cli@next` to use it.
