### ISSUE TITLE
Config file failure when adding plugins

### ISSUE THREAD

**Issue by bre7** [preactjs/preact-cli#1810]
🚨 SOLVED: DO NOT USE YARN 2+

--------------

**What is the current behaviour?**
After adding pretty much any webpack plugin, cli fails to load the config file.

Tried with:

* imagemin-webpack-plugin and imagemin-mozjpeg
* sitemap-webpack-plugin
* sitemap
* copy-webpack-plugin

Error

> $ yarn build                                                                                                                                                                                            
‼ WARN Failed to load preact-cli config file, using default!
C:\demo1_preact\preact.config.js:1
TypeError: Ko._resolveFilename is not a function
    at Object.<anonymous> (C:\demo1_preact\preact.config.js:1)
    at Generator.next (<anonymous>)

**Steps to Reproduce**

1. Add and configure any of the plugins stated before
2. Run `yarn build`
3. See error

Repro CI
https://app.circleci.com/pipelines/github/bre7/preact-demo1/3/workflows/4af232bd-c70c-4136-a2a0-9e88f2ba5554/jobs/3
Repro source
https://github.com/bre7/preact-demo1

preact.config.js ✅
https://gist.github.com/bre7/714344d0015676dcb2189d576da8e471

preact.config.js ❌
https://gist.github.com/bre7/bc27acf7df3de8d82276eae08b68590c

**What is the expected behaviour?**
Build should run, sitemap should be created/copied.

**Please mention any other relevant information**

preact 10.19.2
preact-cli 3.5.0

> Environment Info:
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.9.0
    Yarn: 4.0.2
    npm: 9.5.0
  Browsers:
    Chrome: 120.0.x

**Comment by rschristian** [comment]
You'll need to specify what versions of those plugins you're using, but I should point out `preact-cli` isn't maintained. I might be able to help, but you're best off migrating to more modern tooling.

**Comment by rschristian** [comment]
Will take a look.

I'd suggest taking a peek at `create-preact` instead, which we call out on our [docs](https://preactjs.com/guide/v10/getting-started#create-a-vite-powered-preact-app) and in this ReadMe:

> **Note** preact-cli no longer sees active development! It's stable so you can rely upon it for all of your existing apps, but for creating new ones, we recommend Vite via [create-preact](https://github.com/preactjs/create-preact). It's a much faster, more modern experience and we're working to bring some Preact-CLI/WMR features to it.

**Comment by rschristian** [comment]
Ah, yeah Yarn 2+ isn't likely to be supported. Too niche, too demanding. Would stick to v1 or NPM.

**Comment by bre7** [comment]
I'd probably add a tiny alert-warning to the docs, recommending users to avoid using yarn 2+ or preact-cli. I'd be glad to send a PR.

**Comment by rschristian** [comment]
It's not so much that it'd need to bail that it's not worth going out of our way to test/support. If it works, then great.

Sorry, but that was just in reference to that `create-preact` error you shared, haven't looked into this issue here yet.

**Comment by bre7** [comment]
Don't worry, there's no point in looking to a project without outdated tooling. I'm already switching to Vite ! Thanks for the quick help btw !
