### ISSUE TITLE
Ignoring preact.config.js file on Linux

### ISSUE THREAD

**Issue by DeanPDX** [preactjs/preact-cli#1821]
**What is the current behaviour?**
On Linux, specifically, Preact CLI is ignoring my config file and I can't seem to figure out why. If I run `preact watch` or build I get this:

```
(node:17131) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
⚠ WARN Failed to load preact-cli config file, using default!
Function.prototype.apply was called on undefined, which is a undefined and not a function
```

**Steps to Reproduce**

Run `preact build` with the following stripped down config:

```javascript
export default (config, env, helpers, options) => {
    if (!config) {
        return;
    }
    // Only set up proxy if dev server exists
    // if (config.devServer) {
    //     config.devServer.proxy = [
    //         {
    //             path: '/api/**',
    //             target: 'http://localhost:8081/',
    //         }
    //     ];
    // }
};
```

As you can see, I have stripped my config down to literally nothing to ensure it's not a problem with the config.

**What is the expected behaviour?**
I expected it to load my config like it does on Windows.

**Other Info**
I found [this issue on StackOverflow](https://stackoverflow.com/questions/77865805/preact-apparently-ignoring-preact-config-js-file) that describes my problem exactly but it doesn't have a resolution.

I am also aware that the preact CLI is no longer maintained. I explored switching to modern tooling (AKA Vite) but I ran into all sorts of problems. My first thought was: create a shell of a project using `npm init preact` and then pull all of my existing files in. But the routing had changed, among other things. This specific project is a small, fixed fee project so I'm trying not to blow up my budget by messing with tooling **too** much. If you have advice on how to migrate from the Preact CLI to Vite in a smarter way, I'm open to that.

**Preact CLI Info**
Here is the result of my `npx preact-cli info`:

```
(node:16932) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Environment Info:
  System:
    OS: Linux 4.19 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  Binaries:
    Node: 21.6.1 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.8.1 - ~/.npm-global/bin/npm
  npmGlobalPackages:
    preact-cli: 3.5.1
```

**Comment by rschristian** [comment]
Have you set `"type": "module"` in your `package.json` by any chance? That'd be my only guess.

I'd need a repo to help further.

> But the routing had changed, among other things.

Routing is user land; while we recommend `preact-iso` for routing, you can bring any tool that you like. There's no conflicts or problems in doing so.

**Comment by DeanPDX** [comment]
> Have you set `"type": "module"` in your `package.json` by any chance? That'd be my only guess.

I haven't. I guess I'm going to try migrating to Vite because there's no sense in being on a not-supported platform. Currently dealing with style changes because in previous project I applied classes like `class={style.logo}` and switching all of those to `class="logo"`. Not exactly what changed there but I'm assuming the Preact CLI was doing some processing that my Vite project doesn't.

**Comment by rschristian** [comment]
> `class={style.logo}` and switching all of those to `class="logo"`. Not exactly what changed there but I'm assuming the Preact CLI was doing some processing that my Vite project doesn't.

This is called CSS Modules. In CLI v4 we required users switch to using `<name>.module.css`, a pattern that Vite also uses. It fixes the ambiguity for how the file will be processed.

So, any files you want to be handled as CSS modules need a rename, and then your imports referring to those files will need an update too.

**Comment by rschristian** [comment]
Just a couple additional notes now that I'm back at my computer:

> On Linux, specifically, Preact CLI is ignoring my config file

As the linked SO post states, this isn't CLI ignoring the config file, but unable to execute it. Typically this is due to syntax errors, though in your case, I'm not sure. Here's the lines in particular, you might be able to get more info by patching in a few `console.log`s into `preact-cli`:

https://github.com/preactjs/preact-cli/blob/e826f7caab0d07a27188aab04ca6e9d7d7c35314/packages/cli/src/lib/webpack/transform-config.js#L112-L119

I suppose I'd also check that Node versions match across Linux & Windows.

I'd really suggest jumping to CLI v4 at the least, if you stay with CLI for the time. It at least runs on modern Node without hacks.

---

Certainly let me know if you get stuck on any bit while migrating to Vite, if you go forward with that. Happy to help.

**Comment by DeanPDX** [comment]
I decided to just commit to migrating to Vite. Thanks for the tip about CSS Modules; that was one of the things holding me up. The way image imports work is ALSO different but overall the migration wasn't too bad. Thanks for your help, @rschristian. If anybody else runs into this problem: just migrate to Vite if you can. It's faster, my bundles are somehow smaller, and I'm really enjoying the tool thus far (coming from an Angular background, MAN these builds are fast!).
