### ISSUE TITLE
ERROR Template execution failed: TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by mxrguspxrt** [preactjs/preact-cli#667]
preact-cli 2.2.1

✖ ERROR Template execution failed: TypeError: Cannot read property 'replace' of null
✖ ERROR   TypeError: Cannot read property 'replace' of null

- prerender.js:73 handlePrerenderError
    [app]/[preact-cli]/lib/lib/webpack/prerender.js:73:37
  
  - prerender.js:50 prerender
    [app]/[preact-cli]/lib/lib/webpack/prerender.js:50:3
  
  - render-html-plugin.js:37 Object.ssr
    [app]/[preact-cli]/lib/lib/webpack/render-html-plugin.js:37:55
  
  - template.html:110 EM6I.module.exports
    [app]/[preact-cli]/lib/resources/template.html:110:37
  
  - index.js:264 
    [app]/[html-webpack-plugin]/index.js:264:16
  
  - util.js:16 tryCatcher
    [app]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [app]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [app]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:606 Promise._settlePromiseCtx
    [app]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:142 _drainQueueStep
    [app]/[bluebird]/js/release/async.js:142:12
  
  - async.js:131 _drainQueue
    [app]/[bluebird]/js/release/async.js:131:9
  
  - async.js:147 Async._drainQueues
    [app]/[bluebird]/js/release/async.js:147:5
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [app]/[bluebird]/js/release/async.js:17:14

**Comment by rainy-me** [comment]
Same error. Fixed by [this comment](https://github.com/developit/preact-cli/issues/243#issuecomment-323770905) in #243
