### ISSUE TITLE
Feature Request: Installing dependencies progress

### ISSUE THREAD

**Issue by SleeplessByte** [preactjs/preact-cli#683]
**Do you want to request a *feature* or report a *bug*?**

A feature: Showing the progress of dependencies installing when creating a new project.

**What is the current behaviour?**

It shows a spinner with "Installing dependencies"

**What is the expected behaviour?**

It shows a spinner with "Installing dependencies", with a percentage, or x out of y and/or ETA to finish.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

I never know if it's actually doing anything because installing dependencies takes forever. Has the template downloaded? Is it stuck? Is my internet working?

**Please mention other relevant information.**
- Node version: v10.7.0
- npm version: yarn 1.12.1
- Operating system: Windows 10
- CLI version: @next

**Comment by ForsakenHarmony** [comment]
Fixed in the other issue?

**Comment by AnthumChris** [comment]
Great idea! May be worth reopening this issue, because I'm on a 6mbps connection and am downloading 225MB in > 30s.  A progress indicator would be a nice touch for something so large.

```bash
$ node -v; npm -v; preact -h |grep preact-cli
v10.16.3
6.9.0
preact-cli 2.2.1


$ time preact create default test-project

real	0m39.396s
user	0m26.677s
sys	0m11.215s


$ du -sh test-project/node_modules/
226M	test-project/node_modules/
```

**Comment by ForsakenHarmony** [comment]
The fix should be in the latest `@rc` version, will be released as `@latest` soon when we have the async component ready
