### ISSUE TITLE
Bug: If something fails during installing dependencies, it never finishes

### ISSUE THREAD

**Issue by SleeplessByte** [preactjs/preact-cli#684]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behaviour?**

If something happens during installing dependencies, an error _might_ show, but it never stops spinning, for example, but not limited to:
- No write rights to dest folder
- Using `force` but a file that is overwritten is locked / open
- Connection fails

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. on windows with UAC open a regular prompt
2. try to create a new project
3. rejoice as it fails
4. cancel
5. open as administrator
6. try to create a new project
7. done

**What is the expected behaviour?**

When it fails it tells me why, and stops processing, not spinning indefinitely.

**Please mention other relevant information.**
- Node version: v10.7.0
- npm version: yarn 1.12.1
- Operating system: Windows 10
- CLI version: @next

**Comment by MasterRennor** [comment]
@SleeplessByte, that's an interesting issue - your feature request, too. I personally haven't run into the problem with the standard Windows cmd (or any other shell). 

As far as I can see, this block in `create.js` is where that stage of the `create` is handled:

```
if (argv.install) {
    spinner.text = 'Installing dependencies';
    await install(target, isYarn);
}
```

And the `install` method in `setup.js` simply returns a Promise:
```
exports.install = function(cwd, isYarn) {
    let cmd = isYarn ? 'yarn' : 'npm';
    return spawn(cmd, ['install'], { cwd, stdio });
};
```

Both the `cross-spawn-promise` package the the `cross-spawn` that it's using will throw errors as expected.

Logging other stuff can be done by changing the `spawn` call to:
`spawn(cmd, ['install'], { cwd, stdio: 'inherit' });`

The end result would be something like this:
![image](https://user-images.githubusercontent.com/12250247/55556066-f4245780-56e6-11e9-8858-bd40c3ced511.png)

I'm not sure that's the intended effect here, though.

**Comment by ForsakenHarmony** [comment]
We could just remove the automatic install and output `Please cd into the directory and install dependencies`

**Comment by MasterRennor** [comment]
But wouldn't that mean removing the `--install` option, too? Personally, I find that quite convenient. ;D

**Comment by MasterRennor** [comment]
Still, if it _is_ causing lots of issues, I would consider it.

**Comment by SleeplessByte** [comment]
@MasterRennor 

Yeah, it's an edge case that was actually hard to reproduce because it requires a specific state to hit.

```javascript
spawn(cmd, ['install'], { cwd, stdio: 'inherit' });
```

This is what I would have expected. `stdio: 'ignore'` is fine, but then you need to capture the error output and show that in your own way.

@ForsakenHarmony I actually like that it auto installs. The only issue is the lack of communication.

**Comment by ForsakenHarmony** [comment]
Wanna make a pr for that option?

**Comment by SleeplessByte** [comment]
Which exact option are you referring to 😅 . I'll gladly PR whatevs!

**Comment by ForsakenHarmony** [comment]
Setting `stdio` to `'inherit'` if you think that's better

**Comment by MasterRennor** [comment]
I hope you guys don't mind, but I had some spare time on my hands and created a quick PR for that. :)

**Comment by ForsakenHarmony** [comment]
This is in the latest RC so I think I can close this
