### ISSUE TITLE
Webpack-dev-server can't serve inner routes with publicPath set

### ISSUE THREAD

**Issue by bendtherules** [preactjs/preact-cli#748]
[Moved from https://github.com/developit/preact/issues/1300]

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
Repoduction steps:
I have started a app with preact-cli (default template). Now all the routes (like /profile) are served correctly from dev server (works with page reload).

Then, added publicPath (="/frame") to both output and devServer in webpack config. Also changed the route path and link paths. (See in repo)

Now, on running dev server -

1. `/frame` serves the main app correctly and client-side routing works from there.
2. But if we directly hit `/frame/profile`, dev server says can't get page.

Using route path as `<Profile path="/profile/" user="me" />` or `<Profile path="/frame/profile/" user="me" />` didn't help.

Just to be clear, something like this works with react - so it shouldn't be a problem with dev server itself, but the dev server configurations that we are setting.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Given above.
Also repo:
https://github.com/bendtherules/preact-publicpath-bug

**What is the expected behaviour?**
`/frame/profile` will be served correctly by webpack devserver

**Please mention other relevant information.**
- Node version - v8.11.3
- npm version - 6.4.1
- Operating system - macOS Mojave
- CLI version - 2.2.1
- Browser - Doesn't matter

**Comment by bendtherules** [comment]
Hi,
Any updates on this?
Was someone else able to recreate the issue?

**Comment by mattsaddo** [comment]
You can use hashHistory for this so that it works off a subdomain. https://github.com/developit/preact-router#custom-history

**Comment by ForsakenHarmony** [comment]
Sorry, seem to have missed this

**Comment by ForsakenHarmony** [comment]
Can you check if it's still an issue with `@rc`?

**Comment by zedford** [comment]
When you change the publicPath, you must also make sure to change the historyApiFallback as well as a simple boolean no longer works, i.e.
`
publicPath: '/apps/',
historyApiFallback: { index: '/apps/index.html' },
`
