### ISSUE TITLE
[Next] Question about resolve.modules

### ISSUE THREAD

**Issue by psabharwal123** [preactjs/preact-cli#755]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behaviour?**
in webpack-base-config.js -
resolve: {
			modules: ['node_modules', ...nodeModules],

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
should order be [...nodeModules, 'node_modules'] ?

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Currently if i upgrade preact in my project to version X, entry.js in preact-cli will still use the old preact from node_modules in preact-cli. Would changing the order to [...nodeModules, 'node_modules'] give preference to preact from cwd/node_modules ?

**Please mention other relevant information.**
- Node version 10.15.3
- npm version 6.9.0
- Operating system windows 10
- CLI version 3.0.0-next16
- Browser any

**Comment by ForsakenHarmony** [comment]
I'll look into it

**Comment by psabharwal123** [comment]
@ForsakenHarmony is my understanding of the issue correct? should i submit a PR to fix this?

**Comment by ForsakenHarmony** [comment]
It should be released in the latest next, you can see if that changes anything, sorry about not updating this
