### ISSUE TITLE
Q: Include API response in prerendered site

### ISSUE THREAD

**Issue by lmittmann** [preactjs/preact-cli#759]
I have a Preact site that renders a list, which is retrieved from an API. The first items of that list almost never change. I already use prerendering to show e.g. the navigation header directly.

**Q:** Is it be possible to make Preact call the API endpoint while building to prerender the retrieved list as well.

**Comment by prateekbh** [comment]
We have a few ideas around this. Expect this to land in 3.0

**Comment by ForsakenHarmony** [comment]
Pretty much the only missing piece right now is async support in `prerender-urls.js`

**Comment by ForsakenHarmony** [comment]
I think we have it now?

**Comment by lmittmann** [comment]
@ForsakenHarmony So how can I include dynamic content form an API endpoint in my prerendered site using `prerender-urls.js`?

**Comment by ForsakenHarmony** [comment]
you return an array in there with the shape `[{ url: "/", ...props }]`

and it renders every entry + passes the props to the root component
