### ISSUE TITLE
Issues setting up font loading with preact.config.js

### ISSUE THREAD

**Issue by wfehrnstrom** [preactjs/preact-cli#774]
**Do you want to request a _feature_ or report a _bug_?**
I guess both?

**What is the current behaviour?**
On specifying function to push new loader configuration to webpack in preact.config.js, I get "TypeError: Cannot read property 'module' of undefined". See the gist below for the code that I added into preact.config.js 

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. Create new default template project with --git and --yarn.
2. Create preact.config.js
3. Add the following code to preact.config.js contained within this gist   
https://gist.github.com/wfehrnstrom/e52eb7519cbbece3ccd6106769659533

**What is the expected behaviour?**
To be able to add a new font within my directory assets/fonts and link it to index.css without having to do any additional setup of url-loader within preact.config.js. When I do have to do additional setup within preact.config.js by modifying the function, the documentation regarding this matter, following the format of the functions contained within https://github.com/developit/preact-cli/wiki/Config-Recipes
I would expect to work. This is not the case, and the documentation regarding changing webpack config within preact-cli is minimal at best. So this is both an issue of documentation, as I don't exactly know what to do within the preact.config.js file in order to modify webpack's loaders, and an issue of even having to do this in the first place, as I think it's pretty reasonable to expect that adding new font files to a preact-cli project (.otf), would not break the build and require non-trivial configuration. I do not know preact-cli's internals, so I'm not sure how hard font loader support would be to bundle in by default, but using url-loader to successfully import font files is a development dependency through yarn.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Users of preact-cli expect that importing font files and trivial file formats within preact-cli created projects should not break their projects.

**Please mention other relevant information.**

- Node version
v11.10.0
- npm version
6.7.0
- yarn version
1.13.0
- Operating system
macOS Mojave 10.14.4
- CLI version
3.2.57(1)-release
- Browser
Brave Version 0.62.50

**Comment by ForsakenHarmony** [comment]
`3.2.57` is not a cli version, are you using 3.0-rc?

For one `getLoaders` takes the config as the first argument

Secondly it's a read only wrapper, just to get information

So to modify it you'll want to access `config.module.rules` directly

**Comment by wfehrnstrom** [comment]
Sorry that I misunderstood your question about the CLI version. I think you are talking about preact-cli's version. In that case, I'm running v2.2.1. Thanks for the quick response. I've modified my gist to reflect the changes that you suggested. I now make a deep copy of the loaders, peek at the last one to get its index, and push it back onto the copy of loaders. I will admit that I'm new to webpack as a whole, and I find their documentation somewhat difficult to understand. I assume a one to one correspondence between preact-cli's config object and webpack's config. I now get the error:
```WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules should be an array:
   [object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, resource?, resourceQuery?, compiler?, rules?, test?, use? }]
   -> Options affecting the normal modules (NormalModuleFactory).
```
It seems to be that the configuration.module.rules is an array: I push onto it. As for other formatting issues, I'm not sure. I'm sorry if these are stupid questions: this is the first time I've poked around in webpack's internals.

**Comment by ForsakenHarmony** [comment]
```js
export default (config, env, helpers, options) => {
    // remove the last one
	config.module.rules.pop();
	// add a new loader
	config.module.rules.push(
      {
        test: /\.(png|woff|woff2|eot|ttf|otf|svg)$/,
        ruleIndex: lastLoader.ruleIndex+1,
        loaderIndex: lastLoader.loaderIndex+1,
        loader: 'url-loader?limit=100000'
      }
    );
}
```

This might be what you want

**Comment by wfehrnstrom** [comment]
That exact code errors for me with property cannot read property `pop` of undefined. What makes debugging this difficult is I'm unaware of any logging capabilities included with JS to allow printing out in this situation. console.log is a browser window command.

**Comment by ForsakenHarmony** [comment]
`console.log` works fine in node js

it might be `config.module.loaders` in webpack 3, not sure, sorry

**Comment by wfehrnstrom** [comment]
According to this API: https://webpack.js.org/configuration/module/#ruleuse , config.module.rules seems to be the correct way to go. config.module.rules appears to not be set when accessed, leading pop and push to be undefined. Including a guard for this, I can solve that issue. However, I still get the error: `TypeError: transformer is not a function`. Do you know of this specific error and what it represents?

**Comment by ForsakenHarmony** [comment]
that's webpack 4, `preact-cli@2` still uses webpack 3

You can also use `preact-cli@rc` which does use webpack 4

What do you actually want to change by adding this btw?

**Comment by wfehrnstrom** [comment]
I guess I didn't fully make it clear with the first comment that opened this issue, but I'd like to be able to add a new font, Aileron, under the assets directory using the default template that preact-cli has. Without using preact.config.js, I was getting an unexpected character error within the font file, when webpack tried to parse this. I've heard that you can solve this error by adding a proper url-loader to parse the font files, so I'm trying to add a url-loader to be able to load the font files in webpack correctly. How do I use preact-cli@rc? I'd prefer not to if it's less stable, or requires a good deal of configuration because of the errors I'm already encountering so far.

**Comment by ForsakenHarmony** [comment]
Which format is `Aileron` in?

**Comment by wfehrnstrom** [comment]
.otf

**Comment by ForsakenHarmony** [comment]
is that even supported by browsers?

**Comment by rafinskipg** [comment]
I would like to modify the rules for the IMG src too, but i am not allowed

**Comment by wfehrnstrom** [comment]
@ForsakenHarmony please see [https://caniuse.com/#feat=ttf](https://caniuse.com/#feat=ttf)

**Comment by ForsakenHarmony** [comment]
Interesting, it's not ideal though, you should use woff or woff2 for compression

But we do also support ttf, this should work 
```js
export default (config, env, helpers, options) => {
    // remove the last one
	const rule = config.module.loaders.pop();
	// change test
	rule.test = /\.(svg|woff2?|ttf|otf|eot|jpe?g|png|gif|mp4|mov|ogg|webm)(\?.*)?$/i;
	// add a new loader
	config.module.loaders.push(rule);
}
```
