### ISSUE TITLE
Question - Resources from CDN or inside app

### ISSUE THREAD

**Issue by fabiodcorreia** [preactjs/preact-cli#781]
Hi,

When using external resources like fontawesome or css framework like boostrap or bulma should we import the resources on our local style.css or style.scss that is imported by the index.js,  should we add the CDN urls on the index.html or there are other better ways to do this?

In my case I want this for a PWA so this resources should be available offline after the app get's "installed".

**Comment by prateekbh** [comment]
The resources you are talking about definitely fits better in index.html as far as i can tell.
But for caching it you'll need to add it to sw config using `preact-cli`
