### ISSUE TITLE
Duplicate preact instance while prerendering breaking options

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact-cli#795]
Ported over from: https://github.com/developit/preact-render-to-string/issues/86#issuecomment-492325953

**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behaviour?**

Prerendering will throw an undefined error:

```txt
TypeError: Cannot read property '__H' of undefined
```

This is caused by loading multiple instances of preact which can't see each others `option`-hooks. There are a total of 2 instances at play:

1) included in the generated `ssr-bundle.js`
2) one inside `prerender.js`: https://github.com/developit/preact-cli/blob/bd464043dac8646183ed9a8cfab677778f73b4f7/packages/cli/lib/lib/webpack/prerender.js#L28

Both instances have their own `options` variable which ultimately leads to this error.

**If the current behaviour is a bug, please provide the steps to reproduce.**

```json
{
  "scripts": {
    "build": "preact build"
  },
  "devDependencies": {
    "preact-cli": "^3.0.0-rc.1",
    "preact-render-to-string": "^5.0.3"
  },
  "dependencies": {
    "preact": "^10.0.0-beta.1"
  }
}
```

```jsx
import { useState } from "preact/hooks";

export default () => {
  const [a, b] = useState("c");
  return <h1>Hello, World! {a}</h1>;
};
```

**What is the expected behaviour?**

It should not throw.

**Please mention other relevant information.**

- Node version: 11.7
- npm version 6.5.0
- Operating system: Linux Debian Sid
- CLI version: 3.0.0-rc.1
- Browser: doesn't matter

**Comment by prateekbh** [comment]
// @lukeed

**Comment by lukeed** [comment]
We can do without the `require('preact')` that @marvinhagemeister linked. I think the solution is to modify the `entry.js` file w/ ENV keys for build-time manipulation. We want to be able to just do this:

```js
return renderToString( App({ ...params, url }) );
```

**Comment by marvinhagemeister** [comment]
@lukeed That's likely not enough. `preact` is inlined into the `ssr-bundle` file. `preact-render-to-string` imports straight from `node_modules` so we'll end up with 2 instances again :S

**Comment by lukeed** [comment]
Ah, true. Making it external for SSR bundle should probably do the trick. Then no change needed for entry at all

**Comment by prateekbh** [comment]
glad i was in right direction for the solution.. :) will try it out

**Comment by prateekbh** [comment]
@marvinhagemeister I was able to make it work by making preact external and updating `preact` to beta 10.
However the `preact-render-to-string@4.0.1` return `<Undefined/>`.

I tried updating it to `preact-render-to-string@5.0.3` but this update breaks it again with the same error

```
TypeError: Cannot read property '__H' of undefined
```

**Comment by prateekbh** [comment]
@marvinhagemeister repo for repro: https://github.com/prateekbh/demo-preact-x-ssr-bug

**Comment by prateekbh** [comment]
my bad it works as expected

**Comment by prateekbh** [comment]
I have the fix ready, will open the PR soon 👍
