### ISSUE TITLE
emittingError: ENOENT: no such file or directory, stat 'D:\project\novel_wap\build\index.html'

### ISSUE THREAD

**Issue by liu-miao-miao** [preactjs/preact-cli#807]
**Do you want to request a _feature_ or report a _bug_?**
don't know

**What is the current behaviour?**
i create preact.config.js in root, import prerender-spa-plugin,when i run preact build,then get a error ;

> emittingError: ENOENT: no such file or directory, stat 'D:\project\novel_wap\build\index.html'

that's my preact.config.js file;

> const path = require('path');
> import PrerenderSPAPlugin from 'prerender-spa-plugin';
> const Renderer = PrerenderSPAPlugin.PuppeteerRenderer;
> 
> export default config => {
> 	config.plugins.push(
> 		new PrerenderSPAPlugin({
> 			staticDir: path.join(__dirname, 'build'),
> 			routes: [ '/', '/index', '/search' ],
> 			renderer: new Renderer({
> 				renderAfterTime: 5000
> 			})
> 		})
> 	);
> 	return config;
> };
plz help me,

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

- Node version
v10.15.3
- npm version
v6.4.1
- Operating system
windows 10 enterprise LTSC 1809
- CLI version
^2.1.0
- Browser
chrome 74.0.3729.169（build） （64 bit）

**Comment by ForsakenHarmony** [comment]
why are you using a separate plugin for prerendering?
