### ISSUE TITLE
Import SCSS style to component without CSS module 

### ISSUE THREAD

**Issue by tthygesen** [preactjs/preact-cli#808]
Hey all,
I am sorry if this seems like a stupid question. I tried my best find an answer for 
this 'problem'. 
I just want to import style in a 'normal' way without using the styles module way so I can write classes like this 

  `class="my-classs"` 

instead of  
  
  `class={style.my-class}`

Hope the question i understandable and thanks for taking the time. 

**What is the current behaviour?**
`import styles from './styles`

**What is the expected behaviour?**
`import './styles`

**Please mention other relevant information.**

- Node version : 10.16.0
- npm version : 6.9.0
- Operating system : macOs Mojave 10.14.5
- CLI version : 2.2.1
- Browser : Goolge Chrome

**Comment by ForsakenHarmony** [comment]
it's automatic for styles in the components or routes dirs

https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/webpack/webpack-base-config.js#L194

**Comment by tthygesen** [comment]
I have to admit I am not the sharpest in Webpack, but does this mean i do not have to import the style in my component ?

**Comment by ForsakenHarmony** [comment]
you have to import it somewhere, but the css file just "can't" be in those two directories if you don't want it to be a module

if you just have static styles you can i.e. put them in `styles/index.css` then import more in there and import `index.css` from `/index.js`

**Comment by tthygesen** [comment]
Thank you very much! That clarified it !

**Comment by ForsakenHarmony** [comment]
Glad I could help
