### ISSUE TITLE
sw-debug.js script is registering even if --sw=false in development mode

### ISSUE THREAD

**Issue by Panya** [preactjs/preact-cli#809]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
I'm using `preact watch --sw false` command but `sw-debug.js` script is still trying to register as service worker.

**What is the expected behaviour?**
no `sw-debug.js` service worker when `--sw false` is passed.

**Please mention other relevant information.**

- Node version 10.15.3
- npm version 6.4.1
- Operating system Mac OS 10.14.6
- CLI version 3.0.0-rc.2
- Browser Chrome 74

**Comment by prateekbh** [comment]
it really a no-op service worker thats installed only during `preact watch` to help you tell where you can use what APIs of SW.

does that seem confusing?

**Comment by Panya** [comment]
I prefer not to include the sw if sw=false.

**Comment by prateekbh** [comment]
gotcha

**Comment by ForsakenHarmony** [comment]
I guess we might want to add the option to watch as well

**Comment by psabharwal123** [comment]
https://github.com/preactjs/preact-cli/pull/884

**Comment by reznord** [comment]
This is fixed in #884

**Comment by DenizBasgoren** [comment]
registers sw-debug.js when I build with `preact build --no-sw`

**Comment by Haugen** [comment]
Same issue for me still. `sw-debug.js` is still included in the build folder when running `preact build --no-sw`. Using preact-cli version `3.0.1`.

**Comment by psabharwal123** [comment]
strange, I dont see it being included in the build in our project

**Comment by RonnyLV** [comment]
sw-debug.js still registering on Preact 3.0.3
![image](https://user-images.githubusercontent.com/3844817/100598296-344a3c00-3307-11eb-89b4-c48303d82405.png)

**Comment by RonnyLV** [comment]
When do you plan to release this fix?

**Comment by rschristian** [comment]
> 
> 
> When do you plan to release this fix?
> 
> ![image](https://user-images.githubusercontent.com/3844817/100600377-e2ef7c00-3309-11eb-9b18-b021adc0e5fc.png)

What fix are you referring to? 

Also, `--inline-css` and `--no-brotli` can be removed from your command. CSS is inlined by default, and brotli is disabled by default. The flags have no effect with your usage.

**Comment by RonnyLV** [comment]
> > When do you plan to release this fix?
> > ![image](https://user-images.githubusercontent.com/3844817/100600377-e2ef7c00-3309-11eb-9b18-b021adc0e5fc.png)
> 
> What fix are you referring to?
> 
> Also, `--inline-css` and `--no-brotli` can be removed from your command. CSS is inlined by default, and brotli is disabled by default. The flags have no effect with your usage.

I'm referring to the fix regarding sw-debug.js being included in the build output

**Comment by rschristian** [comment]
"The fix" was released back on Sept 7, 2019. If there was a regression you should open a new issue.

**Comment by RonnyLV** [comment]
Ok, no problem, here it is #1477
