### ISSUE TITLE
preact-cli 3.0.0-rc.2 install fails 

### ISSUE THREAD

**Issue by tkassila** [preactjs/preact-cli#811]
**Do you want to request a _feature_ or report a _bug_?**
bug: cannot access file or dir! 

**What is the current behaviour?**
npm install -g preact-cli@3.0.0-rc.2 fails because it has not access/rigths!

**If the current behaviour is a bug, please provide the steps to reproduce.**
see above install command and below and executed as a root!

pm WARN deprecated sw-precache@5.2.1: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
npm WARN deprecated sw-toolbox@3.6.0: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
/usr/local/bin/preact -> /usr/local/lib/node_modules/preact-cli/lib/index.js

> nodent-runtime@3.2.1 install /usr/local/lib/node_modules/preact-cli/node_modules/nodent-runtime
> node build.js

fs.js:114
    throw err;

- later above directory/ies does not exists after command execution.

**What is the expected behaviour?**
no

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
v12.4.0
- npm version
6.9.0
- Operating system
cat /etc/*rel*
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"

- CLI version

- Browser
none on this

**Comment by ForsakenHarmony** [comment]
you shouldn't run `npm install` as root

see
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by tkassila** [comment]
Thanks, Now all is working, but an extra thing was: npm uninstall preact ... etc and rm -R for old @HOME/node_modules/preact* dirs and files. And then as normal user: npm i preact@preact-cli 3.0.0-rc.2 installed ok, preact -v, preate create default test1 ok.
