### ISSUE TITLE
Having a dedicated command to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [preactjs/preact-cli#812]
### Use case

What about including a dedicated command such as `preact info` which shows up necessary local environment information. With that, all the user has to do is to copy and paste the relevant information useful especially while submitting bug reports.

`preact info`

**Comment by jamesgeorge007** [comment]
@lukeed I would love to submit a PR for the same :+1: Shall I go ahead?

**Comment by ForsakenHarmony** [comment]
Sure

**Comment by lukeed** [comment]
How about calling it `envinfo` command? And then we can pull in & attach [`envinfo`](https://www.npmjs.com/package/envinfo) directly? That'd be pretty sweet I think

**Comment by prateekbh** [comment]
Just curious, why do we need this to be a part of `preact-cli`?
A lot of OSS projects need similar info now a days. 
Just that I dont see a value of adding this dep to fill in a section of a PR.

Also this will be downloaded by all the users even though probably 90% of them will never contribute to `preact-cli`

**Comment by jamesgeorge007** [comment]
@prateekbh Didn't get you :confused:

**Comment by ForsakenHarmony** [comment]
https://packagephobia.now.sh/result?p=envinfo

Seems fine to me, it's self contained

**Comment by prateekbh** [comment]
well ok, just in doubts do we really need it
