### ISSUE TITLE
Example proxy breaks SPA functionality

### ISSUE THREAD

**Issue by zwrawr** [preactjs/preact-cli#815]
**Do you want to request a _feature_ or report a _bug_?**
Bug / Documentation fix

**What is the current behaviour?**
Using the example proxy code breaks the single page app feature.

If the example proxy code is used then when navigating directly to anywhere but the route the SPA will not be served to you. These pages still work when you go to them via a link on the home page.

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. `preact create default` with all default settings
2. move into app i.e `cd app` 
3. `npm run dev`
4. verify SPA functionality is working by navigating directly to `localhost:8080/profile`
5. create the `preact.config.js` and add the following from the [config recipes](https://github.com/preactjs/preact-cli/wiki/Config-Recipes#setting-proxy-for-dev-server-using-config-directly)
    ```js
    export default (config, env, helpers) => {
	    config.devServer = {
	      quiet: true,
	      proxy: [
		    {
		      path: '/api/**',
		      target: 'http://api.example.com',
		      // ...any other stuff...
		    }
	      ]
	    }
      }
    ```
6. reload the server `Ctrl-C` and `npm run dev`
7. Navigate directly to `localhost:8080/profile` again to show that SPA is broken
    > Cannot GET /profile

**What is the expected behaviour?**
- The SPA functionality should still work even with a proxy
- The example proxy shouldn't break the site

**Please mention other relevant information.**

- Node version: v10.15.3
- npm version: v6.4.1
- Operating system: Ubuntu 19.04
- CLI version: preact-cli 2.2.1
- Browser:  Chrome 75

**Comment by zwrawr** [comment]
Changing the example to this would avoid overwriting the other devServer settings. Which would stop the example code breaking stuff and help avoid confusion.
```js
export default (config, env, helpers) => {
	config.devServer['proxy'] = [
		{
			path:'/api/**',
			target: 'http://api.example.com',
			// ...any other stuff...
		}
	]
}
```

**Comment by ForsakenHarmony** [comment]
no idea why it was changed, the old one was correct

**Comment by ForsakenHarmony** [comment]
Changed it back
