### ISSUE TITLE
Unable to build with async function

### ISSUE THREAD

**Issue by abird** [preactjs/preact-cli#821]
**Do you want to request a _feature_ or report a _bug_?**
report a bug

**What is the current behaviour?**
Whenever I do a build and my code contains an async function, I get the UglifyJs error with the unexpected token operator «*».

I've seen references to this problem a year or two ago, but I'm having this problem with the current build and no solutions seem to work.

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. preact create default test
2. cd test
3. edit app.js file and add:
async function test() {
	return true;
}
4. npm run build

Get error:

✖ ERROR bundle.1f687.js from UglifyJs
Unexpected token operator «*», expected punc «(» [./components/app.js:34,0][bundle.1f687.js:675,39]

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

- Node version
10.15.3
- npm version
6.4.1
- Operating system
macos 10.14.5
- CLI version
2.2.1
also tried with 3.0.0-rc.2 with same result
- Browser
na

**Comment by ForsakenHarmony** [comment]
do you have your own `.babelrc`?

**Comment by abird** [comment]
As a test, I only did the 4 steps outlined above. I did not change any of the configuration. I only added the async function to the app.js file.

**Comment by ForsakenHarmony** [comment]
with `@rc` you'll also have to install it into the project again because the template uses 2.x

**Comment by abird** [comment]
OK. That worked. I did:

npm install --save-dev preact-cli@3.0.0-rc.2

I think previously I had installed 3.0.0-rc.2 at the global level and that didn't work.

I'm getting some new warnings about "Autoprefixer browsers option" but I can look into that.

Thanks for your help. I'll go ahead and close this issue.
