### ISSUE TITLE
SSR outputs <undefined></undefined> node

### ISSUE THREAD

**Issue by ciampo** [preactjs/preact-cli#822]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**

When enabling SSR, the output is a `<undefined></undefined>` node, instead of the contents of the page

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Follow this gist to use latest preact cli, and update preact dependencies to latest version: https://gist.github.com/developit/f1a3425ded9b52206c372b6c6b54ddcb

2. Add a `prerender-urls.json` file in the root project folder and add this content:

```
[
  {
    "url": "/",
    "title": "Homepage"
  }
]
```

3. run `npm run build`

4. notice how the file `build/index.html` has a `<undefined></undefined>` HTML node instead of the SSRs page

**What is the expected behaviour?**

The SSR'd HTML file should include the page contents.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

N/A

**Please mention other relevant information.**

- Node version 12.3.1
- npm version 6.9.0
- Operating system MacOS 10.14.5
- CLI version 3.0.0-rc.2
- Browser N/A

**Comment by ForsakenHarmony** [comment]
Do you have `preact-compat` installed? if so please remove it

**Comment by ciampo** [comment]
Good catch, I did have it installed.

Although I removed `preact-compat` from `package.json`, re-installed dependencies, and I am still having the same problem.

Can you reproduce it too?

**Comment by evont** [comment]
maybe you should try upgrading` preact-render-to-string` to 5.02

**Comment by ForsakenHarmony** [comment]
yeah I forgot about that part thanks @evont 

We should make it more obvious though

/cc @developit

**Comment by ciampo** [comment]
Thank you @evont, that fixed it!

@ForsakenHarmony Yeah it'd be a good idea to update the gist

**Comment by developit** [comment]
Gist updated. Might be neat for us to add a check to the CLI that verifies known good versions.

**Comment by lorenzo-dd** [comment]
hi everyone,

I have the same issue as of today, I had preact-render-to-string@5.1.0 installed and I tried to install the afore mentioned 5.0.2, but I still get <undefined></undefined> tag instead of the expected prerendered content in the build/index.html file.

**Comment by reznord** [comment]
This is fixed in the latest versions of CLI.
