### ISSUE TITLE
Browserlist warning

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact-cli#825]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behaviour?**

Lots of warnings created by autoprefixer when running any command:

```
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Create project with `preact-cli@rc`
2. Start dev server

**What is the expected behaviour?**

No warnings

**Please mention other relevant information.**

Please paste the results of `preact info` here.

```
  ERROR
    Invalid command: info

  Run `$ preact --help` for more info.

error Command failed with exit code 1.
```

Looks like we need to update the issue template :grimacing:

**Comment by marvinhagemeister** [comment]
@ForsakenHarmony @prateekbh @lukeed Just checked with `master` and the fix is already there. Any chance we could publish a new rc?

**Comment by ForsakenHarmony** [comment]
might be fixed now in https://github.com/preactjs/preact-cli/releases/tag/v3.0.0-rc.3

**Comment by marvinhagemeister** [comment]
Sweet, thank you so much :+1: Can confirm that it's fixed in `rc3` :tada:
