### ISSUE TITLE
Add to-string-loader to scss rule

### ISSUE THREAD

**Issue by marijnbent** [preactjs/preact-cli#827]
**Do you want to request a _feature_ or report a _bug_?**
Not sure

**What is the current behaviour?**
I want to add a loader (https://www.npmjs.com/package/to-string-loader) before the sass-loader. 

**If the current behaviour is a bug, please provide the steps to reproduce.**
In `preact.config.js`.

```
  let {ruleIndex} = helpers.getLoadersByName(config, 'sass-loader')[0];
  let rules = helpers.getRules(config);
  rules[ruleIndex].push('to-string');
```
Whatever I try, ruleIndex is always undefined. 

**What is the expected behaviour?**
`import styles from './CertificateModal.scss';` should return a string, to be used in a `<style></style>` tag inside a shadow dom. 

**If this is a feature request, what is motivation or use case for changing the behaviour?**
How to debug this?
Am I doing something wrong?

**Comment by developit** [comment]
```js
let { ruleIndex } = helpers.getRulesByMatchingFile(config, '.scss')[0];
config.module.rules.splice(ruleIndex, 0, 'to-string-loader');
```

FWIW this will break all CSS, since it's not possible to have CSS compile to a stylesheet and a string.

**Comment by marijnbent** [comment]
`let { ruleIndex } = helpers.getRulesByMatchingFile(config, '.scss')[0];` outputs all the loaders, not just the .scss loader.

Output:
```
  loaders: [
    {
      enforce: 'pre',
      test: /\.jsx?$/,
      loader: 'babel-loader',
      options: [Object]
    },
    { enforce: 'pre', test: /\.less$/, use: [Array] },
    { enforce: 'pre', test: /\.s[ac]ss$/, use: [Array] },
    { enforce: 'pre', test: /\.styl$/, use: [Array] },
    {
      test: /\.(css|less|s[ac]ss|styl)$/,
      include: [Array],
      loader: [Array]
    },
    {
      test: /\.(css|less|s[ac]ss|styl)$/,
      exclude: [Array],
      loader: [Array]
    },
    { test: /\.json$/, loader: 'json-loader' },
    { test: /\.(xml|html|txt|md)$/, loader: 'raw-loader' },
    {
      test: /\.(svg|woff2?|ttf|eot|jpe?g|png|gif|mp4|mov|ogg|webm)(\?.*)?$/i,
      loader: 'url-loader'
    },
    {
      test: /\.jsx?$/,
      include: [Array],
      loader: '/Users/marijnbent/Projects/wsfy-js/node_modules/preact-cli/lib/lib/webpack/async-component-loader',
      options: [Object]
    }
  ]
```

**Comment by rschristian** [comment]
This looks to have been fixed at some point, so closing out.
