### ISSUE TITLE
HMR fails in v3 with modules enabled

### ISSUE THREAD

**Issue by jjacobson93** [preactjs/preact-cli#828]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Running `preact watch` fails to provide proper HMR without a full-page reload.

**What is the expected behaviour?**
Running `preact watch` should provide HMR without a full-page reload.

**Please mention other relevant information.**

Versions:
```
preact-cli: 3.0.0-rc.2
preact: 10.0.0-beta.3
```

I've done a little debugging and it looks like the HMR code is included in the bundle twice. I've tried the following but none of them seemed to work: changing the the devServer options, removing the dev server from the bundle in the "entry", and removing the HMR webpack plugin. I disabled ESM and everything works fine. It looks like it's only a problem when compiling with modules.

**Comment by developit** [comment]
Dev mode could probably compile without esm by default.

**Comment by prateekbh** [comment]
This was the case earlier but, ppl had bugs only in esm and thus got stuck when doing prod builds

**Comment by developit** [comment]
strange. I know Next and Gatsby both use `modules: 'auto'`, which infers whether to use modules based on information passed to Babel by `babel-loader`, ultimately selecting commonjs during development and esmodules for production.

**Comment by prateekbh** [comment]
Also, it was just a plug-in bug which got fixed... May be it's ok to go back to cjs for dev

**Comment by psabharwal123** [comment]
@developit https://github.com/preactjs/preact-cli/issues/721 was the issue @prateekbh is talking about. Can we still support esm flag on dev, and default it to cjs?

**Comment by psabharwal123** [comment]
not sure if https://github.com/prateekbh/babel-esm-plugin/issues/12#issuecomment-476234002 helps

**Comment by prateekbh** [comment]
This should be fixed now
