### ISSUE TITLE
preact create widget template not working with preact x

### ISSUE THREAD

**Issue by th-m** [preactjs/preact-cli#840]
### steps to reproduce.

- `npm install -g preact-cli`
- `preact create widget new-widget`
- `cd new-widget`
- `npm install preact@next`
- `npm i`
- `npm run serve`

![Screen Shot 2019-07-16 at 2 15 13 PM](https://user-images.githubusercontent.com/13792029/61326508-2b210380-a7d4-11e9-8d47-4b6d75359af0.png)

### Trying to serve the `build/index.html` directly through chrome

![Screen Shot 2019-07-16 at 2 11 00 PM](https://user-images.githubusercontent.com/13792029/61326244-8ef6fc80-a7d3-11e9-88a5-88f7957cf7c1.png)

**Comment by ForsakenHarmony** [comment]
#657 we know, it's not really maintained right now

**Comment by th-m** [comment]
@ForsakenHarmony What is not maintained? preactx or the widget template?

**Comment by ForsakenHarmony** [comment]
the widget template sadly
