### ISSUE TITLE
Hashing isn't stable when the file contents haven't changed

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact-cli#853]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**

Just noticed that on https://github.com/preactjs/preact-www/pull/338#issuecomment-515845394 that some files have the exact same content, but a different hash with each build. This makes it hard to track size changes across builds.

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Run build, check size
2. Run build, check again

**What is the expected behaviour?**

Filenames stay the same when the content didn't change.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

See above.

**Please mention other relevant information.**

Using the latest RC.

**Comment by kuldeepkeshwar** [comment]
https://github.com/preactjs/preact-cli/blob/4da222985ed6afd1da53767eb0927c30c62920d9/packages/cli/lib/lib/webpack/webpack-client-config.js#L47

will changing `chunkhash:5` to `chunkhash` fix it

**Comment by ForsakenHarmony** [comment]
I don't think so

**Comment by kuldeepkeshwar** [comment]
Yup, I tried it. I cloned the project in a different directory & ran the build, got a different hash.  it doesn't work.

**Comment by ForsakenHarmony** [comment]
Might be a webpack problem, but not sure 🤔

**Comment by ForsakenHarmony** [comment]
> any reason we do path based hashing

we do?

**Comment by kuldeepkeshwar** [comment]
@marvinhagemeister @developit @ForsakenHarmony 
I tested above configure with `webpack@5.0.0-alpha.19`. it doesn't output a different hash. Seems like updating webpack fix it.

**Comment by prateekbh** [comment]
Oooof... That's bad.
Upgrading webpack by a major version is a big deal because of plethora of plugins which might not work

**Comment by marvinhagemeister** [comment]
Agree, I'd hold off until webpack 5 is at least stable.

**Comment by kuldeepkeshwar** [comment]
> Agree, I'd hold off until webpack 5 is at least stable.

plus the plugin chain 🙂

**Comment by rschristian** [comment]
Looks like this was fixed at some point in CLI or maybe back ported to Webpack v4, as we've had consistent hashes on our assets for a fair while now. This is part of our test suite, at least for non-esm assets:

https://github.com/preactjs/preact-cli/blob/783bb013e4381bd72ab34d7880776846abf12cfd/packages/cli/tests/images/build.js#L1-L35
