### ISSUE TITLE
Way to put files on root

### ISSUE THREAD

**Issue by prateekbh** [preactjs/preact-cli#865]
**Do you want to request a _feature_ or report a _bug_?**
_feature_

**What is the current behaviour?**
We don't have a good way of putting files on the root after build.
Most CLI's have a way of doing it by putting everything in `static`/`root` folder and putting them at root level of build folder.

This is handy for putting stuff like static CMS' admin pages/robots.txt file/`.htaccess` etc etc

**If the current behaviour is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behaviour?**
There should be a recommended directory which puts its content on root in build directory

**Comment by reznord** [comment]
Fixed in #866
