### ISSUE TITLE
Yarn template still uses npm in README.md and package.json

### ISSUE THREAD

**Issue by andybons** [preactjs/preact-cli#871]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Generated `README.md` and `package.json` scripts use `npm` instead of `yarn` even when the `--yarn` option is specified.

**If the current behaviour is a bug, please provide the steps to reproduce.**

```bash
preact create yarnapp --yarn
grep npm ./yarnapp/README.md ./yarnapp/package.json
```

**What is the expected behaviour?**

Yarn is used throughout project instructions and in `package.json`

**If this is a feature request, what is motivation or use case for changing the behaviour?**

N/A

**Please mention other relevant information.**

N/A

Please paste the results of `preact info` here.

```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    preact: ^8.3.1 => 8.5.2 
    preact-cli: ^3.0.0-next.19 => 3.0.0-rc.4 
    preact-compat: ^3.18.4 => 3.19.0 
    preact-render-to-string: ^4.1.0 => 4.1.0 
    preact-router: ^2.6.1 => 2.6.1 
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.4
```

**Comment by harshitkumar31** [comment]
I think the owners need add the description https://github.com/preactjs-templates/widget & https://github.com/preactjs-templates/typescript

**Comment by andybons** [comment]
Yep it looks that way from looking at the code.

**Comment by DenysVuika** [comment]
I am working on the PR to improve project templates, will fix this issue too.

**Comment by ForsakenHarmony** [comment]
I'm not sure if the scripts in `package.json` are a problem
