### ISSUE TITLE
TypeScript and Widget templates show “null” descriptions

### ISSUE THREAD

**Issue by andybons** [preactjs/preact-cli#872]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
See issue description and repro step below.

```
preact list

ℹ INFO Available official templates: 

  ⭐️  default - The default template for Preact CLI (preact create default my-app) 
  ⭐️  material - The material design `preact-cli` template. 
  ⭐️  simple - A simple, minimal "Hello World" template for Preact CLI 
  ⭐️  typescript - null
  ⭐️  widget - null
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
See above

**What is the expected behaviour?**
Descriptions after `typescript` and `widget` are not `null`

**If this is a feature request, what is motivation or use case for changing the behaviour?**
N/A

**Please mention other relevant information.**
N/A

Please paste the results of `preact info` here.
```
preact info

Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    preact: ^8.3.1 => 8.5.2 
    preact-cli: ^3.0.0-next.19 => 3.0.0-rc.4 
    preact-compat: ^3.18.4 => 3.19.0 
    preact-render-to-string: ^4.1.0 => 4.1.0 
    preact-router: ^2.6.1 => 2.6.1 
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.4
```

**Comment by harshitkumar31** [comment]
I think the owners need to add the descriptions https://github.com/preactjs-templates/widget & https://github.com/preactjs-templates/typescript

**Comment by andybons** [comment]
Yep. Looks that way from looking at the code.

**Comment by DenysVuika** [comment]
I did a PR to better format the list and display descriptions only when present. One the corresponding repos get their descriptions done - it should be displayed with the `preact list` command.
