### ISSUE TITLE
Build process fails to locate custom template

### ISSUE THREAD

**Issue by verbman** [preactjs/preact-cli#876]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Upgraded to version 3.0.0-rc.5 and build command with custom template file fails. Uninstalled and returning to version 3.0.0-rc.4 resolves the problem

**If the current behaviour is a bug, please provide the steps to reproduce.**
The build command I was using is: `preact build --template src/template/defaultindex.html`

**What is the expected behaviour?**
Build succeeds

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
Error on build: 
× ERROR Error: ENOENT: no such file or directory, open 'C:\Users\....\node_modules\preact-cli\lib\lib\webpack\src\template\defaultindex.html'

Please paste the results of `preact info` here.
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0

**Comment by Stas-Buzunko** [comment]
confirm this issue

**Comment by sirphoenix** [comment]
I can confirm this with 10.0.0-rc.1 and 3.0.0-rc.5.
It seems that cli tries to access the relative template path from "node_modules/preact-cli/lib/lib/webpack/" instead of the project root.

Workaround: if you use an absolute path with --template it still works, relative path with "../../../../../" will not work.

**Comment by sampotts** [comment]
I've found this option pretty useful to serve up different templates. It'd be good to restore the previous behavior if possible.

**Comment by prateekbh** [comment]
@sampotts can u elaborate your use case a bit so we can justify the restoring

**Comment by ForsakenHarmony** [comment]
don't really see why we should remove it if it's useful for someone

**Comment by prateekbh** [comment]
TBH my only concern was that we'll end up having two way to do exact same thing.
No strong preferences. We should totally fix it if it still has a use case

**Comment by sampotts** [comment]
I may be using it wrong but I have several different test pages to render simple preact components while in development: 

```json
"scripts": {
    "dev": "preact watch --template ./path/to/templates/index.ejs",
    "dev:store": "preact watch --template ./path/to/templates/store.ejs",
    "dev:product": "preact watch --template ./path/to/templates/product.ejs"
}
```

It's been working fine previously but if there's a better solution I'm all ears.

**Comment by sampotts** [comment]
Not sure why the issue is closed. It's still an issue...

**Comment by prateekbh** [comment]
This was fixed in #878, will be in next release

**Comment by sampotts** [comment]
@prateekbh Awesome, cheers! 🎉

**Comment by bmitchinson** [comment]
@sampotts I use templates the same way:
```
"dev": "preact watch --template ./path/to/templates/index.ejs"
```
But currently on rc.5 this functionality searches my node modules folder instead of the package directory. This is method still work for you?

Will this begin to work again once the next rc is released?
