### ISSUE TITLE
sass-loader 8 incompatiblity

### ISSUE THREAD

**Issue by LeviSchuck** [preactjs/preact-cli#880]
**Do you want to request a _feature_ or report a _bug_?** Bug

**What is the current behaviour?**
Installing `sass-loader` results in the latest version (8.0.0) from NPM.
then running `npm run start` which runs preact cli tools then fails with the following error
```
✖ ERROR ./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--2-0!./src/components/formInput/style.scss
Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }    at validate (/mnt./src/routes/category/index.js
 @ ./src/routes/category/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```
Note this hit vue at the same time https://github.com/vuejs/vue-cli/issues/4513

**If the current behaviour is a bug, please provide the steps to reproduce.**
Create a new preact project, the demo with a header is fine.
`npm install sass-loader@8.0.0 node-sass`
Rename the existing css file to a `.scss` file in one of the components.
`npm run start`

**What is the expected behaviour?**
Runs as usual, it works with `sass-loader@7.3.1` but not `8.0.0`

**If this is a feature request, what is motivation or use case for changing the behaviour?**
`sass-loader` seems to be officially listed in the documentation, maintaining support would be pleasant.

**Please mention other relevant information.**

Please paste the results of `preact info` here.

```
> preact info

         ▄▄ 
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌ 
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 2.2.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
For help with a specific command, enter:
  preact help [command]

  create [template] [dest]  Create a new application.
  build [src] [dest]        Create a production build in build/
  watch [src]               Start a development live-reload server.
  serve [dir]               Start an HTTP2 static fileserver.
  list                      List all official templates

Options:
  -h, --help  Show help                                                [boolean]

Unknown argument: info
```
_Is this an outdated command line option or issue template?_

**Comment by peabnuts123** [comment]
Just commenting to confirm this behaviour in my project too. I'm not sure what change needs to be made here, however.

**Comment by lsahil** [comment]
+1 Downgrading to sass-loader@7.3.1 works.

**Comment by peterbe** [comment]
`yarn add sass-loader@7.3.1` and now it starts.

**Comment by jliebrand** [comment]
Friendly ping - is anyone looking at this?

**Comment by rajivkr** [comment]
Any update wrt this?

**Comment by zgoda** [comment]
Now because of Webpack 4 it's incompatible with sass-loader 11.

**Comment by rschristian** [comment]
Closing, we've supported `sass-loader` v10+ for a while now and it's the best we can do on Webpack v4.
