### ISSUE TITLE
Site not configured @ clidemo.preactjs.com

### ISSUE THREAD

**Issue by pnfcre** [preactjs/preact-cli#881]
**Do you want to request a _feature_ or report a _bug_?**
Reporting a bug.

**What is the current behaviour?**
Visiting https://clidemo.preactjs.com from the repo URL gives an error.

**If the current behaviour is a bug, please provide the steps to reproduce.**
- Open https://clidemo.preactjs.com.

**What is the expected behaviour?**
Something useful should be there, I guess, since it's the repo URL.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
(Not relevant)

**Please mention other relevant information.**

Please paste the results of `preact info` here.
(Not relevant)

**Comment by pnfcre** [comment]
Note: Most likely a typo of https://cli-demo.preactjs.com.

**Comment by cperezc** [comment]
Both https://clidemo.preactjs.com and https://cli-demo.preactjs.com are not working anymore...

**Comment by ForsakenHarmony** [comment]
https://cli-demo-next.preactjs.com/ 🙃

**Comment by prateekbh** [comment]
@developit :(

**Comment by prateekbh** [comment]
can someone edit the link on the repo?

**Comment by reznord** [comment]
I am doing it.

**Comment by prateekbh** [comment]
Paging @developit

**Comment by pnfcre** [comment]
Looks like this has been resolved! Thanks 🎉
