### ISSUE TITLE
High Code Injection vulnerability

### ISSUE THREAD

**Issue by interdigitize** [preactjs/preact-cli#883]
**Do you want to request a _feature_ or report a _bug_?**: report a bug

**What is the current behavior?** 
A friend was telling me how much more efficient Preact is than React so I decided to install it and build something. After running `npm install ...`, I noticed that there is a high code injection vulnerability warning. 
High: Code Injection 
Package: js-yaml
Patched in: >=3.13.1
Dependency of: preact-cli [dev]
Path: preact-cli > css-loader > cssnano > postcss-svgo > svgo > js-yaml
More info: [https://npmjs.com/advisories/813](https://npmjs.com/advisories/813)

**If the current behavior is a bug, please provide the steps to reproduce.**

Pull the latest version: 2.2.1
In a terminal, run `npm install` then `npm audit`

**What is the expected behavior?**
That there is not a high vulnerability when a user installs preact-cli. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
preact-cli requires version 0.28.11 of css-loader. The most recent version is 3.2.0: [https://www.npmjs.com/package/css-loader](https://www.npmjs.com/package/css-loader)

Please paste the results of `preact info` here.
Not relevant

**Comment by ForsakenHarmony** [comment]
Just to clarify, this doesn't affect us, only `safeLoad` is used in our dependencies

Also you'd kinda need untrusted input for it to do something harmful, which shouldn't happen on your local machine with a config file

I think this might be fixed in the current rc as well, 2.x hasn't gotten an update in a while

**Comment by osdiab** [comment]
chiming in that this is still popping up a year later - is there a high likelihood of something breaking by bumping the version?

**Comment by osdiab** [comment]
oh - looks like the problem on my project is not from preact-cli. I think this can probably be closed since the version of `css-loader` has long since been bumped.
