### ISSUE TITLE
Unable to use preact.config.js TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by lsahil** [preactjs/preact-cli#888]
**Do you want to request a _feature_ or report a _bug_?**
bug
**What is the current behaviour?**
Using latest cli (preact-cli 2.2.1) to generate sample project add preact.config.js from 

https://github.com/preactjs/preact-cli/wiki/Config-Recipes#merge-static-assets-with-the-build-folder
Trying to start the project or build it gives the following error 
preact TypeError: Cannot read property 'emit' of undefined

Not sure what i am doing wrong or missing about preact.config.js
**If the current behaviour is a bug, please provide the steps to reproduce.**

Use yarn option in cli 
yarn add copy-webpack-plugin --dev
Add the mentioned config
yarn build

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

react info
         ▄▄
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌ 
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌ 
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 2.2.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
For help with a specific command, enter:
  preact help [command]

Commands:
  create [template] [dest]  Create a new application.
  build [src] [dest]        Create a production build in build/
  watch [src]               Start a development live-reload server.
  serve [dir]               Start an HTTP2 static fileserver.
  list                      List all official templates

Options:
  -h, --help  Show help                                                [boolean]

Unknown argument: info

Is there a stabler version of cli i can use ? Thanks for any help.

**Comment by psabharwal123** [comment]
you need to paste results of preact info not react info

**Comment by psabharwal123** [comment]
also try using the latest version which is v3.0.0-rc4

**Comment by lsahil** [comment]
That was a mis type but the result is the same .

ahillamba@Hyperpod ~/D/S/preact-webapp> preact info
         ▄▄
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌ 
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌ 
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 2.2.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
For help with a specific command, enter:
  preact help [command]

Commands:
  create [template] [dest]  Create a new application.
  build [src] [dest]        Create a production build in build/
  watch [src]               Start a development live-reload server.
  serve [dir]               Start an HTTP2 static fileserver.
  list                      List all official templates

Options:
  -h, --help  Show help                                                [boolean]

Unknown argument: info



Will try v3.0.0-rc4 .

**Comment by psabharwal123** [comment]
Sounds good, it seems that command was added somewhere in v3

**Comment by prateekbh** [comment]
Please re-check with v3 and re-open if it still exist
