### ISSUE TITLE
preact cli exits with status code 0 even if there are build errors

### ISSUE THREAD

**Issue by psabharwal123** [preactjs/preact-cli#889]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
preact cli exits with status code 0 even if there are build errors, which causes CI systems to mark build as successful.

**If the current behaviour is a bug, please provide the steps to reproduce.**
a simple way to repro - throw an exception in preact.config.js file

**What is the expected behaviour?**
build fails with sttus code other than 0

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.4

**Comment by psabharwal123** [comment]
fixed by https://github.com/preactjs/preact-cli/pull/884

**Comment by luhis** [comment]
is there an estimate on when the next Release Candidate will drop?  this bug is interfering with my workflow a bit

**Comment by prateekbh** [comment]
this is included in rc6
