### ISSUE TITLE
Demo (https://clidemo.preactjs.com/) not working

### ISSUE THREAD

**Issue by caebozzini** [preactjs/preact-cli#893]
**Do you want to request a _feature_ or report a _bug_?**
Bug.
**What is the current behaviour?**
Demo (https://clidemo.preactjs.com/) landing page is a "Site not configured" on WebFaction hosting.

**Comment by prateekbh** [comment]
New home : cli-demo-next.preactjs.com

**Comment by caebozzini** [comment]
Repository landing page still lists and redirects to https://clidemo.preactjs.com/.

**Comment by developit** [comment]
this should be fixed once DNS propagates.

**Comment by caebozzini** [comment]
Sorry if this is bothering, but https://clidemo.preactjs.com/ is still the listed demo URL and the same error as in my original post persists.
