### ISSUE TITLE
The default blueprint/template isn't able to execute tests.

### ISSUE THREAD

**Issue by givanse** [preactjs/preact-cli#901]
If you create a new project and try to run the tests:
```
preact create default foobar
npm run test
```

You get this error.
```
Validation Error:

  Preset jest-preset-preact not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html
```

Using that default template is what the preact tutorial asks you to do.

**Comment by givanse** [comment]
A default Jest configuration should be part of the default set up you get when following along the tutorial.

**Comment by reznord** [comment]
This is fixed in the default template with the following PR - https://github.com/preactjs-templates/default/pull/31
