### ISSUE TITLE
How to create a 10.x preact project?

### ISSUE THREAD

**Issue by shunia** [preactjs/preact-cli#903]
Sorry for not to follow the issue template but the questions are simple:

1. How can I create a new 10.x preact project?
2. Is there anyway to upgrade a 8.x preact project to 10.x by preact-cli for now or in the future?

**Comment by prateekbh** [comment]
Yarn add preact@latest preact-router@latest preact-render-to-string@latest

**Comment by ForsakenHarmony** [comment]
We'll update the templates soon when we have the async component for preact 10 ready

**Comment by suhaotian** [comment]
@prateekbh can't build. don't do that

**Comment by prateekbh** [comment]
Which version of Preact cli are ubat?

**Comment by suhaotian** [comment]
latest

**Comment by ForsakenHarmony** [comment]
Which error are you getting? Can't read your mind sadly 🙃

**Comment by vinaybedre** [comment]
> We'll update the templates soon when we have the async component for preact 10 ready

Is there any open PR for this?

**Comment by suhaotian** [comment]
@ForsakenHarmony Hey. This is the `yarn build` screenshot error message:

![image](https://user-images.githubusercontent.com/6512574/66791877-af486b80-ef28-11e9-87b4-d4ea707929f1.png)

**Comment by chase** [comment]
@suhaotian Not sure if you're still having issues, but it might be worth trying `preact-cli@rc` which is what the default Preact X template uses.

**Comment by suhaotian** [comment]
@chase yeah ok now!

**Comment by rosenbjerg** [comment]
Seems these challenges are all solved by now. I suggest closing this issue.
