### ISSUE TITLE
Installing 3.0.0-rc.6 causes BSOD on WSL

### ISSUE THREAD

**Issue by spongessuck** [preactjs/preact-cli#904]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behaviour?**
BSOD on Windows 10

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. Used VS Code to start a remote session with my Ubuntu WSL installation
2. Open integrated terminal
3. Run `npm i -g preact-cli@3.0.0-rc.6

**What is the expected behaviour?**
preact-cli installs successfully

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
n/a

**Comment by ForsakenHarmony** [comment]
This happened more than once?

**Comment by spongessuck** [comment]
Yes, I tried it twice and got a BSOD each time, though with different failure codes; the first time it was a KERNEL_SECURITY_CHECK_ERROR, IIRC. I can't remember what it was the second time but it was different.

Afterward I tried installing 3.0.0-rc.6 in a regular Powershell window and it worked fine. I only had a problem while in a WSL terminal.

**Comment by spongessuck** [comment]
I've installed the current preact-cli@2.2.1 successfully on the WSL installation, so it seems peculiar to the 3.0.0-x releases.

**Comment by mseddon** [comment]
If you can reproduce this again, could you include a capture of the bsod? I personally never experienced this with 3.0.0-rc.6 under amd64 here.

**Comment by ForsakenHarmony** [comment]
I'll close this for now

If you can somehow figure out which dependency causes it we can maybe try to fix it, but with the information we have right now I don't think there's much we can do

**Comment by mseddon** [comment]
Agreed. Either you get a pr to review or not. 😄

**Comment by spongessuck** [comment]
Fair enough. Just wanted to put this in in case someone else runs into it.

**Comment by mseddon** [comment]
As above, quite happy to help with debugging this issue, but until I can reproduce locally it seems tricky
