### ISSUE TITLE
 Conflict: Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by mfbx9da4** [preactjs/preact-cli#906]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
Build gives following warning 

```
⚠ WARN Conflict: Multiple assets emit different content to the same filename bundle.7e56a.css
⚠ WARN Conflict: Multiple assets emit different content to the same filename route-home.chunk.e6c71.css
⚠ WARN Conflict: Multiple assets emit different content to the same filename route-profile.chunk.62c75.css
⚠ WARN Conflict: Multiple assets emit different content to the same filename bundle.7e56a.css
⚠ WARN Conflict: Multiple assets emit different content to the same filename route-home.chunk.e6c71.css
⚠ WARN Conflict: Multiple assets emit different content to the same filename route-profile.chunk.62c75.css
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

preact create default blah
preact build

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

**Comment by prateekbh** [comment]
This is ok and can be ignored for now.

This happens because both legacy and modern JavaScript has same css and thus generate same css.

//@developit were you looking for something to skip CSS generation next time?

**Comment by gtsop** [comment]
@prateekbh  Any updates on this? How can we resolve it? Having these warnings in the console is not ok, it makes it harder to quickly spot usefull output.

**Comment by prateekbh** [comment]
should be fixed by https://github.com/preactjs/preact-cli/pull/981
