### ISSUE TITLE
Styled Components Prerender Critical CSS Preact Cli

### ISSUE THREAD

**Issue by mfbx9da4** [preactjs/preact-cli#907]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behaviour?**
No critical css from styled components being prerendered

**If the current behaviour is a bug, please provide the steps to reproduce.**

The only custom config is in `preact.config.js` for loading styled components

```js
    let { rule } = helpers.getLoadersByName(config, 'babel-loader')[0]
    let babelConfig = rule.options
    babelConfig.plugins.push(
      'styled-components',
    )
```

I am not using a custom `template.html` [See here for full config](https://github.com/mfbx9da4/instructorlist-frontend/tree/master/instructorlist-preact)

I did see https://github.com/preactjs/preact-cli/issues/561 but there doesn't seem to be any resolution.

**Please mention other relevant information.**
```
"preact": "10.0.0",
"preact-cli": "3.0.0-rc.1",
"styled-components": "4.3.2",
```

**Comment by nightpool** [comment]
Any update on this? Is it possible to use styled components with prerendering?

**Comment by rschristian** [comment]
@nightpool This looks like it should work: https://github.com/preactjs/preact-cli/issues/844#issuecomment-608130399

Let me know if it does and I'll close this out.

**Comment by rschristian** [comment]
Going to close this out as it should work.
