### ISSUE TITLE
easy to replicate (but weird) bug with aliasing React to Preact

### ISSUE THREAD

**Issue by matthewliufavor** [preactjs/preact-cli#912]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behaviour?**

**1.** Suppose I am creating a new project from scratch.

`npx preact-cli create default preact-starter`
`cd preact-starter`
`npm i  # everything at this point is working` 👍

**2.** Now let's say I want to use `react-redux` (or other react libraries) in my project. As per https://preactjs.com/guide/v10/getting-started/ and https://preactjs.com/guide/v10/upgrade-guide#preact-redux, I'll need to alias react to preact. 

**3.** I therefore add a `preact.config.js` file (at the root level, aka in the same directory as package.json) and add the following
```
export default (config, env, helpers) => {
  config.resolve = { 
    "alias": { 
      "react": "preact/compat",
      "react-dom/test-utils": "preact/test-utils",
      "react-dom": "preact/compat",
    },
  }
}
```

4. I run `npm start`, but I get this err msg.

```
Build failed!

✖ ERROR ../node_modules/preact-cli/lib/lib/entry.js
Module not found: Error: Can't resolve 'preact-cli-entrypoint' in './node_modules/preact-cli/lib/lib'
 @ ../node_modules/preact-cli/lib/lib/entry.js 31:25-57 37:29-61 58:18-66 58:61-65
 @ multi ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
✖ ERROR BabelEsmPlugin: ../node_modules/preact-cli/lib/lib/entry.js
Module not found: Error: Can't resolve 'preact-cli-entrypoint' in './node_modules/preact-cli/lib/lib'
 @ ../node_modules/preact-cli/lib/lib/entry.js 29:25-57 35:29-61 56:18-66 56:61-65
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8080 ../node_modules/webpack/hot/dev-server.js ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

For whatever reason preact can't find the entrypoint, but I don't know why 😔

**What is the expected behaviour?**
I would expect that I'd be able to alias react to preact by following the docs.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
N/A

**Please mention other relevant information.**
*Note*: this is a contrived example for a problem where I have a project that is being upgraded from preact 8 to 10, and I had to switch from `preact-redux` to `react-redux`. Unfortunately, react-redux is not being recognized, hence the need to alias react to preact (but that is not working)

**Environment Info:**

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    preact: ^10.0.1 => 10.0.4 
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.6 
    preact-render-to-string: ^5.1.0 => 5.1.1 
    preact-router: ^3.0.0 => 3.1.0 
```

**Comment by prateekbh** [comment]
For cli, these aliases should already be there IIRC

**Comment by matthewliufavor** [comment]
I don't know, but if it is there, it's not working for me. I get this error when I try to use `react-redux` with preact.

```
⚠ WARN ./node_modules/react-redux/es/components/connectAdvanced.js
111:33-40 "export 'useMemo' was not found in 'react'
 @ ./node_modules/react-redux/es/components/connectAdvanced.js
 @ ./node_modules/react-redux/es/index.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

Regardless: I don't understand why adding the above block of code to `preact.config.js` is breaking. That's the same block of code from the docs (from preact 10 no less)

**Comment by matthewliufavor** [comment]
@prateekbh very interesting, so I did some digging.

- It seems like **manually** adding the aliases, as per the docs, doesn't seem to work at all (in the example `preact-starter` I fiddled around with the versions). I tried: preact v10 + preact-cli v2, preact v10 + preact-cli v3, preact v8 + preact-cli v2. No bueno for any of them - all get the same entry point err msg.

- But yes, built-in aliases were added in `preact-cli`, but ONLY for v3 of preact-cli. https://github.com/preactjs/preact-cli/commit/6f9dee118a96744281a831fa91e82ffde368f173. And it works (at least with `react-redux`)! I don't need to add any manual aliases. 👍

HOWEVER, I do have a final question now: is there an ETA for when v3 preact-cli will become a full-fledged release? I really want to upgrade preact 8 to 10, but (based upon the fact I need `react-redux` and other factors) I will also need v3 preact-cli. However, there are currently things missing in v3 preact-cli (e.g. the `serve` command was removed https://github.com/preactjs/preact-cli/releases/tag/v3.0.0-next.1 that are a pain to deal with).

Thank you for your time.

**Comment by ForsakenHarmony** [comment]
@matthewliufavor yeah we decided to remove `serve`, there's other packages that can do it equally or better

Is there anything else missing? (other than async components which are the last thing we're working on)

**Comment by matthewliufavor** [comment]
@ForsakenHarmony that was the only 1 I noticed. And thanks for the reply. I appreciate very much everything you guys are doing :)

**Comment by cquinders** [comment]
@matthewliufavor are aliases for `react` and `react-dom` still working for you with `preact-cli` v3 and `react-redux`? I tried with preact-cli v3 and react-redux v5, v6, and v7 without luck. Im running into the same issues you described above.

Could you tell me which versions you are running?

Thanks!

**Comment by matthewliuswims** [comment]
try `preact-cli` with "^v3.0.0-rc.7" and `react-redux` with "^7.1.3"
