### ISSUE TITLE
Cannot use a preact-app on the server with an url+path

### ISSUE THREAD

**Issue by mweissen** [preactjs/preact-cli#914]
**Do you want to request a _feature_ or report a _bug_?**
a bug

**What is the current behaviour?**
I have installed the demo program and I write

> https://pwa.mydomain.com:8443/profile

to the command line and it crashes with a "404 Not found" nginx error.

**If the current behaviour is a bug, please provide the steps to reproduce.**
I have opened a new preact directory with 

> preact create default pwa11

_I did not change anything else._ Then I created a build with 

> cd pwa11
> preact build

This build goes to my server. I call it with

> https://pwa.mydomain.com:8443

and it seems to work perfect. A click on "Me" gives in the address field

> https://pwa.mydomain.com:8443/profile

and it  shows the usual page.

Now I **write** or **copy** **the same URL**

> https://pwa.mydomain.com:8443/profile

to the address field and it crashes with a "404 Not found" nginx error.

**What is the expected behaviour?**
The same webpage as with a click to "Me"

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

I have build a pwa with preact-cli@2.2.1 and this old build works without any problems.

This is the console message:

> Error in event handler: TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at chrome-extension://agnoocojkneiphkobpcfoaenhpjnmifb/Resources/JavaScript/content.js:315:37

If I try the same on my local computer with 

> preact watch

and 

> http://localhost:8080/profile

there is no problem.

Please paste the results of `preact info` here.

> Environment Info:
> 
>   System:
>     OS: Windows 10
>     CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
>   Binaries:
>     Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
>     npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: 44.18362.387.0
>   npmPackages:
>     preact: ^10.0.1 => 10.0.4
>     preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.6
>     preact-render-to-string: ^5.1.0 => 5.1.1
>     preact-router: ^3.0.0 => 3.1.0

**Comment by mikolaj6r** [comment]
Is your nginx configured to always serve index.html ?
