### ISSUE TITLE
favicon configuration support

### ISSUE THREAD

**Issue by givanse** [preactjs/preact-cli#915]
Currently the webpack config assumes that if you want to use a favicon it'll grab it from `src/assets/favicon.ico` otherwise it uses none.

https://github.com/preactjs/preact-cli/blob/f21948c8c4b078c03833c57b2163a2810bc4d79c/packages/cli/lib/lib/webpack/render-html-plugin.js

This is not considering the case where the favicon is fetched remotely.

```
<link rel="shortcut icon" type="image/png" href="https://...">
```

One possibility is to add a config option in the `preact.config.js` that then is read and applied on the render-html-plugin. I don't think that is a great idea.

Little trivial tasks like this one wouldn't be a topic of [continued discussion](https://github.com/preactjs/preact-cli/search?q=favicon&type=Issues) if the [`index.html` was exposed by default](https://github.com/preactjs/preact-cli/issues/51). So, that people can use standard web features that are already documented elsewhere.

**Comment by prateekbh** [comment]
This should be taken care on in V3, because of what you said.

All new projects have a default `template.html` exposed under `src`.

If not, follow this: https://preactjs.com/cli/getting-started/
