### ISSUE TITLE
CSS :root {} is not inlined on SSR

### ISSUE THREAD

**Issue by pimdewit** [preactjs/preact-cli#919]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behaviour?**
CSS Custom properties defined using `root` (`:root {}`) are not being inlined when running SSR.

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. init cli
2. add scss (not sure if this is related)
3. add a "global" stylesheet, imported in the app's entrypoint (src/index.js)
4. define `:root {}` with a custom property
5. run SSR
6. note how it is not inlined unlike any other styles

**What is the expected behaviour?**
:root {} and all its defined custom properties to be inlined on pre-render.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
CSS variables potentially have a huge impact on first meaningful paint, JS-disabled environments, and more.

**Please mention other relevant information.**

Please paste the results of `preact info` here.
```
Environment Info:

  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.36
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    preact: ^10.0.5 => 10.0.5
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.6
    preact-render-to-string: ^5.1.1 => 5.1.1
    preact-router: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.6
```

**Comment by prateekbh** [comment]
can you please re-check with rc7?

**Comment by pimdewit** [comment]
@prateekbh It works on rc7 👍
