### ISSUE TITLE
Too long filenames

### ISSUE THREAD

**Issue by montyx99** [preactjs/preact-cli#924]
I use version preact-cli 2.2.1. As far as I see this is the latest stable version.

**Do you want to request a _feature_ or report a _bug_?**
question
**What is the current behaviour?**
The build generates hashes into the file names, which are too long.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Make a default project, and try to build it.

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
I'm working on a low memory device web UI, and there is forbidden to use filename (includes full path) longer than 32 characters. The build creates many files with very long filenames. I hope that if I don't have the hash in the file names, I can use the result on my device. If you have any useful workaround, I appreciate that.

Please paste the results of `preact info` here.

**Comment by developit** [comment]
@montyx99 sorry for the long delay! You can disable filename hashing:

Create a file `preact.config.js` in your repo root containing the following:

```js
module.exports = function(config) {
  config.output.filename = '[name].js';
  config.output.chunkFilename = '[name].chunk.js';
};
```

**Comment by developit** [comment]
I'm going to close since the above should work fine for your use-case, but please let me know if this is still an issue.
