### ISSUE TITLE
3.0.0-rc.6 does not contain PR#884

### ISSUE THREAD

**Issue by chase** [preactjs/preact-cli#926]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
3.0.0-rc.6 does not include https://github.com/preactjs/preact-cli/pull/884

**If the current behaviour is a bug, please provide the steps to reproduce.**
`cat node_modules/preact-cli/lib/lib/entry.js`
Note the changes are not available.

**What is the expected behaviour?**
The changes should be available on NPM.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
N/A

**Please mention other relevant information.**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.17.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.3 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
  npmPackages:
    preact: ^10.1.0 => 10.1.0 
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.6 
    preact-render-to-string: ^5.1.2 => 5.1.2 
    preact-router: ^3.1.0 => 3.1.0 
```

**Comment by psabharwal123** [comment]
@chase seems like rc7 has it, this can be closed :)

**Comment by chase** [comment]
Thanks @psabharwal123 :+1:
