### ISSUE TITLE
warnings when building with scss files

### ISSUE THREAD

**Issue by AEnterprise** [preactjs/preact-cli#927]
**Do you want to request a _feature_ or report a _bug_?**
bug report

**What is the current behaviour?**
When doing ``npm run build`` you get a bunch of warnings about multiple outputs to the same file when using scss

**If the current behaviour is a bug, please provide the steps to reproduce.**
have scss files in the styles folder, use them in your project and run ``npm build``
project repo: https://github.com/gearbot/Dashboard
build output: https://github.com/gearbot/Dashboard/commit/076f2d0350cf5ef06dd25b33ce4c62918eed962c/checks?check_suite_id=359487917#step:6:64

**What is the expected behaviour?**
No warnings about writing to the same file multiple times

Please paste the results of `preact info` here.

```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    preact: ^10.1.0 => 10.1.0
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.6
    preact-compat: ^3.19.0 => 3.19.0
    preact-render-to-string: ^5.1.2 => 5.1.2
    preact-router: ^3.1.0 => 3.1.0
```

**Comment by prateekbh** [comment]
This should be fixed in : https://github.com/preactjs/preact-cli/pull/981
