### ISSUE TITLE
reloading page after hotreloading css

### ISSUE THREAD

**Issue by AEnterprise** [preactjs/preact-cli#928]
**Do you want to request a _feature_ or report a _bug_?**
bug report

**What is the current behaviour?**
When only changing css in the project it first hotreloads the project, then hits a 404 and reloads the page

**If the current behaviour is a bug, please provide the steps to reproduce.**
- run ``npm run dev`` 
- change only css
- see it hotreload css
- instantly followed by the entire page reloading
- if you got "preserve log" enabled in the console you'll see there was a 404

**What is the expected behaviour?**
For it to only hotreload css

Please paste the results of `preact info` here.
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    preact: ^10.1.0 => 10.1.0
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.6
    preact-compat: ^3.19.0 => 3.19.0
    preact-render-to-string: ^5.1.2 => 5.1.2
    preact-router: ^3.1.0 => 3.1.0
```

**Comment by prateekbh** [comment]
I tried the steps couldn't reproduce the bug.

Can you try in a fresh repo and confirm if it happens there as well?

**Comment by AEnterprise** [comment]
i can repro with:
- run commands:
```
npm install -g preact-cli@rc
preact create default test
cd test
```
- then rename index.css to index.scss
- go into the index.js and replace the css import to ``import './style/index.scss';``

- then
```
npm install --save-dev node-sass sass-loader@7.1.0
npm run dev
```
- go to ``localhost:8080`` in browser (used chrome)
- open dev tools, go into console settings, enable "preserve log"
- change something in the css (like height to 50% instead of 100%) and save the file
- go back to page and dev tools
- see 404 and page reload in dev tools
![image](https://user-images.githubusercontent.com/5206666/71076566-39f65280-2186-11ea-8f53-85b010a3bb5b.png)

**Comment by AEnterprise** [comment]
do those steps work for you?

**Comment by prateekbh** [comment]
Sorry trying to carve time out for this one.

**Comment by Inviz** [comment]
Same issue, not only with css but with other type of changes as well. First you see the change, and then it still reloads again.

**Comment by prateekbh** [comment]
@Inviz are you windows as well?

**Comment by NicolaiSchmid** [comment]
For me the issue persists across macOs Catalina and arch Linux

**Comment by prateekbh** [comment]
will take a look today

**Comment by prateekbh** [comment]
This is coming from `--esm`.
For immediate fix please use ``--no-esm` with watch.

@developit @ForsakenHarmony is it ok if watch work without esm?

**Comment by Inviz** [comment]
Holy molly! it works now without --no-esm! Yahoo! Thank you @prateekbh
