### ISSUE TITLE
Dev mode reloads page every 30 seconds, even without changes

### ISSUE THREAD

**Issue by kevlened** [preactjs/preact-cli#933]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
The app refreshes every 30 seconds, even without changes. This is frustrating, because when inspecting element styles in dev tools, the element must be found and modified every 30 seconds (between each refresh).

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. `preact create simple preact-reload-test`
1. `cd preact-reload-test`
1. `yarn start`
1. wait 30 seconds for the page to reload without changes (optionally: watch with Chrome dev tools)

<img width="577" alt="Screen Shot 2019-12-26 at 2 35 32 PM" src="https://user-images.githubusercontent.com/955312/71488172-2170e280-27ed-11ea-9904-8a45bfaf0b53.png">

**What is the expected behaviour?**
Only refresh when there are changes

**If this is a feature request, what is motivation or use case for changing the behaviour?**
N/A

**Please mention other relevant information.**
```
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    preact: ^10.1.0 => 10.1.1 
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.6 
    preact-render-to-string: ^5.1.2 => 5.1.3 
```

**Comment by reznord** [comment]
Couldn't reproduce this locally with the steps mentioned above. 

Can you share a small repo for this issue?
