### ISSUE TITLE
"preact watch" exits on error in v3.0.0-rc.7

### ISSUE THREAD

**Issue by hesselbom** [preactjs/preact-cli#939]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behaviour?**
When starting "preact watch" with a syntax error, or getting a syntax error while developing, preact will exit with status code 1. In previous versions (v3.0.0-rc.6) it would show the error, not exit, and continue to watch for changes until the error is fixed.

What happens now is I have to rerun "preact watch" manually every time I get an error.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Create a project with latest version of preact-cli, v3.0.0-rc.7, with a index.js file containing a syntax error.

**What is the expected behaviour?**
It should not exit, allowing me to continue developing without manually restarting.

**Please mention other relevant information.**
Might be related to #884, I suppose it should exit with 1 if building but maybe with 0 when "preact watch"-ing?

**Comment by psabharwal123** [comment]
sorry about that @hesselbom

**Comment by prateekbh** [comment]
@ForsakenHarmony can this be closed?

**Comment by ForsakenHarmony** [comment]
Yes, but needs a new release

**Comment by hesselbom** [comment]
@prateekbh Any estimate on next release date? :)

**Comment by hesselbom** [comment]
Now works with version v3.0.0-rc.9!

**Comment by ForsakenHarmony** [comment]
Sorry about the long wait
