### ISSUE TITLE
Bump Typescript version to 3.7.4

### ISSUE THREAD

**Issue by oliverstr** [preactjs/preact-cli#942]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behaviour?**
Typescript version is outdated (3.4.5)

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
Bump it to the current latest version (3.7.4)

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Typescript 3.7 came out with some very nice [features](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html), one very important being [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining).

**Comment by prateekbh** [comment]
we would really appreciate a PR to https://github.com/preactjs-templates/typescript/tree/master/template.

Its ok if you you want one of to do as well :)

**Comment by oliverstr** [comment]
But don't we need to update it in the CLI for people who don't use the templates?
https://github.com/preactjs/preact-cli/blob/master/packages/cli/package.json#L126

**Comment by rosenbjerg** [comment]
Perhaps enable dependabot on the template repos, to keep them up-to-date without spending too much developer time on it? :)

**Comment by reznord** [comment]
Right now we are using `3.9.6` in CLI.
