### ISSUE TITLE
custom .babelrc is not getting picked up

### ISSUE THREAD

**Issue by pPanda-beta** [preactjs/preact-cli#949]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Whatever I put in "<project_root>/.babelrc", not configs are picked up. 
Also when I put invalid json, build never fails

**If the current behaviour is a bug, please provide the steps to reproduce.**
It can be reproduced by triggering existing test cases.
Test case name :  **'should use custom \`.babelrc\`'**
```
docker run --rm -it \
  -v $PWD:/preact-cli \
  -w /preact-cli/packages/cli \
   node:10.15.3-jessie \
  bash -c "echo 'Invalid JSON' > tests/subjects/custom-babelrc/.babelrc; npm run test -- --testPathPattern=build.test"
```
---> Ideally build should fail as .babelrc contains invalid json, but all the test cases pass

**What is the expected behaviour?**
It should pick up the changes from root's  .babelrc file. It should fail building if root's .babelrc is not a valid json.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
## This particular commit caused the problem : 
https://github.com/preactjs/preact-cli/commit/a532149a99f95afa9bba31f753761372510d48d8#diff-e8975d611d9d413eecd5c7236e2a7a85R33

Please paste the results of `preact info` here.

```
Environment Info:

  System:
    OS: Linux 4.9 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (10) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  npmPackages:
    preact: ^10.0.0 => 10.2.1
    preact-compat: ^3.18.5 => 3.19.0
    preact-render-to-string: ^5.0.6 => 5.1.3
    preact-router: ^3.0.1 => 3.1.0
```

**Comment by TommyDew42** [comment]
Hi have we fixed it? If not, happy to work on it!

**Comment by rschristian** [comment]
Yes, custom `.babelrc` files have long since worked.

However, it's rather important to note they override matching keys; if `plugins` exists in your custom `.babelrc`, it wipes out every existing plugin in the default Babel config.

See: https://github.com/preactjs/preact-cli#babel

Validating a JSON structure in the config file doesn't make sense to do as Babel supports JS config files as well.
