### ISSUE TITLE
Add support for quick jest setup

### ISSUE THREAD

**Issue by alexanderbird** [preactjs/preact-cli#962]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behaviour?**
No jest setup

**What is the expected behaviour?**
Some easy way to set up Jest. E.g. https://gist.github.com/alexanderbird/8456ca4e01366fb30d9b0660899369ec

**If this is a feature request, what is motivation or use case for changing the behaviour?**
I'm tired of re-googling "jest preact" no "jest preact babel" nah "jest babel" and copy-pasting suggestions into babel config until it works. I'd like it to be easy to add unit testing with Jest.

**Please mention other relevant information.**
Opening this in response to [this tweet from @marvinhagemeister ](https://twitter.com/marvinhagemeist/status/1223233397792944129) to discuss the details.

**Comment by alexanderbird** [comment]
I'll do up a PR, what would be a good approach?

- Maintain template versions that include Jest?
- Provide a `--with-jest` flag that adds Jest and a sample test?

Other notes:

- I'm using Jest for the non-jsx related logic, not the UI -- but a natural next step is setting up Enzyme or some nice way of asserting on rendered components. I don't think that belongs in this PR but could maybe be part of this down the road.

Do you have any tips for me going in to this? I haven't worked on the preact cli before.

**Comment by developit** [comment]
Hi @alexanderbird - I'm actually wondering if we missed something here. I just took at look at the default `preact-cli` template and I'm seeing a Jest setup that looks pretty much the same as your Gist. That makes me think we're actually scaffolding a Jest setup by default, it just isn't working?

Here's what we're doing right now:

- We add a `"test": "jest"` script to the package.json ([source](https://github.com/preactjs-templates/default/blob/3bb003257b3d1057b0a7448dc21712e993ad6678/template/package.json#L14))
- We inject a Jest configuration into the package.json ([source](https://github.com/preactjs-templates/default/blob/3bb003257b3d1057b0a7448dc21712e993ad6678/template/package.json#L40-L46))
- We scaffold a `.babelrc` file with `env.test` similar to your Gist ([source](https://github.com/preactjs-templates/default/blob/master/template/.babelrc))

Maybe we're missing a piece?

**Comment by alexanderbird** [comment]
Ah, it's because I was using the simple template which doesn't have jest.

**Comment by alexanderbird** [comment]
I could just fork the simple template and add jest to it.

**Comment by alexanderbird** [comment]
@marvinhagemeister are you still interested in a PR?

**Comment by alexanderbird** [comment]
I'm going to close this as not a real issue -- if you use the default template you get Jest all set up for you. I'm guessing I'm more of a rare case who wants simple template + jest.
