### ISSUE TITLE
[BUG] SCSS Build failed with "File to import not found or unreadable"

### ISSUE THREAD

**Issue by muuvmuuv** [preactjs/preact-cli#965]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behaviour?**

I'm trying to import a css file from node_module's into a scss file:

```scss
@import "~modern-normalize/modern-normalize.css'";
```

The scss file is imported in my `src/docs/index.js`:

```js
//...
import './style/index.scss'
//...
```

I'm running the following command:

```shell
→ pnpm run docs-watch
→ preact watch --src src/docs
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

```
Build failed!

✖ ERROR ./style/index.scss (./node_modules/.pnpm/registry.npmjs.org/preact-cli/3.0.0-rc.7_76c3f24ebd6d53f057176dd4e3350505/node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--6-0!./style/index.scss)
Module build failed (from ./node_modules/.pnpm/registry.npmjs.org/preact-cli/3.0.0-rc.7_76c3f24ebd6d53f057176dd4e3350505/node_modules/preact-cli/lib/lib/webpack/proxy-loader.js):

@import "~modern-normalize/modern-normalize.css'";
^
      File to import not found or unreadable: ~modern-normalize/modern-normalize.css'.
      in ./src/docs/style/index.scss (line 1, column 1)
 @ ./style/index.scss 2:14-450 21:1-42:3 22:19-455
 @ ./index.js
 @ ./node_modules/.pnpm/registry.npmjs.org/preact-cli/3.0.0-rc.7_76c3f24ebd6d53f057176dd4e3350505/node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/.pnpm/registry.npmjs.org/preact-cli/3.0.0-rc.7_76c3f24ebd6d53f057176dd4e3350505/node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
 ERROR  Command failed with exit code 1.
```

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

It should just use the node_modules's file I import through sass-loaders alias.

**Please mention other relevant information.**

Please paste the results of `preact info` here. ← this seems to not work

```
→ preact info
preact-cli 2.2.1
.....
Unbekanntes Argument: info
```

**Comment by muuvmuuv** [comment]
Wow... just saw by reading my issue that I added a `'` ... `...malize.css'";`

**Comment by ForsakenHarmony** [comment]
`preact info` only works with `preact-cli` v3, which is not fully released as stable yet, but if you're using preact 10 it might be worth using either way
