### ISSUE TITLE
Service worker improvements

### ISSUE THREAD

**Issue by prateekbh** [preactjs/preact-cli#967]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
To make additions in service worker, users currently have to 
1. copy paste the whole [sw.js](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/sw.js) in their `src` folder.
2. find apt place to make the change according to their need
3. make changes amid the 70 lines of code that we have.

**What is the expected behavior?**
1. Ugly details of basic service worker setup should be hidden from the users.
2. Users should be able to import a prebuilt module e.g. `preact/sw` and initialize it in < 5 LOC.
3. Advanced users should be able to add functionality on a clean stale environment

**If this is a feature request, what is motivation or use case for changing the behaviour?**
We want to abstract away the basic service worker setup in a module and make improvements to it  while users can customize additional functionality on top of it.

Currently the option users have for modifications in `sw.js` is to copy the entire thing and make changes to it. This makes us loose all control over their service worker for future releases.

**P.S: We don't want to maintain a full fledged SW library. We just want to govern basic setup and be able to ship improvements/library changes to all the basic users without a breaking change in preact-cli. However, this means that it might still be a breaking change for some advanced users, who can pretty much eject from our `sw` setup anyways.**

**Comment by prateekbh** [comment]
FWIW this is how future `sw.js` would look like for users

```js
import {getPrecachableFilesList, setup} from 'preact/sw';
const files = getPrecachableFilesList();
setup({
  files,
});
```

for any firther customization e.g. runtime strategies

```js
import {getPrecachableFilesList, setup} from 'preact/sw';
const files = getPrecachableFilesList();

/* caching API requests starting with url /api/ */
workbox.routing.registerRoute(
  new RegExp('/api/.*'),,
	new workbox.strategies.NetworkFirst({
		plugins: [
			new workbox.cacheableResponse.Plugin({
				statuses: [200], // only cache valid responses, not opaque responses e.g. wifi portal.
			}),
		],
	})
);

setup({
  files,
});


```

**Comment by developit** [comment]
Just dropping a note here - I came up with this workaround version of the above for the preact website ([here](https://github.com/preactjs/preact-www/blob/master/src/sw.js)):

Contents of `src/sw.js`:

```js
// "import" the existing Preact CLI implementation (just inlines it):
import 'preact-cli/lib/lib/sw.js';

// add our own logic:
addEventListener('install', e => {
  // etc
});
```

**Comment by prateekbh** [comment]
**Note:** If we ever add a catch all route, this would fail. Any runtime strategy added after `import 'preact-cli/lib/lib/sw.js';` would be meaningless

**Comment by harshitkumar31** [comment]
What do we plan to do in the setup method? Anything specific to preact ? If not, we could simply use workbox.

**Comment by prateekbh** [comment]
Plan is to actually use work box but hide it behind Preact apis PARTIALLY.

The end result will be a mix of Preact API and workbox. 

For basic users just Preact APIs will suffice.

For advanced users they will need to use workbox APIs as well

**Comment by harshitkumar31** [comment]
I'd like to help with this, once the requirements are finalised.

**Comment by JCofman** [comment]
I was wondering is there an easy way that we can include to get a reference to the service worker in your application code. For example if you want to message between the application code and the service worker. This issue #955 has definitely some similarities :)

**Comment by prateekbh** [comment]
Yes these utilities can be shipped as inbuilt plugins as well

**Comment by prateekbh** [comment]
@harshitkumar31 sorry for taking this over. We can still use help with https://github.com/preactjs/preact-cli/pull/1049#issuecomment-601864284
