### ISSUE TITLE
Upgrading to Preact 10.3.1 causes compat.module.js?de84:1 Uncaught TypeError: Cannot read property 'class' of undefined at Object.__WEBPACK_IMPORTED_MODULE_1_preact__.options.vnode 

### ISSUE THREAD

**Issue by Anwardo** [preactjs/preact-cli#968]
Working on upgrading my project to Preact X from Preact 8. When trying to use the latest version of Preact I'm getting the following error:

`compat.module.js?de84:1 Uncaught TypeError: Cannot read property 'class' of undefined
    at Object.__WEBPACK_IMPORTED_MODULE_1_preact__.options.vnode `

Weirdly enough this error doesn't occur in the earlier versions I tested (10.2 and lower).

The error seems to occur on line 21 in preact.js, which is the following line:
`if (void 0 !== options.vnode) options.vnode(p);`

It's happening when trying the render the following code from my codebase:

```
return str.split('<br/>').map((item,index) => {
	return index === str.split('<br/>').length -1 ? <span>{item}<span tabindex="0" aria-label={requiredMarkLabel} className="required-mark">*</span><br/></span> : <span>{item}<br/></span>
})
```

But if I change that line the same error will just move to a different part of the code. Any idea what could be the issue here?

**Comment by developit** [comment]
I moved this issue to `preact-cli` since it relates to CLI upgrades, not Preact upgrades. Preact CLI v2 was never made to be compatible with Preact X, so upgrading both at the same time is the only option.

**Comment by Anwardo** [comment]
That did the trick! Thanks 👍
