### ISSUE TITLE
Plugin linked on README.md does not work

### ISSUE THREAD

**Issue by piazz** [preactjs/preact-cli#969]
**Do you want to request a _feature_ or report a _bug_?**
Bug.

**What is the current behaviour?**

The CLI plugin [preact-cli-svg-loader](https://github.com/pmcalmeida/preact-cli-svg-loader/blob/master/src/index.js) listed in the [https://github.com/preactjs/preact-cli/wiki/Plugins](Wiki) (and linked on the README) doesn't work.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Trying to install said plugin plugin results in the error:

`TypeError: Cannot read property 'push' of undefined`

After inspecting the config object in `preact.config.js`, I saw that the line from the plugin `config.module.loaders.push` will fail because there is no such object. If I change it to `config.module.rules.push`, it works as expected. I'm not super familiar with webpack - I assume there was some breaking API change this plugin never updated to.

**What is the expected behaviour?**

Either fix plugins, or don't link them on the main README :)

**If this is a feature request, what is motivation or use case for changing the behaviour?**

Help poor noobs like me have a less terrifying Preact onboarding experience.

**Please mention other relevant information.**

I'm happy to file a PR against this particular plugin, but I would want to understand the issue better first.

**Comment by ForsakenHarmony** [comment]
Which version of preact-cli are you using? previous plugins are not compatible with preact-cli v3 because of webpack api changes

**Comment by piazz** [comment]
I'm using v3 of the CLI. Sounds like the task here is to remove the link to the wiki on the README, or add a disclaimer.

**Comment by SolarLiner** [comment]
If marking the SVG plugin as not working for v3, I've just made the change in the wiki. If that's all needed, we can close this.
